### ISSUE TITLE
aternos.org

### ISSUE THREAD

**Issue by ExtendLord** [jspenguin2017/uBlockProtector#1123] opened 2020-09-19 11:13 UTC
### Screenshot of the web page (including address bar and extension icons) (required):
![image](https://user-images.githubusercontent.com/26222159/93665778-f072c500-fa81-11ea-8df4-0b2995d06b3d.png)

### Reproduction steps (optional if trivial):
1. Create an account
2. Create a server (It is free)
3. Go to that server

### Environment (Required):

- Operating System and Version: Windows 10 2004
- Browser and Version: Chrome 85.0.4183.102
- Adblocker and Version: uBlock Origin 1.29.2
- Nano Defender Version: 15.0.0.205

#### Your filter lists (Required):
![image](https://user-images.githubusercontent.com/26222159/93665786-fec0e100-fa81-11ea-8263-52a791e3d808.png)

**Comment by jspenguin2017** [comment] 2020-09-19 15:30
Duplicate of https://github.com/NanoMeow/QuickReports/issues/1643

**Closed by jspenguin2017** 2020-09-19 15:30 UTC
Labels: Duplicate
