### ISSUE TITLE
[Anti-adblock] animesync.tv

### ISSUE THREAD

**Issue by carloshbcabral** [jspenguin2017/uBlockProtector#988] opened 2018-09-11 21:14 UTC
### URLs where this issue occurs (Required)
`https://www.animesync.tv/v/x58A4KbyoDln/`

### Screenshots (Required)
![](https://i.imgur.com/WHiccAz.png)

### Screenshot of console (Required, press `F12` to open the console)
![](https://i.imgur.com/KNEw6Gg.png)

### Anything else you believe to be useful (Optional)
Anti-adblock is only activated when Nano Defender is also activated.

#### Environment (Required)

- Operating System and Version: Windows 10
- Browser and Version: Chrome 69
- Nano Adblocker Version: 1.0.0.66
- Nano Defender Version (Optional if you are not using it): 15.0.0.43

#### Your filter lists (Required)
![](https://i.imgur.com/tZHnhvV.png)

**Comment by jspenguin2017** [comment] 2018-09-11 21:18
Duplicate of https://github.com/NanoAdblocker/NanoFilters/issues/181

**Closed by jspenguin2017** 2018-09-11 21:18 UTC
Labels: Duplicate
