### ISSUE TITLE
Generic NoAdBlock defuser

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/uBlockProtector#362] opened 2017-07-09 01:41 UTC
A Cloudflare app, NoAdBlock, caught my attention, despite their claims, it is trivial to make it generic (for now), we already have a DOM watcher anyway, 2 more checks won't change the performance. 
https://noadblock.net/
https://www.cloudflare.com/apps/noadblock
~~They claim to update rules to bypass whitelists weekly, but hopefully removing their app block screen instead of dodging their detection will keep them occupied for longer.~~ Nope, they kept their promise...

**Comment by jspenguin2017** [comment] 2017-07-09 01:53
Seems to work for me. 
```JavaScript
        //NoAdBlock
        if (insertedNode.nodeName === "CLOUDFLARE-APP" &&
            insertedNode.getAttribute("app-id") === "no-adblock") {
            //Log
            a.err("NoAdBlock");
            //Remove element
            insertedNode.remove();
            //Force enable scroll
            $("body").rmClass("adbmodal-cloudflare-open");
            //a.css("html, body { overflow:scroll; }");
        }
```
Test links: 
https://www.cloudflare.com/apps/noadblock/install
https://www.noticiasautomotivas.com.br/
http://www.clubedohardware.com.br/

**Comment by jspenguin2017** [comment] 2017-07-09 01:57
Making it a Cloudflare app is a big mistake 😆

**Comment by uBlock-user** [comment] 2017-07-09 03:40
No wonder it was being difficult to kill as it was loaded via the CF itself and since CF is used by every other website this will come in use.

**Comment by jspenguin2017** [comment] 2017-07-09 03:46
Not sure about that, the app costs $7 per *month*. Now that we have a generic solution, if words spread, this app will die pretty fast.

**Comment by jspenguin2017** [comment] 2017-07-09 04:03
Oh no, it's being featured... I guess the solution is going to be handy after all... 
![image](https://user-images.githubusercontent.com/7283682/27991105-36a313e2-6429-11e7-9426-c91f33ef4df3.png)

**Comment by jspenguin2017** [comment] 2017-07-09 04:05
Wait a second, Admiral is also a Cloudflare app???
https://www.cloudflare.com/apps/admiral

**Comment by jspenguin2017** [comment] 2017-07-09 04:08
NVM, it works differently and loads the payload elsewhere. If a generic solution for Admiral can be found then that would help a lot. They have like 500 random domains...

**Comment by uBlock-user** [comment] 2017-07-09 06:47
It's not made by CF to be specific but CF offers it as a app for deployment.

**Comment by jspenguin2017** [comment] 2017-07-09 14:57
Seems to work for me. Admiral is way more complicated, I might have a look if I got time.

**Comment by ghajini** [comment] 2017-07-15 16:42
here is 1 page i encountered with admiral
site ss: 
http://prntscr.com/fw2c0z

console:
http://prntscr.com/fw2cc8

**Comment by jspenguin2017** [comment] 2017-07-15 16:49
Source dump: https://pastebin.com/nxCjwiWm

I have no generic solution yet, Admiral is pretty robust...

**Comment by ghajini** [comment] 2017-07-15 16:56
what does this code mean

africam.com#%#!function(a,c,b){a&&(Promise=function(e){if('function'!=typeof e)throw new TypeError(e+' is not a function');for(var f=c.call(e),d=0,g=b.length;d<g;d++)if(b[d][0].test(f))return b[d][1]?a.reject(b[d][2]):a.resolve(b[d][2]);return new a(e)},Object.getOwnPropertyNames(a).forEach(function(b){Object.defineProperty(Promise,b,Object.getOwnPropertyDescriptor(a,b))}),a.prototype.constructor=Promise)}(window.Promise,Function.prototype.toString,[[/\.MozBinding\.indexOf\(["']abp-/],[/\.parentNode\.removeChild\([\s\S]*?\.removeEventListener\("error"[\s\S]*?\.createElement\([\s\S]*?\.getElementsByTagName\("head"/,,1],[/\.createElement\("iframe"[\s\S]*?URL\.createObjectURL\(new Blob\(\[""/],[/\.getPropertyValue\("display"\)[\s\S]*?\/tpc\.googlesyndication[\s\S]*?\.addEventListener\(["']message["']/,1]]);
--

**Comment by jspenguin2017** [comment] 2017-07-15 16:58
It's a JS rule I guess, I can unminify it.

**Comment by jspenguin2017** [comment] 2017-07-15 16:59
```js
! function(a, c, b) {
    a && (Promise = function(e) {
        if ('function' != typeof e) throw new TypeError(e + ' is not a function');
        for (var f = c.call(e), d = 0, g = b.length; d < g; d++)
            if (b[d][0].test(f)) return b[d][1] ? a.reject(b[d][2]) : a.resolve(b[d][2]);
        return new a(e)
    }, Object.getOwnPropertyNames(a).forEach(function(b) {
        Object.defineProperty(Promise, b, Object.getOwnPropertyDescriptor(a, b))
    }), a.prototype.constructor = Promise)
}(window.Promise, Function.prototype.toString, [
    [/\.MozBinding\.indexOf\(["']abp-/],
    [/\.parentNode\.removeChild\([\s\S]*?\.removeEventListener\("error"[\s\S]*?\.createElement\([\s\S]*?\.getElementsByTagName\("head"/, , 1],
    [/\.createElement\("iframe"[\s\S]*?URL\.createObjectURL\(new Blob\(\[""/],
    [/\.getPropertyValue\("display"\)[\s\S]*?\/tpc\.googlesyndication[\s\S]*?\.addEventListener\(["']message["']/, 1]
]);
```

**Comment by jspenguin2017** [comment] 2017-07-15 17:00
It filter some stuff out of Promise.

**Comment by jspenguin2017** [comment] 2017-07-15 17:03
Is that what they use for generic Admiral defuser? Are they confident enough to apply it to all domains?

**Comment by ghajini** [comment] 2017-07-15 17:04
adguard apply for this site
africam.com.....

i don't know other site...will check

**Comment by jspenguin2017** [comment] 2017-07-15 17:07
I mean they are not patching Promise in all domains are they? It probably work but I just go block their payload serving domain. Admiral probably have rather limited funding, let's see how many domains they can register.

**Comment by ghajini** [comment] 2017-07-15 17:08
They haven't committed yet

**Comment by jspenguin2017** [comment] 2017-07-15 17:09
Just block the payload server is much faster, don't have to let Admiral to run and block it later.

**Comment by ghajini** [comment] 2017-07-15 17:19
They have I think generic....
https://github.com/AdguardTeam/AdguardFilters/search?utf8=%E2%9C%93&q=admiral&type=

**Comment by okiehsch** [comment] 2017-07-16 01:43
@jspenguin2017 I think you got the attention of this Cloudflare app. I just updated a uBO-filter fix for
`hackintosh.zone` https://github.com/uBlockOrigin/uAssets/commit/db88bcafe63f9c2942ffc5a46eb9d0ff1e9b5fa1.
The updated fix works with uBO default settings. I never saw that anti-adblock script before, so I looked for 
some information and found this issue.

If I go to `hackintosh.zone`  with uBO + UBProtector without the fix,  this is the result.
![ubprot](https://user-images.githubusercontent.com/16838044/28243813-56574af0-69d8-11e7-902d-e35ebc4c0d9e.JPG)

My CPU goes throgh the roof and I have to close the tab, reloading does not work.
If I add the fix `hackintosh.zone##script:inject(abort-on-property-read.js, CloudflareApps.installs)`
I can use `hackintosh.zone without any problems.

**Comment by jspenguin2017** [comment] 2017-07-16 02:04
OK I guess it didn't took them long...

**Comment by jspenguin2017** [comment] 2017-07-16 02:09
Let me patch this ;)

**Comment by jspenguin2017** [comment] 2017-07-16 02:20
Easy, patched in 15 minutes ;)

**Comment by okiehsch** [comment] 2017-07-16 02:28
Do you know of other websites using this app right now? I would like to take a look.

**Comment by jspenguin2017** [comment] 2017-07-16 02:28
It's on the top of this thread.

**Comment by okiehsch** [comment] 2017-07-16 02:37
Oops missed that somehow, thanks.
Fix works fine.

**Comment by jspenguin2017** [comment] 2017-07-16 02:52
They added a `while (true) { }` to their code, you can use Chrome task manager to terminate the tab.

**Comment by okiehsch** [comment] 2017-07-16 03:00
I used `Ctrl + w`, worked after a few seconds.

**Comment by jspenguin2017** [comment] 2017-07-16 03:45
There are ways to make it robust enough to prevent generic solutions, let's see how long will it take for them to figure it out.

**Comment by uBlock-user** [comment] 2017-07-16 05:26
They insert the script via their DNS servers that's why it's difficult to cut them off like we do with the regular filters.

**Comment by jspenguin2017** [comment] 2017-07-16 14:15
I can have really aggressive code to break theirs, but the problem is I can't apply that to all domains. I think after 2 or 3 weeks they will figure out how to force me to use aggressive code.

**Comment by jspenguin2017** [comment] 2017-07-16 16:23
Did they break their preview?

**Comment by jspenguin2017** [comment] 2017-07-16 17:51
@okiehsch I think `hackintosh.zone` is still changing their website, it may add other Cloudflare apps, need to keep an eye on it.

**Comment by okiehsch** [comment] 2017-07-16 21:37
They are constantly changing their adblock detection https://github.com/uBlockOrigin/uAssets/issues/216,
so I check the site from time to time anyway, but thanks for the heads-up.

**Comment by jspenguin2017** [comment] 2017-07-16 21:47
I'll actually nuke their app this time, instead of playing cat and mouse. 
Generic solution V2 work in progress!

**Comment by jspenguin2017** [comment] 2017-07-16 23:48
Now I actively prevent NoAdBlock from initializing, let's see if this will keep them occupied longer ;)

**Comment by jspenguin2017** [comment] 2017-07-17 14:09
This need a little optimization: 

* Use for...of
* Extract it out and do a check in `rules.js`, block all Cloudflare apps when appropriate to make it non-bypassable
* The observer rule can probably retire

**Comment by jspenguin2017** [comment] 2017-07-17 21:15
I think we are done for this week, I can't wait to see how NoAdBlock devs react to blocked `CloudflareApps.installs` :3

**Comment by jspenguin2017** [comment] 2017-07-18 23:46
I just realized Cloudflare assigns each app an unique ID 😄 This makes it a LOT easier.

**Comment by uBlock-user** [comment] 2017-07-19 10:41
FYI this also works - `clubedohardware.com.br##script:inject(abort-on-property-read.js, CloudflareApps)` and nothing is broken either.

**Comment by jspenguin2017** [comment] 2017-07-19 13:52
Yes, blowing up `CloudflareApps.installs` is the ultimate solution, but that is no-go for generic solution.

**Comment by uBlock-user** [comment] 2017-07-19 15:55
No need to make it generic, the use has just begun, so fixing it on a case by case basis is fine.

**Comment by jspenguin2017** [comment] 2017-07-19 16:07
We still need a way that does not blow up other Cloudflare apps.

**Comment by uBlock-user** [comment] 2017-07-19 17:39
> Cloudflare assigns each app an unique ID

You found a way already, didn't you ? Just find the unique ID of NoAdblock and kill it generically so only that app is affected and while others are not harmed.

**Comment by jspenguin2017** [comment] 2017-07-19 17:48
The problem is Cloudflare sometimes put multiple apps in one file, so I cannot just abort that file... I can find a way to interfere, but they will eventually bypass my solution... And it will end up to be non-generic...

**Comment by jspenguin2017** [comment] 2017-07-20 00:04
They are back, need to disable Mutation Observer rule, as it is not a safe fallback. 
![image](https://user-images.githubusercontent.com/7283682/28394749-7cb8164e-6cac-11e7-8223-931fed622163.png)

**Comment by jspenguin2017** [comment] 2017-07-20 01:19
<details>

```
"{"dismissOptions":{"allowDismiss":"allow","warningFrequency":"visit","warningInterval":1},"warningSettings":{"coverPage":false,"messageTypeFull":"1","messageTypeSmall":"1"},"translations":{"showTranslations":true,"warningTitle":"Welcome","warningText":"Looks like uBlock Protector was not able to defuse NoAdBlock.","refreshButtonText":"Don't click","howToDisableButtonText":"Report it","howToDisableButtonLink":"https://github.com/jspenguin2017/uBlockProtector/issues/362"},"advancedSettings":{"showAdvancedSettings":0,"warningDelay":0}}"
```

</details>

**Comment by jspenguin2017** [comment] 2017-07-20 03:36
Maybe I should just lock their config to be "show up 10 years later" 😂 
Their code is very weak and world writable.

**Comment by okiehsch** [comment] 2017-07-20 18:55
Just fyi we now have people getting blocked because people "use" your extension, even if they really
do not 😄 https://github.com/gorhill/uBlock/issues/2804

**Comment by jspenguin2017** [comment] 2017-07-20 22:37
Maybe I should be swapping a couple solutions around to ensure no downtime, they would have to guess which comment will execute next 😆

**Comment by jspenguin2017** [comment] 2017-07-21 00:44
I now have 4 distinct working solutions that does not break other Cloudflare apps, plus one emergency fallback. 
The reason I'm doing this is that I want to show NoAdBlock devs that I can break their new detection with one switch flip unless they patch all 4 of my solutions.

**Comment by jspenguin2017** [comment] 2017-07-21 03:18
Looks like the app does auto-update, all websites are running 1.4.7 now.

**Comment by jspenguin2017** [comment] 2017-07-21 18:42
They updated again, removed the detection code 😂 
Are they giving up?

**Comment by jspenguin2017** [comment] 2017-07-21 18:48
And they forgot to change `scope.VERSION`...

**Comment by lain566** [comment] 2017-07-31 11:36
They haven't given up
I can reproduce it if I have uBlock Protector Extension enabled
http://www.clubedohardware.com.br/
![clube_do_hardware_-_clube_do_hardware_-_google_chr_2017-07-31_13-23-40](https://user-images.githubusercontent.com/27441315/28775667-870f46e4-75f3-11e7-972b-06dc25b2a000.png)

**Comment by jspenguin2017** [comment] 2017-07-31 14:10
They obfuscated their code...

**Comment by jspenguin2017** [comment] 2017-07-31 14:29
Looks like solution 4 still works, doing a quick solution swap for now.

**Comment by jspenguin2017** [comment] 2017-07-31 15:09
They encrypted their variable names, although the encryption key is hard coded, it is different for every variable, which is actually pretty annoying... 
It also pulls some external scripts, but nukes the webpage once they realized that those scripts are blocked. 

Well done. Well done, that is some high quality changes, unlike the alert + infinite loop from last time.

**Comment by jspenguin2017** [comment] 2017-07-31 16:20
Good enough for now...

**Comment by jspenguin2017** [comment] 2017-07-31 20:13
I think there are a few things left to try.

**Comment by jspenguin2017** [comment] 2017-07-31 21:17
GG again 😄 
Can't wait to see how they responds.

**Comment by uBlock-user** [comment] 2017-08-01 05:32
Can't reproduce with or without the extension as uBlock Filters already patched it via `clubedohardware.com.br,itavisen.no##script:inject(abort-on-property-read.js, CloudflareApps.installs)`

**Comment by uBlock-user** [comment] 2017-08-01 05:33
So let them change whatever they want...

**Comment by jspenguin2017** [comment] 2017-08-01 14:33
Yea but I need a generic solution, I'm pretty sure there are way more than 4 websites using it.

**Closed** 2017-08-01 14:48 UTC
Labels: Fixed

**Comment by shameen** [comment] 2017-08-04 19:28
https://cmacapps.com/
http://who-called.co.uk/

back again?

**Comment by jspenguin2017** [comment] 2017-08-04 19:29
Did you update Extension? 
![image](https://user-images.githubusercontent.com/7283682/28983920-f7e7bef0-7918-11e7-880d-917ab9d8aa98.png)
![image](https://user-images.githubusercontent.com/7283682/28983928-fce1a88a-7918-11e7-8772-2fde1d7e4e48.png)

**Comment by shameen** [comment] 2017-08-07 11:59
Ah my mistake, was only updating the filter list
