### ISSUE TITLE
egy.best

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [jspenguin2017/uBlockProtector#1096] opened 2019-12-15 13:31 UTC
### Test link (required):
https://beta.egybest.cheap/episode/breaking-bad-season-5-ep-13/#download

### Screenshot of the web page (including address bar and extension icons) (required):
![Screenshot_257](https://user-images.githubusercontent.com/19984935/70863242-9111e280-1f4e-11ea-9cfe-e6a399223d12.jpg)

### Screenshot of the console (press `F12` to bring up the console) (required):
![Screenshot_258](https://user-images.githubusercontent.com/19984935/70863257-b4d52880-1f4e-11ea-9cf0-3499633f3bdc.jpg)

### Reproduction steps (optional if trivial):
Open the page, try to play the video.

### Environment (Required):

- Operating System and Version: Windows 10 1909
- Browser and Version: Google Chrome Version 79.0.3945.79 (Official Build) (64-bit)
- Adblocker and Version: uBlock Origin v1.23.0

#### Your filter lists (Required):
![Screenshot_259](https://user-images.githubusercontent.com/19984935/70863327-a6d3d780-1f4f-11ea-8dff-e42e2c59a873.jpg)

#### Your custom filters (Required if you have any):
Applied to different domains. Irrelevant.

**Comment by jspenguin2017** [comment] 2019-12-15 17:16
Duplicate of https://github.com/NanoAdblocker/NanoFilters/issues/376

**Closed by jspenguin2017** 2019-12-15 17:16 UTC
Labels: Duplicate
