### ISSUE TITLE
crackleplus.com

### ISSUE THREAD

**Issue by DBZsuper** [jspenguin2017/uBlockProtector#986] opened 2018-08-31 11:46 UTC
hi,
I am facing a problem whenever I click on the video. A pop-ad appears every time. I am using adblocker and google chrome browser.

affected links:
text link1: https://crackleplus.com/
text link2: https://crackleplus.com/tv-series/dragon-ball-z-english-dubbed/

the main page sometimes doesn't show any problem.

**Comment by mapx-** [comment] 2018-08-31 12:31
adblocker ? I hope ublock origin, right ?

**Comment by DBZsuper** [comment] 2018-08-31 12:57
yeah.. it is.. how you know that..

**Comment by jspenguin2017** [comment] 2018-08-31 13:16
Cannot reproduce. Closing as invalid since you have not filled the template.

**Closed by jspenguin2017** 2018-08-31 13:16 UTC
Labels: Invalid
