### ISSUE TITLE
mediafire.com

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#992] opened 2018-09-27 07:08 UTC
### Test link (required):
`http://www.mediafire.com/file/yi23ro4ggrqc5z3/CCNP+Routing+By+Ahmostafa.rar`

### Screenshot of the web page (including address bar and extension icons) (required):
![2018-09-27_090014](https://user-images.githubusercontent.com/2828165/46128608-554d0900-c234-11e8-86ba-9993f4d535f7.png)

### Screenshot of the console (press `F12` to bring up the console) (required):
![2018-09-27_090115](https://user-images.githubusercontent.com/2828165/46128615-5f6f0780-c234-11e8-83ba-7d63244c1786.png)

**Environment (Required):**
Operating System and Version: WIN 7 SP1 64BIT
Browser and Version: Chrome Version 69.0.3497.100 (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.69+Nano Defender 15.0.0.46

**Your filter lists (Required):**
My filters​​​​​
Nano Defender Integration​​​
Nano filters​
Nano filters – Timer bypassing (sometimes works)​
Nano filters – Whitelist​​​​​
uBlock filters​
uBlock filters – Badware risks
uBlock filters – Privacy​​​​​
uBlock filters – Resource abuse
uBlock filters – Unbreak
**Ads (2)**
Adblock Warning Removal List​
EasyList
**Privacy (1)**
EasyPrivacy​
Malware Domain List​​​​​
Malware domains​
Peter Lowe’s Ad and tracking server list
**Regions, languages (4)**
ARA: Liste AR
IRN: Adblock-Iran​
RUS: Adguard Russian Filter​
RUS: RU AdList​

Your custom filters (Required if you have any):
https://zerodot1.gitlab.io/CoinBlockerLists/list.txt

**Comment by mapx-** [comment] 2018-09-27 07:30
fixed in `uBlock filters – Annoyances`

**Comment by jspenguin2017** [comment] 2018-09-27 23:16
Fix doesn't work.

**Comment by jspenguin2017** [comment] 2018-09-27 23:21
@okiehsch 
![image](https://user-images.githubusercontent.com/7283682/46179710-b5b26980-c279-11e8-9946-865044951f0c.png)
![image](https://user-images.githubusercontent.com/7283682/46179713-bc40e100-c279-11e8-964e-35d3e4f594a7.png)

**Comment by okiehsch** [comment] 2018-09-27 23:48
I can't reproduce any anti-adblock message.
Here is the site after I disabled the added filter and used a canadian IP.
![image](https://user-images.githubusercontent.com/16838044/46180388-6fccc400-c2c0-11e8-91af-6fb96aa073e6.png)

**Comment by jspenguin2017** [comment] 2018-09-28 02:03
`mediafire.com##+js(abort-current-inline-script.js, document.getElementById, adblocker)` works for me.

**Comment by jspenguin2017** [comment] 2018-09-28 03:08
That's weird, I see it: 
![image](https://user-images.githubusercontent.com/7283682/46185953-74ca4d00-c299-11e8-9e1c-7b42c067a24a.png)

**Comment by okiehsch** [comment] 2018-09-28 03:12
Well, I will add your filter, can't hurt, but I will not remove the one **mapx-** added, maybe he gets served something different altogether.

Is it an annoyance on your end?

**Comment by jspenguin2017** [comment] 2018-09-28 12:27
Yea, it's annoyance.

**Comment by okiehsch** [comment] 2018-09-28 17:12
Added.

**Closed** 2018-09-28 23:28 UTC
Labels: Fixed
