### ISSUE TITLE
Ublock protector blocking twitch playback .

### ISSUE THREAD

**Issue by ariefpizzuti** [jspenguin2017/uBlockProtector#351] opened 2017-07-07 20:53 UTC
Test link :
https://www.twitch.tv/matumbaman
Screenshot of the web page :
![untitled](https://user-images.githubusercontent.com/18688192/27976310-7766da6c-6398-11e7-84ca-432edd184921.jpg)
Screenshot of the console :
![dduntitled](https://user-images.githubusercontent.com/18688192/27976370-c8125e6e-6398-11e7-91c8-104c4c65ba9c.jpg)

Somehow disabling ublock protector extension ,the twitch playback is back to normal .ublock origin are on default setting .reinstalling both extension or restarting chrome didn't help .

**Comment by uBlock-user** [comment] 2017-07-07 20:56
Can't reproduce.

**Comment by uBlock-user** [comment] 2017-07-07 20:57
Plays fine.

![](https://i.gyazo.com/dfc0b7d10f69f07d10a17bb205568bb3.png)

**Comment by ariefpizzuti** [comment] 2017-07-07 20:58
I guess its on my end .thank you .

**Comment by adreporter** [comment] 2017-07-07 21:01
@ariefpizzuti It's not only you. I'm having the same problem.

**Comment by uBlock-user** [comment] 2017-07-07 21:06
Don't close the issue just like that, let others investigate.

**Comment by ariefpizzuti** [comment] 2017-07-07 21:07
Im trying to resolve it now by restarting my router and modem .restarting pc now .maybe it'll help .

**Comment by ariefpizzuti** [comment] 2017-07-07 21:07
Sorry @uBlock-user

**Comment by jspenguin2017** [comment] 2017-07-07 21:08
Works fine for me: 
![image](https://user-images.githubusercontent.com/7283682/27977005-15f78172-6326-11e7-8c48-b48326ab5262.png)

**Comment by ariefpizzuti** [comment] 2017-07-07 21:17
Restarting pc,modem,router didnt solve the issue .it was fine before I go out 5-6 pm-ish SGT .got back home 2.30am .

**Comment by matbech** [comment] 2017-07-07 21:23
Same problem here.

**Comment by lain566** [comment] 2017-07-07 21:24
me too, same problem

**Comment by uBlock-user** [comment] 2017-07-07 21:24
This sounds more like a filter list issue to me, force update all your active filterlists, remove cache and site data and then refresh the page again.

**Comment by matbech** [comment] 2017-07-07 21:25
@uBlock-user I don't think so. All filter lists have been refreshed. Maybe it's a geo issue.

**Comment by adreporter** [comment] 2017-07-07 21:26
@uBlock-user Already did that, but unfortunately it doesn't work.

**Comment by uBlock-user** [comment] 2017-07-07 21:28
You wouldn't get a black screen if it was a Geo-Lock, that's not it. You would rather receive a notification based on your IP address.

**Comment by lain566** [comment] 2017-07-07 21:29
Only works for me if i disable ublock protector extension

**Comment by adreporter** [comment] 2017-07-07 21:29
@lain566 Same here.

**Comment by Bpsmooth** [comment] 2017-07-07 21:30
Same problem for me as well.

**Comment by uBlock-user** [comment] 2017-07-07 21:32
Browser does makes a network request to `imasdk.googleapis.com`

**Comment by uBlock-user** [comment] 2017-07-07 21:34
Try this filter -  `@@||imasdk.googleapis.com^$domain=twitch.tv`

It's from `uBlock Filters - Unbreak`

**Comment by jspenguin2017** [comment] 2017-07-07 21:35
That won't do anything, the loopback seems to be broken.

**Comment by jspenguin2017** [comment] 2017-07-07 21:35
Try updating the Extension to 10.36.

**Comment by uBlock-user** [comment] 2017-07-07 21:35
Then how come it was playing for us ?

**Comment by ariefpizzuti** [comment] 2017-07-07 21:36
Updating the extension solve the issue .thank you

**Comment by matbech** [comment] 2017-07-07 21:36
@jspenguin2017 works with 10.36. Thanks.

**Comment by adreporter** [comment] 2017-07-07 21:37
@jspenguin2017 Yes, now it works. Thank you as always.

**Comment by Bpsmooth** [comment] 2017-07-07 21:38
@jspenguin2017 10.36 solved my issue. Thank you sir!

**Comment by lain566** [comment] 2017-07-07 21:38
@jspenguin2017 Now it works fine

**Closed** 2017-07-07 21:43 UTC
Labels: Fixed
