### ISSUE TITLE
cmacapps.com

### ISSUE THREAD

**Issue by Elkrite** [jspenguin2017/uBlockProtector#377] opened 2017-07-11 10:50 UTC
### Test link (required): 

https://cmacapps.com/category/entertainment/

### Screenshot of the web page (required): 

<img width="1439" alt="g3nsewhgsfydyyj8mezdxa" src="https://user-images.githubusercontent.com/15133609/28064988-bbd1b00a-6604-11e7-84f4-7d2b194a26f2.png">

### Screenshot of the console (press `F12` to bring up the console) (required): 

<img width="960" alt="xmuizbsxrvgffnayawi7sg" src="https://user-images.githubusercontent.com/15133609/28065034-e7082d6c-6604-11e7-806c-f1681f8fc695.png">

### Add everything else that you believe to be useful below (optional): 

Occurs on both Mac and Windows. May take a few seconds for the pop up to kick in.

**Comment by uBlock-user** [comment] 2017-07-11 12:45
Can't reproduce.

**Comment by jspenguin2017** [comment] 2017-07-12 15:25
Still works. Closing.

**Closed by jspenguin2017** 2017-07-12 15:25 UTC
Labels: Fixed
