### ISSUE TITLE
cyberterminators.co

### ISSUE THREAD

**Issue by ColliderTD** [jspenguin2017/uBlockProtector#287] opened 2017-06-11 15:19 UTC

**Comment by uBlock-user** [comment] 2017-06-11 19:04
I was going to suggest killing the setTimeout call, but looks like you already patched the `anOptions` property.

**Comment by ColliderTD** [comment] 2017-06-12 00:24
Still....

**Comment by adreporter** [comment] 2017-06-12 00:41
@ColliderTD Can't reproduce, make sure you're using the latest version of the list and of the script.

**Comment by uBlock-user** [comment] 2017-06-12 11:11
That's because it got patched by jspenguin before you posted.

**Comment by adreporter** [comment] 2017-06-12 11:20
@uBlock-user ikr

**Comment by ColliderTD** [comment] 2017-06-12 19:41
:D (y)

**Comment by jspenguin2017** [comment] 2017-06-12 20:52
It's patched in https://github.com/jspenguin2017/uBlockProtector/commit/8f66e2773b0aa68bfc6c60d7b2cd5aaabed21cd5

**Comment by jspenguin2017** [comment] 2017-06-17 16:16
Still works. Closing.

**Closed by jspenguin2017** 2017-06-17 16:16 UTC
Labels: Fixed
