### ISSUE TITLE
gsmarena.com

### ISSUE THREAD

**Issue by Acters** [jspenguin2017/uBlockProtector#346] opened 2017-07-04 08:39 UTC
### Screenshot of the web page (required): 

screenshot of me manually blocking www.adiode.com: http://i.imgur.com/QxIL01d.png
screenshot of me accessing the site: http://i.imgur.com/c7hAQiB.png (your extension is hidden)

### Screenshot of the console (press `F12` to bring up the console) (required): 

http://i.imgur.com/5J2gH42.png

### Add everything else that you believe to be useful below (optional): 
I am providing this issue as a statement as there seems to be a new player that comes forth to the anti-adblocking "community". I am unable to find a social media outlet to alert you by.

I found this domain as I regularly visit gsmarena's website. In the past I was able to access the website perfectly fine, however the UMatrix recently caught www.adiode.com in the filter. I understand this is not done by uBlockProtector. I am alerting you to show that there is another domain created to prevent adblock users from accessing the site. However the attempt was poorly done and may be updated to truly catch adblock users. I am concerned and unsure of the implications, since I am limited in knowledge.

Thank you,
Acters

**Comment by Acters** [comment] 2017-07-04 08:50
ok so it seems that allowing it through now allows me on the site but at random times(sometimes doesn't) presents me with an ad.

Screenshot of site: http://i.imgur.com/LLlU4HY.png
screenshot of console: http://i.imgur.com/TzkVSuH.png

I guess I should alert the ublock filter maintainers, but it is 2 am, I'm sleepy.  If I do not see you alert them then I'll post an issue. I will rather sleep than put minimal brain power on a post. this post took me an hour to write. good night.

**Comment by uBlock-user** [comment] 2017-07-04 11:43
Can't reproduce.

**Comment by uBlock-user** [comment] 2017-07-04 11:55
Running 3 evals.

One tries to establish WebRTC connection, and then send logs to a tracking domain, another loads anti adblock notice.

**Comment by uBlock-user** [comment] 2017-07-04 11:55
Filter - `gsmarena.com##script:inject(noeval.js)`

**Comment by uBlock-user** [comment] 2017-07-04 12:03
Alternatively if you don't wish to kill `eval`, you can use - `gsmarena.com##script:inject(abort-on-property-read.js, adonis)`

**Comment by jspenguin2017** [comment] 2017-07-04 14:47
Yep, just block `eval`.

**Comment by Acters** [comment] 2017-07-04 21:23
I see I left a confusing late night post. Thank you for fixing up the title and the fix. Happy 4th of July!

**Comment by jspenguin2017** [comment] 2017-07-07 14:45
Still works. Closing.

**Closed by jspenguin2017** 2017-07-07 14:45 UTC
Labels: Fixed
