### ISSUE TITLE
sport365.live

### ISSUE THREAD

**Issue by k3lt** [jspenguin2017/uBlockProtector#345] opened 2017-07-03 16:11 UTC
### Screenshot of the web page: 
![1](https://user-images.githubusercontent.com/22222328/27800905-b6b39230-601b-11e7-95ec-fe2d9c8052dd.png)

### Screenshot of the console: 
![2](https://user-images.githubusercontent.com/22222328/27800908-bb9562ce-601b-11e7-97a3-c61d9896581b.png)

After about 30 seconds of opening stream warning message that adblock has been detected shows up.

**Comment by uBlock-user** [comment] 2017-07-03 16:40
Lots of `evals` running.

**Comment by uBlock-user** [comment] 2017-07-03 16:43
`sport365.live###popup-wrapper`

That kills the notice.

**Comment by jspenguin2017** [comment] 2017-07-03 16:49
Yea, but that looks like a generic wrapper, I'm not sure if it is used elsewhere, I'll go with a scripted approach.

**Comment by k3lt** [comment] 2017-07-03 16:49
Im supposed to put this under "My Filters" in uBlock Origin settings? If so it doesn't work.

**Comment by jspenguin2017** [comment] 2017-07-03 16:51
No, I fixed it with another way.

**Comment by uBlock-user** [comment] 2017-07-03 16:51
You will need to whitelist `adshell.net ` if blocked.

**Comment by jspenguin2017** [comment] 2017-07-03 16:51
https://github.com/jspenguin2017/uBlockProtector/commit/7780888331f83ab0cd5c11305ba7b79c2b193a9f#diff-699ddf519061db77234838947da4ce77R2599

**Comment by uBlock-user** [comment] 2017-07-03 16:53
Not for the anti-adblock, but the video won't play if adshell.net is blocked. It deliver videos with integrated ads and popups.

**Comment by uBlock-user** [comment] 2017-07-03 16:57
It supplies inline-script and frame for the player and the video and then popups

**Comment by jspenguin2017** [comment] 2017-07-03 16:58
I see that videos don't always play...

**Comment by uBlock-user** [comment] 2017-07-03 16:59
whitelist adshell.net and you will be greeted with numeorus popups and then they will play

**Comment by jspenguin2017** [comment] 2017-07-03 17:00
That's not good.

**Comment by uBlock-user** [comment] 2017-07-03 17:06
Can you replace the player ? A 3rd party CDN mixing itself with original content and ads and stuff is their way of forcing you to whitelist them. They host the video and the player itself, so you have to whitelist them.

**Comment by jspenguin2017** [comment] 2017-07-03 17:07
If the ads are baked into the stream then there is nothing I can do, but that seems to be not the case. I need the VJS payload like last time, super sticky.

**Comment by uBlock-user** [comment] 2017-07-03 17:11
I tried to investigate further but those damn popups made me quit, I can't deal with 3rd party popups coming out nowhere and trying to stop all of them at the same time.

**Comment by jspenguin2017** [comment] 2017-07-03 17:43
Video sites are always so painful...

**Comment by uBlock-user** [comment] 2017-07-03 17:52
This one is different, video sites usually never hijack the player itself like this..

**Comment by jspenguin2017** [comment] 2017-07-03 20:55
http://www.castasap.pw/embed/9d5f296503f053c8291c80647c4b2f0d0e51a54c31fc3897b6fcfb3e3f77c145/1499115122/595a0d55d2bea058015816/er7l1cf10e8fptg8tvscepm951/595aaf12a2d3f/595aaf12d3bf7/768/432

**Comment by jspenguin2017** [comment] 2017-07-03 23:29
This is a sticky one, the website keeps changing, the streams sometimes work, sometimes don't.

**Comment by jspenguin2017** [comment] 2017-07-04 00:07
So these are the embeds that misbehave: 
`fastflash.pw`, `castasap.pw`

**Comment by jspenguin2017** [comment] 2017-07-04 14:21
`fastflash.pw` works now, I think it's just because some sources goes down from time to time, they give you 6 sources for a reason. I guess this is good.

**Comment by uBlock-user** [comment] 2017-07-04 16:15
and how did you fix ? I don't see the commit.

**Comment by jspenguin2017** [comment] 2017-07-04 16:19
I don't think there is anything to fix, some sources goes down from time to time.

**Comment by k3lt** [comment] 2017-07-04 16:28
So its not possible to watch it without ads?

**Comment by jspenguin2017** [comment] 2017-07-04 16:29
What? I don't see any ads.

**Comment by k3lt** [comment] 2017-07-04 16:31
With uBlock Origin there are not, but the video stop working when it's enabled.. When i watch it without uBlock it shows bunch of ads but the video doesnt stop.

**Comment by jspenguin2017** [comment] 2017-07-04 16:32
Can't reproduce: 
![image](https://user-images.githubusercontent.com/7283682/27837850-0be71aa0-60a4-11e7-9906-3f0b5fcade40.png)

**Comment by k3lt** [comment] 2017-07-04 16:33
It doesnt stop after like a minute for you with uBlock enabled?

**Comment by jspenguin2017** [comment] 2017-07-04 16:50
Eh... life is hard

**Comment by jspenguin2017** [comment] 2017-07-04 17:22
Does this work? 
`||adshell.net/f/$subdocument,domain=www.sport365.live,redirect=noopframe`

**Comment by k3lt** [comment] 2017-07-04 17:26
Video stops after like 90seconds. :(

**Comment by jspenguin2017** [comment] 2017-07-04 17:32
![image](https://user-images.githubusercontent.com/7283682/27839169-71bb5230-60ac-11e7-989d-c4d1c731bbbc.png)
![image](https://user-images.githubusercontent.com/7283682/27839173-7e96a018-60ac-11e7-849e-579d67182e12.png)

**Comment by jspenguin2017** [comment] 2017-07-04 17:46
Are you sure it works properly with uBO off? It doesn't work whitelisted or not. 
![image](https://user-images.githubusercontent.com/7283682/27839435-6476b1c6-60ae-11e7-9ca7-1f96c54ec9df.png)

**Comment by k3lt** [comment] 2017-07-04 17:49
To be honest instead of turning it all off i tested it with other browsers that has no adblock installed, like Edge plays it fine.. but now u asked for it and yeah it still stops on Chrome with uBlock disabled, weird..

**Comment by uBlock-user** [comment] 2017-07-04 18:26
Chrome issue perhaps...?

**Comment by k3lt** [comment] 2017-07-04 18:27
I have no idea i think i'll give up at this point and just look for some alternative.

**Comment by jspenguin2017** [comment] 2017-07-04 18:38
Yea, it is not an issue with ad blocking, the message from the home page is patched, marking as fixed for now.

**Comment by lain566** [comment] 2017-07-04 19:38
@jspenguin2017 This might be the source of the problem
http://s1.medianetworkinternational.com/js/advertisement.js

the whitelist works for me
`@@||medianetworkinternational.com/js/advertisement.js$script,domain=sport365.live`

**Comment by jspenguin2017** [comment] 2017-07-04 19:42
That code boils down to one line: `jQuery.adblock=false;`...

**Comment by jspenguin2017** [comment] 2017-07-04 19:46
Put it in loopback server, going to test once things are synced.

**Comment by jspenguin2017** [comment] 2017-07-04 19:51
Ops, need to have wildcard.

**Comment by jspenguin2017** [comment] 2017-07-04 19:53
Nope, nooping that file doesn't help, in fact, turning off uBO entirely doesn't help neither. 
![image](https://user-images.githubusercontent.com/7283682/27841604-29463786-60c0-11e7-81ec-264360d19100.png)

**Comment by lain566** [comment] 2017-07-04 19:54
It seems to be working

**Comment by jspenguin2017** [comment] 2017-07-04 19:56
It works for a minute or two, then the server starts throwing 406.

**Comment by k3lt** [comment] 2017-07-04 19:56
Yup same for me, works for about 2 minutes and then the video hangs up.

**Comment by k3lt** [comment] 2017-07-05 11:31
Can you maybe leave it open so maybe someone figure out how to stop the 406 errors?

**Comment by jspenguin2017** [comment] 2017-07-05 13:48
I can leave it open for a while, yea.

**Comment by lain566** [comment] 2017-07-05 14:02
@jspenguin2017 Can you try this?
`@@|http://tags2.adshell.net/p/44/1-0-60,2-0-90,3-0-90`

**Comment by jspenguin2017** [comment] 2017-07-05 14:23
@lain566 It doesn't work with uBO off, how can adding a few whitelists help?

**Comment by k3lt** [comment] 2017-07-05 15:12
So out of curiosity i just tested it on Internet Explorer, played the video for about 20 minutes and it didnt hang, there have been some ads though

**Comment by lain566** [comment] 2017-07-05 15:13
@jspenguin2017 I want to know the source of the problem, nothing more.
Do you know why video stops?


whitelist, just in case, I doubt this will help
```
@@||tags2.adshell.net/*/*/*?el=d&req=*
@@|http://tags2.adshell.net/p/51/1-0-5,2-0-5
@@|http://tags2.adshell.net/p/80/1-0-1,2-0-1
@@|http://tags2.adshell.net/p/55/1-0-1,2-0-1,3-5-5
@@|http://tags2.adshell.net/p/46/1-0-5,2-0-5
@@|http://tags2.adshell.net/p/79/1-0-60,2-0-90
@@|http://tags2.adshell.net/p/44/1-0-60,2-0-90,3-0-90
```

**Comment by jspenguin2017** [comment] 2017-07-05 15:16
Yep, their server is broken.

**Comment by uBlock-user** [comment] 2017-07-05 17:15
There's nothing you can do about it if the issue lies on their end.

**Comment by k3lt** [comment] 2017-07-05 17:16
How it doesn't get stuck on IE though?

**Comment by jspenguin2017** [comment] 2017-07-05 17:50
Try spoof the user agent?

**Comment by k3lt** [comment] 2017-07-05 17:56
Just tried but still hangs with UA Spoofer.

**Comment by uBlock-user** [comment] 2017-07-05 18:26
Perhaps it deals with IE differently than it does with Chrome. You're better off finding an alternative.

**Comment by uBlock-user** [comment] 2017-07-05 18:28
406 error - http://www.inmotionhosting.com/support/website/error-numbers/406-error

Apparently Mod_security protection on the server's end is causing this.

**Comment by jspenguin2017** [comment] 2017-07-05 18:45
I don't think the request has anything that would be caught in that Apache mod.

**Comment by uBlock-user** [comment] 2017-07-05 20:08
Either way, the issue doesn't lie on our end.

**Comment by jspenguin2017** [comment] 2017-07-12 15:22
It's been a week... I'm closing this.

**Closed by jspenguin2017** 2017-07-12 15:22 UTC
Labels: Fixed
