### ISSUE TITLE
uol.com.br

### ISSUE THREAD

**Issue by ialexsilva** [jspenguin2017/uBlockProtector#234] opened 2017-05-24 14:26 UTC
Before opening an issue, you MUST read the contribution guideline. Failure to do so may result in a ban. 

### About this website

Test link: https://www.uol.com.br/

Screenshot: 
![capturar](https://cloud.githubusercontent.com/assets/6363160/26408273/b0d81790-4073-11e7-901d-e501bec8b4c0.PNG)

### Setup

Browser: Google Chrome Version 58.0.3029.110 (64-bit)

AdBlocker: uBlock origin

Script Host: 

### Others

Add everything else that you believe to be useful below:

**Comment by jspenguin2017** [comment] 2017-05-24 16:20
Can't reproduce. Marking as bad installation as you have not specified the script host that you are using.
![image](https://cloud.githubusercontent.com/assets/7283682/26413877/9defd4d2-406a-11e7-9dc1-a2cc96a359bc.png)

**Comment by uBlock-user** [comment] 2017-05-24 17:51
I can reproduce.

Filter - `||uol.com.br/camaleao/assets/web/javascript/detectadblock^$script,important`

**Comment by jspenguin2017** [comment] 2017-05-24 20:19
I guess it has a counter somewhere... I was able to reproduce it too... Added the rule to List.

**Closed** 2017-05-29 01:40 UTC
Labels: Fixed
