### ISSUE TITLE
gamersclub.com.br

### ISSUE THREAD

**Issue by xitero** [jspenguin2017/uBlockProtector#258] opened 2017-06-02 03:25 UTC
Test link: https://gamersclub.com.br/

Screenshot: http://i.imgur.com/Im1peHS.png

Add everything else that you believe to be useful below: 
To open any page of this site you need to disable uBlock Origin.

**Comment by jspenguin2017** [comment] 2017-06-02 03:31
Hum... I guess we can white list `https://gamersclub.com.br/js/ads.js`. 
It has some random strings, a hard coded solution probably won't last.

**Comment by uBlock-user** [comment] 2017-06-02 04:04
Can't reproduce.

**Comment by uBlock-user** [comment] 2017-06-02 04:11
Blocking the inline-script doesn't seem to break anything.

**Comment by jspenguin2017** [comment] 2017-06-02 04:16
@uBlock-user 👍 I'll test it out tomorrow. Thanks.

**Comment by jspenguin2017** [comment] 2017-06-02 15:50
I think blocking inline-script will cause some problem... 
![image](https://cloud.githubusercontent.com/assets/7283682/26733695/d996f4ba-4778-11e7-9ad0-74f739579c25.png)

**Comment by jspenguin2017** [comment] 2017-06-02 15:52
This no longer works with `$inline-script`... I guess another white list... 
![image](https://cloud.githubusercontent.com/assets/7283682/26733742/015df872-4779-11e7-936f-ca72f801903d.png)

**Comment by jspenguin2017** [comment] 2017-06-07 17:30
Looks like it's still working. Closing.

**Closed by jspenguin2017** 2017-06-07 17:30 UTC
Labels: Fixed
