### ISSUE TITLE
9anime.to

### ISSUE THREAD

**Issue by MistieKitteh** [jspenguin2017/uBlockProtector#724] opened 2017-11-23 04:55 UTC
### Test link (required): 
https://9anime.is/watch/boku-dake-ga-inai-machi.kkw/z872pw

### Screenshot of the web page (including address bar and extension icons) (required): 

initial video load running fine
![image](https://user-images.githubusercontent.com/27728278/33159314-0f0ae654-cfcf-11e7-84ef-9f3220a107da.png)

Adblock Killer
![image](https://user-images.githubusercontent.com/27728278/33159311-00719b4c-cfcf-11e7-9188-3e256cea758a.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 

Video loaded with white box (Adblock killer presented before video started playing)
![image](https://user-images.githubusercontent.com/27728278/33159322-20d77622-cfcf-11e7-9074-b9eff3d5c618.png)
Adblock killer presented on second video, video may or may not play in background (audio only)
![image](https://user-images.githubusercontent.com/27728278/33159326-2bd17672-cfcf-11e7-88db-7379fb21d63e.png)

### Explain what was not right (optional if obvious): 
Video player initially loads to show an adblock killer but plays initial video fine. White box appears over video when first loaded. Attempting to switch videos bring an adblock killer.

### Reproduction steps (optional if trivial): 
Load page (Will display an adblock killer but video will play regardless with a white empty ad box on video)
Press N or click onto the next episode
An adblock killer is presented and video does not load, or if it does you can only hear audio.

### Add everything else that you believe to be useful below (optional): 
Yes its broken again, bloody annoying. Maybe time to look for a new anime site

**Comment by jspenguin2017** [comment] 2017-11-23 15:14
Duplicate of #723

**Closed by jspenguin2017** 2017-11-23 15:14 UTC
Labels: Duplicate

**Comment by uBlock-user** [comment] 2017-12-14 20:11
@jspenguin2017 I would appreciate if you would just say NO, if you don't want to help me out with issues I post, and avoid locking the thread if you have no interest in taking part of the issue. This has happened for the third time in the recent days, that's why I'm posting here. I know how to take NO for an answer.

**Comment by jspenguin2017** [comment] 2017-12-14 20:16
There are more ways people say no, I told you I can't reproduce popunder, which means either you have more useful information about how to reproduce it or you are on your own to investigate.

**Comment by uBlock-user** [comment] 2017-12-14 20:17
Locking the thread is not the way to say no, that's rude specifically for a person who is not spamming or harassing you in any way. Just say NO once and I will move on.

**Comment by jspenguin2017** [comment] 2017-12-14 20:20
I lock issue when it's getting off topic. I'm not interested in issues that your specific setup introduces. I think you should have realized that by now.

**Comment by uBlock-user** [comment] 2017-12-14 20:23
You could have let me know that in few words. Still there's no need to lock it.  Also my specific setup only blocks third party requests which comes from random domains, but fine. I understand if you're not willing.

**Comment by uBlock-user** [comment] 2017-12-14 20:25
FYI the case is same as https://github.com/jspenguin2017/uBlockProtector/issues/608, but with a modified script, take if you will.

**Comment by jspenguin2017** [comment] 2017-12-14 20:31
I'm more interested in making Nano now.

**Comment by uBlock-user** [comment] 2017-12-14 20:33
See, should have told that before locking.
