### ISSUE TITLE
macupload.net

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#386] opened 2017-07-12 06:05 UTC
macupload.net

### Test link (required): 
https://macupload.net/3ws

### Screenshot of the web page (required): 
http://i.imgur.com/geN7fDt.png

-->

### Screenshot of the console  (required): 
http://i.imgur.com/xguj445.png

**Comment by uBlock-user** [comment] 2017-07-12 06:24
Can't reproduce.

**Comment by uBlock-user** [comment] 2017-07-12 06:24
Try `@@||macupload.net^$elemhide`

**Comment by jspenguin2017** [comment] 2017-07-12 14:57
timeout enforced on server side, can't reproduce anti-adblock.

**Comment by Dibbyo456** [comment] 2017-07-14 03:38
Can't reproduce either.

**Comment by jspenguin2017** [comment] 2017-07-16 20:44
Still works. Closing.

**Closed by jspenguin2017** 2017-07-16 20:44 UTC
Labels: Cannot Reproduce
