### ISSUE TITLE
ftuapps.dev

### ISSUE THREAD

**Issue by NghiaSE** [jspenguin2017/uBlockProtector#1120] opened 2020-07-13 10:28 UTC
### Test link (required):

https://ftuapps.dev/

### Screenshot of the web page (including address bar and extension icons) (required):

https://imgur.com/a/uzdKim9

### Explain what was not right (optional if obvious):
I use both Nano Defender Pro + Nano Adblocker but the website https://ftuapps.dev/ still detects I am using an adblock

### Reproduction steps (optional if trivial):
Open browser Edge
Go to https://ftuapps.dev/
The Warning appears

### Environment (Required):

- Operating System and Version: 
- Browser and Version: 
- Adblocker and Version: 
- Nano Defender Version: 
Windows 10
Edge Version 83.0.478.58 (Official build) (64-bit) Restart This browser is made possible by the Chromium
Nano Adblocker 1.0.0.150
Nano Defender Pro 15.0.0.201

#### Your filter lists (Required):

Nano Defender Integration 2,576 used out of 2,627
Nano filters 397 used out of 400
Nano filters – Whitelist 0 used out of 0
uBlock filters 23,396 used out of 23,499
uBlock filters – Badware risks 852 used out of 860
uBlock filters – Privacy 196 used out of 207
uBlock filters – Resource abuse 117 used out of 117
uBlock filters – Unbreak 1,450 used out of 1,462
Adblock Warning Removal 753 used out of 759
EasyList 83,921 used out of 84,047
EasyPrivacy 17,872 used out of 17,931
Online Malicious URL Blocklist 5,592 used out of 5,596
AdGuard Annoyances 29,454 used out of 29,681
AdGuard Social Media 10,388 used out of 11,059
Peter Lowe's Ad and tracking server list 3,375 used out of 3,482
Regions, languages (1/34)
VIE: ABPVN List 1,475 used out of 1,497
Malware Domain List 1,104 used out of 1,104
Malware domains 26,838 used out of 26,853

**Comment by mapx-** [comment] 2020-07-13 10:53
update uBO filters list

**Comment by jspenguin2017** [comment] 2020-07-13 14:48
Duplicate of https://github.com/NanoMeow/QuickReports/issues/4303

**Closed by jspenguin2017** 2020-07-13 14:48 UTC
