### ISSUE TITLE
l2s.io

### ISSUE THREAD

**Issue by adreporter** [jspenguin2017/uBlockProtector#355] opened 2017-07-08 10:14 UTC
@jspenguin2017 Unfortunately it doesn't work anymore
Updated info:
http://l2s.io/5rCcZ
<img width="306" alt="asas" src="https://user-images.githubusercontent.com/18214146/28378340-1f7756d0-6cb0-11e7-8b52-66324f42a7d7.PNG">
<img width="562" alt="cattura" src="https://user-images.githubusercontent.com/18214146/28378348-259b8dba-6cb0-11e7-8fd6-008ca763930e.PNG">

**Comment by Dibbyo456** [comment] 2017-07-08 11:38
Similar to #339

**Comment by uBlock-user** [comment] 2017-07-08 12:25
```
@@||l2s.io^$elemhide
l2s.io##.banner-captcha.banner
```

**Comment by uBlock-user** [comment] 2017-07-08 12:27
Upon solving the captcha successfully, a 5 sec timer appears.

**Comment by jspenguin2017** [comment] 2017-07-08 15:57
Fixed.

**Comment by adreporter** [comment] 2017-07-08 16:35
@jspenguin2017 Thanks for the fix.
There is a (related?) website that doesn't show the captcha and you won't see the destination page because after clicking the button "Click here to continue", the website says "The CAPTCHA was incorrect. Try again".

Test link: http://u2s.io/oaSc

Screenshot of the webpage after clicking the button:
<img width="655" alt="cattura" src="https://user-images.githubusercontent.com/18214146/27987320-10912e18-640c-11e7-9875-10d45df56b04.PNG">

Screenshot of the console:
<img width="536" alt="before" src="https://user-images.githubusercontent.com/18214146/27987322-1a2d3f0c-640c-11e7-8041-67ba26a1ebb9.PNG">

**Comment by jspenguin2017** [comment] 2017-07-08 16:50
![image](https://user-images.githubusercontent.com/7283682/27987461-47a8737a-63cb-11e7-8f24-f2b86c36e366.png)
Can't reproduce...

**Comment by Dibbyo456** [comment] 2017-07-08 16:54
@adreporter Sometimes Solvemedia Captcha does create some issues.

**Comment by adreporter** [comment] 2017-07-08 16:57
@jspenguin2017 @Dibbyo456 It works for me if I disable EasyList.

**Comment by adreporter** [comment] 2017-07-08 17:17
@jspenguin2017 @uBlock-user @Dibbyo456 
Could you please remove the cache and update EasyList and see if you can see the Captcha?
This is what I see in the logger:
<img width="662" alt="cattura2" src="https://user-images.githubusercontent.com/18214146/27987690-f2baeb58-6411-11e7-9cbd-5b357e158924.PNG">

**Comment by jspenguin2017** [comment] 2017-07-08 17:23
OK, it should be fixed now.

**Comment by uBlock-user** [comment] 2017-07-08 17:25
Solving the second link leads to http://short.am/9SCLoi

Looks like a rotating link of URL shorteners.

**Comment by adreporter** [comment] 2017-07-08 17:31
@jspenguin2017 Now it works, thank you so much.

**Comment by adreporter** [comment] 2017-07-08 17:37
@uBlock-user 

> Solving the second link leads to http://short.am/9SCLoi

I'm going to create a new issue.

**Comment by adreporter** [comment] 2017-07-19 16:29
http://l2s.io/5rCcZ
<img width="306" alt="asas" src="https://user-images.githubusercontent.com/18214146/28378340-1f7756d0-6cb0-11e7-8b52-66324f42a7d7.PNG">
<img width="562" alt="cattura" src="https://user-images.githubusercontent.com/18214146/28378348-259b8dba-6cb0-11e7-8fd6-008ca763930e.PNG">

**Comment by adreporter** [comment] 2017-07-19 16:35
@jspenguin2017 Thanks for the fast fix.

**Comment by adreporter** [comment] 2017-08-15 13:20
@jspenguin2017 
http://u2s.io/Osif
Could you please remove the timer?

**Comment by adreporter** [comment] 2017-08-17 00:56
@jspenguin2017 Thanks. Could you please remove the timer also on these sites?
http://xurl.us/AXQeqV
http://www.adyou.me/FOUS
http://adbilty.me/nZSV

**Comment by jspenguin2017** [comment] 2017-08-17 01:17
yes no yes

**Comment by adreporter** [comment] 2017-08-19 12:21
@jspenguin2017 Thanks as always. I found another site that has a timer.
http://backin.net/nj019p6rtza9
I think this one is different from the others, you have to wait 65 seconds to get the download link. Could you please remove it?

**Comment by jspenguin2017** [comment] 2017-08-19 13:46
Can't, validated on server side.

**Comment by adreporter** [comment] 2017-08-21 17:13
@jspenguin2017 Could you please remove the timer also on these sites?
http://cpmlink.net/GV4WAA#
http://gsurl.in/4rly
http://linkhits.us/PaDgI6NX (instead of timer there is written "please wait")

**Comment by adreporter** [comment] 2017-08-21 17:36
@jspenguin2017 Didn't expect that, so fast! Thank you, you are the best.

**Comment by adreporter** [comment] 2017-08-21 17:55
@jspenguin2017 Didn't expect that, fixed so fast! Thank you very much, you are the best.

**Comment by adreporter** [comment] 2017-08-29 09:50
@jspenguin2017 
http://coshurl.co/w8Pk8
Can you remove the timer?

**Comment by adreporter** [comment] 2017-09-12 15:02
@jspenguin2017 
http://tmearn.com/915y
Another website with timer. Can you remove it?

**Comment by adreporter** [comment] 2017-09-12 23:12
@jspenguin2017 
https://linkhits.net/PaDgI6NX
Instead of the timer there is written "Please Wait...". Can you remove it?

**Comment by jspenguin2017** [comment] 2017-09-12 23:23
Yep.

**Comment by adreporter** [comment] 2017-09-15 11:03
@jspenguin2017 
http://bit-url.com/SEwO
Another website with timer

**Comment by adreporter** [comment] 2017-09-15 13:51
@jspenguin2017 
http://leenlink.com/xd2Ud

**Comment by adreporter** [comment] 2017-09-22 17:29
@jspenguin2017 
http://oke.io/NsIpB

**Comment by adreporter** [comment] 2017-09-23 16:04
@jspenguin2017 
http://wolink.in/2i6
https://bilink.xyz/aaaa
http://git.tc/Lh79

**Comment by jspenguin2017** [comment] 2017-09-23 18:12
For the 3rd one I have to let it tab under, but I'll close the tab automatically as soon as possible.

**Comment by adreporter** [comment] 2017-09-26 10:32
@jspenguin2017 
http://zlshorte.net/wZR8C

**Comment by adreporter** [comment] 2017-10-03 12:53
@jspenguin2017 
http://g5u.pw/1sbya
I can't proceed to the destination page, could you please fix it?

**Comment by adreporter** [comment] 2017-10-03 13:07
@jspenguin2017 
http://g5u.pw/1sbya
After clicking on "Continue", I'm getting a HTTP ERROR 500 or the site redirects me to https://www.getsurl.com/404. I even tried to open the link on Internet Explorer but with the same result. Am I the only one?

**Comment by jspenguin2017** [comment] 2017-10-03 21:28
Since it does not work on a browser without extensions, it is a problem on their end.

**Comment by adreporter** [comment] 2017-10-08 22:38
@jspenguin2017 
http://l2s.io/sRO7
I can't see the captcha
<img width="391" alt="1" src="https://user-images.githubusercontent.com/18214146/31321711-23b65b0a-ac8a-11e7-9799-32413d100ac8.PNG">
Could you please fix it?

**Closed** 2017-10-08 22:48 UTC
Labels: Fixed

**Comment by adreporter** [comment] 2017-10-23 21:19
@jspenguin2017 
https://123link.io/Drl1nV

**Comment by adreporter** [comment] 2017-10-31 23:55
@jspenguin2017 
http://mlink.club/twq8PeJ35bUtTM 
http://shink.xyz/9jeZtP0PqPbe0ihE

**Comment by adreporter** [comment] 2017-11-08 14:13
@jspenguin2017 http://123link.press/J9snr

**Comment by adreporter** [comment] 2017-12-06 22:37
@jspenguin2017 https://met.bz/VfKivut1gt

**Comment by endonesa92** [comment] 2018-01-29 19:52
Hey, Help me please can u fix problem captcha http://l2s.io/e7t6a is not working....
i hope u can fix it thanks...

**Comment by jspenguin2017** [comment] 2018-01-29 21:14
Can't reproduce.

**Comment by adreporter** [comment] 2018-10-31 18:14
@jspenguin2017 
http://fox-url.com/R4b31I
Could you please remove the timer?

**Comment by jspenguin2017** [comment] 2018-10-31 18:59
Yea, it doesn't seem to have server side validation.

**Comment by jspenguin2017** [comment] 2018-10-31 18:59
https://github.com/NanoMeow/QuickReports/issues/268

**Comment by jspenguin2017** [comment] 2018-10-31 19:00
This thread is getting long, please open a new issue for further issues.
