### ISSUE TITLE
uploaduj.net

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/uBlockProtector#729] opened 2017-11-29 19:08 UTC
### Test link (required): 

https://uploaduj.net/download/izabela-trojanowska-wszystko-czego-dzis-chce-www-djoles-pl-mp3-mp3-2017/

### Screenshot of the web page (including address bar and extension icons) (required): 
![capture](https://user-images.githubusercontent.com/15007183/33393905-abd5e63e-d50e-11e7-8b90-051a0ec89ed3.PNG)

**Comment by jspenguin2017** [comment] 2017-11-29 22:07
Hum, could be a tricky one.

**Comment by uBlock-user** [comment] 2017-11-30 05:01
That alert is gone with `uploaduj.net##script:inject(setTimeout-defuser.js, blockAlert)`

but the song doesn't play, does the play for you if you whitelist ?

**Comment by jspenguin2017** [comment] 2017-11-30 13:54
The player is broken either way, the problem is the download button.

**Comment by uBlock-user** [comment] 2017-12-01 05:53
download button open the same page again

**Comment by jspenguin2017** [comment] 2017-12-01 14:08
Hum, you are right, it actually doesn't work at all.

**Comment by jspenguin2017** [comment] 2017-12-01 14:10
This is suspicious, although I'm not sure what exactly is it checking: 
```js
Unet.DPoint = function($) {
    var $dPoint = $('#' + 'down' + 'load' + 'POINT');
    var $blockBox = $('#' + 'block' + 'Alert');
    var $startDownload = $('#' + 'start' + 'Download');
    var $rectangleBox = $("#bmone2n-6930\\.2\\.1\\.36");
    var $dForm = $dPoint.closest('form');
    var palecGrzebalec = true;
    var requested = false;

    return {
        init: function() {
            if ($dPoint.length <= 0)
                return;
            var _this = this;

            $dPoint.on('click', function(e) {
                e.preventDefault();
                var hashV = $dForm.find('#download_hash').val();

                if (hashV.length >= 20) {
                    $dForm.submit();
                } else {
                    _this.blockAlert();
                }
            });

            setTimeout(function() {
                if (palecGrzebalec) {
                    _this.blockAlert();
                }
            }, 3000);
        },
        up: function() {
            if ($dPoint.length <= 0)
                return;

            var start = parseInt($dPoint.data('start')) === 1;
            var hashV = $dForm.find('#download_hash').val() || '';
            var hashT = Unet.AdServer.getToken();
            var token = (hashV.length >= 20 ? hashV : null) || (hashT.length >= 20 ? hashT : null) || null;
            var adLength = $rectangleBox.html().length;
            if (!token || adLength < 1)
                return;

            palecGrzebalec = false;
            $dForm.find('#download_hash').val(token);

            if (start && !requested) {
                requested = true;
                this.request(token);
            }
        },
        request: function(token) {
            $.ajax({
                method: "POST",
                url: $dPoint.data('request'),
                data: {
                    url: window.location.href,
                    hash: token
                }
            }).done(function(msg) {
                if (msg && msg.clientUrl) {
                    $startDownload.removeClass('hide');
                    setTimeout(function() {
                        window.location.href = msg.clientUrl;
                    }, 4000);
                } else {
                    console.log('sthg went wrong...');
                }
            });
        },
        blockAlert: function() {
            $blockBox.removeClass('hide').addClass('red');
            $("html, body").animate({
                scrollTop: $blockBox.offset().top - 100
            }, 200);
            $blockBox.removeClass('red');
        }
    };
}(jQuery || $);
```

**Comment by jspenguin2017** [comment] 2017-12-04 21:25
Related: https://github.com/AdguardTeam/AdguardFilters/issues/8106

**Comment by jspenguin2017** [comment] 2017-12-16 02:20
OK, it's pretty complicated... 
https://github.com/AdguardTeam/AdguardFilters/commit/b06a77e06a6287c87799ed1e34a0f6b120da0e39
https://github.com/AdguardTeam/AdguardFilters/commit/ed0298520eead1c55295fdaec3957f11e5d4c266

**Comment by jspenguin2017** [comment] 2017-12-16 14:17
Resolved in uAssets.

**Closed by jspenguin2017** 2017-12-16 14:17 UTC
Labels: Fixed
