### ISSUE TITLE
dasolo.co

### ISSUE THREAD

**Issue by MrcRel** [jspenguin2017/uBlockProtector#280] opened 2017-06-09 14:13 UTC
When i open an article appears the banner:

Screenshot:
https://s30.postimg.org/du5cswhc1/image.png

I'm using:

- uBlock v1.12.4

-  Protector Script v8.25

- Violent Monkey v2.6.4

- Chromium

Test link:
http://www.dasolo.co/serie-tv/serie-tv-in-corso/541795-agent-of-shield-stagione-4-2016-01-22-mkv-dlmux-aac-ita.html

Thanks.

**Comment by uBlock-user** [comment] 2017-06-09 14:23
Duplicate of https://github.com/jspenguin2017/uBlockProtector/issues/126

Search before you open a new issue.

**Comment by uBlock-user** [comment] 2017-06-09 14:25
`dasolo.co##script:inject(abort-on-property-read.js, alert)`

**Comment by jspenguin2017** [comment] 2017-06-09 14:52
This website's code quality is so bad lol, they have 5 different adblock detector and 3 different context menu blocker...

**Comment by uBlock-user** [comment] 2017-06-09 15:04
They're desperate 🤣

**Comment by uBlock-user** [comment] 2017-06-09 15:05
If it doesn't break anything, then one should just kill the inline-script.

**Comment by uBlock-user** [comment] 2017-06-09 15:16
These guys look like they will keep adding junk just to trouble us some more, that's why I suggested.

**Comment by jspenguin2017** [comment] 2017-06-13 15:32
Looks like it's still working, closing.

**Closed by jspenguin2017** 2017-06-13 15:32 UTC
Labels: Fixed
