### ISSUE TITLE
vidstream.top

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#1072] opened 2019-07-22 09:05 UTC
### Test link (required):
http://vidstream.top/upload

### Screenshot of the web page (including address bar and extension icons) (required):
![2019-07-22_110116](https://user-images.githubusercontent.com/2828165/61620132-863d7500-ac70-11e9-8f11-41ad1559ab1b.png)

### Screenshot of the console (press `F12` to bring up the console) (required):
![2019-07-22_110148](https://user-images.githubusercontent.com/2828165/61620144-8c335600-ac70-11e9-967f-7741118d38c9.png)

**Environment (Required):**
Operating System and Version: WIN 7 64BIT
Browser and Version: Chrome Version 75.0.3770.142 (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.121+Nano Defender 15.0.0.155

**Your filter lists (Required):**
Built-in (10/11)
Nano Defender Integration​​​​​
Nano filters​​​​​
Nano filters – Annoyance
Nano filters – Whitelist​​​​​
uBlock filters​​​​​
uBlock filters – Annoyances​​​​​
uBlock filters – Badware risks​​​​​
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak

**Ads (2/4)**
Adblock Warning Removal List​​​​​
EasyList​​​​​

**Privacy (1/3)**
EasyPrivacy​​​​​

**Malware domains (2/4)**
Malware Domain List​​​​​
Malware domains​​​​​

**Annoyances (3/5)**
Adguard’s Annoyance List​​​​​
Fanboy’s Annoyance List​​​​​
Fanboy’s Anti-Thirdparty Social (see warning inside list)​​​​​​​​​
Fanboy’s Cookiemonster List​​​​​​​​​
Fanboy’s Social Blocking List​​​​​

Multipurpose (2/5)
NoCoin Filter List
Peter Lowe’s Ad and tracking server list

**Regions, languages (3/36)**
ARA: Liste AR
IRN: Adblock-Iran
RUS: RU AdList

**Comment by jspenguin2017** [comment] 2019-07-23 00:53
Can't reproduce. 
![image](https://user-images.githubusercontent.com/7283682/61674657-020be180-acb2-11e9-8629-77e135461ee1.png)

**Comment by jspenguin2017** [comment] 2019-07-23 00:55
Duplicate of https://github.com/NanoAdblocker/NanoFilters/issues/377

**Closed by jspenguin2017** 2019-07-23 00:55 UTC
Labels: Cannot Reproduce
