### ISSUE TITLE
1tv.ru

### ISSUE THREAD

**Issue by ghajini** [jspenguin2017/uBlockProtector#399] opened 2017-07-15 18:28 UTC
changing video quality to HD triggers antiadblock
### Test link (required): 
http://www.1tv.ru/live
### Screenshot of the web page (required): 
https://prnt.sc/fw3bw5

### Screenshot of the console (press `F12` to bring up the console) (required): 
https://prnt.sc/fw3fdg

**Comment by uBlock-user** [comment] 2017-07-16 01:21
Can't reproduce.

**Comment by ghajini** [comment] 2017-07-16 02:44
@uBlock-user 
setup to default settings.....
after clicking play, click settings gear icon of player( [url=http://iconshow.me/media/images/ui/ios7-icons/png/512/gear.png]like this button[/url] and change seeting to HD which will reproduce antiadblock.....

**Comment by uBlock-user** [comment] 2017-07-16 03:09
No need to setup to default settings, I can reproduce it now.

**Comment by ghajini** [comment] 2017-07-17 13:24
@jspenguin2017 
http://static.1tv.ru/player/eump1tv-current/eump-1tv.all.min.js?rnd=1297324695

**Comment by jspenguin2017** [comment] 2017-07-17 14:00
Eh... Can you pin down something more specific?

**Comment by ghajini** [comment] 2017-07-17 14:04
I see that in console.....`it looks like some sort of adblock software enabled` which links to 
http://static.1tv.ru/player/eump1tv-current/eump-1tv.all.min.js?rnd=1297324695

**Comment by jspenguin2017** [comment] 2017-07-17 14:05
Feels like a lot of work...

**Comment by jspenguin2017** [comment] 2017-07-17 21:44
It has multiple stage, fixed the first stage...

**Comment by jspenguin2017** [comment] 2017-07-17 21:44
Another test link: http://www.1tv.ru/shows/hity-interneta/chudo-lyudi/vo-floride-80-chelovek-sozdali-zhivuyu-cep-chtoby-spasti-utopayushih-hity-interneta

**Comment by jspenguin2017** [comment] 2017-07-17 21:47
The detection has multiple stages, this only fixes the first...

**Comment by ghajini** [comment] 2017-07-18 15:12
Fix works ***sometimes***.... Page take forever to load(may be due to 3rd parties).....

**Comment by jspenguin2017** [comment] 2017-07-18 16:41
It loads pretty fast for me. I am aware that it doesn't always work.

**Comment by jspenguin2017** [comment] 2017-07-18 19:44
Dumps: https://pastebin.com/eT2gTpxD

**Comment by jspenguin2017** [comment] 2017-07-18 20:09
I almost got it to work... This breaks autoplay...

**Comment by jspenguin2017** [comment] 2017-07-18 20:45
Content loopback doesn't quite work due to it listening to error event...

**Comment by jspenguin2017** [comment] 2017-07-18 21:18
This seems to work...

**Comment by jspenguin2017** [comment] 2017-07-21 14:35
Still works. Closing.

**Closed by jspenguin2017** 2017-07-21 14:35 UTC
Labels: Fixed

**Comment by UnclWish** [comment] 2017-12-17 11:56
Didn't work again.

**Comment by jspenguin2017** [comment] 2017-12-17 16:06
Still seems to work for me... Any specific test link?

**Comment by UnclWish** [comment] 2017-12-17 16:08
I'm sorry. It's work in Chrome, but I tried in Edge. But in Edge it's no protector extension.
Any plans to add uBlock Protector to Edge?

**Comment by jspenguin2017** [comment] 2017-12-17 16:33
Although I have some plan on doing that, Microsoft Store is full, and I can't publish extension on there. 
Need to wait for Microsoft to raise the limit.

**Comment by UnclWish** [comment] 2017-12-17 16:52
Understand. Thanks! Now will wait MS...
