### ISSUE TITLE
vod.pl

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#494] opened 2017-08-20 19:59 UTC
https://vod.pl/seriale/wmiksowani-online-za-darmo/dtc5g1b

![1](https://user-images.githubusercontent.com/31142317/29497969-d92ce83c-85f2-11e7-8251-4fc9b8a88ad4.png)
![2](https://user-images.githubusercontent.com/31142317/29497970-d93289ea-85f2-11e7-8d5f-c453fe363800.png)

**Comment by jspenguin2017** [comment] 2017-08-20 20:00
Can't reproduce: 
![image](https://user-images.githubusercontent.com/7283682/29497979-f11397ea-85af-11e7-9180-834b5306404f.png)

**Comment by StreamXL** [comment] 2017-08-20 20:06
This is very funny, that is already the 2 side. something is not correct

**Comment by StreamXL** [comment] 2017-08-20 20:14
**UBlock Protector** _turned off_
The page works

**Comment by jspenguin2017** [comment] 2017-08-20 20:32
How does your setup differ from the [standard setup](https://github.com/jspenguin2017/uBlockProtector/blob/master/Notes/Standard%20Configuration.MD) ?

**Comment by lain566** [comment] 2017-08-20 20:41
I can reproduce only if I delete cookies and refresh the page

**Comment by jspenguin2017** [comment] 2017-08-20 21:01
Hum, was able to reproduce once...

**Comment by uBlock-user** [comment] 2017-08-21 12:29
wasn't this patched already with other .pl group domains ?

**Comment by HateAds** [comment] 2017-08-21 13:03
@jspenguin2017
The video doesn't load when uBlock Protector Extension is enabled.

**Comment by jspenguin2017** [comment] 2017-08-21 13:32
@uBlock-user What was the patch? 

@HateAds It should be fixed now.

**Comment by jspenguin2017** [comment] 2017-08-21 14:03
Something isn't working correctly with GitHub, `git remote prune origin` was hanging, and now pipeline is stuck.

**Comment by uBlock-user** [comment] 2017-08-21 14:37
I can't find the case, must have been another .pl domain I suppose.

**Closed** 2017-08-22 13:32 UTC
Labels: Fixed
