### ISSUE TITLE
hdblog.it

### ISSUE THREAD

**Issue by LukePoke** [jspenguin2017/uBlockProtector#904] opened 2018-04-10 13:09 UTC
https://windows.hdblog.it/2018/04/10/windows-3-file-manager-open-source/

Screenshot of the web page (including address bar and extension icons) (required):
https://i.imgur.com/hsDpxIF.png

Screenshot of the console (press F12 to bring up the console) (required):
https://i.imgur.com/HofOWFw.png

Environment (Required):

- Operating System and Version: Windows 10 Pro
- Browser and Version: Firefox 59.0.2 (64 bit)
- Adblocker and Version: Ublock Origin 1.15.24

Every news on this site is blocked.

**Comment by jspenguin2017** [comment] 2018-04-10 14:10
@okiehsch

**Comment by mapx-** [comment] 2018-04-10 21:35
https://github.com/uBlockOrigin/uAssets/commit/0e7e628f3c225c6df040a7a7384c11af60991c1e

**Comment by xlollomanx** [comment] 2018-04-11 07:27
I'm italian and I use this site too. I cleared cache filter and updated it but adblock warning is still here https://prnt.sc/j3ocxs

**Comment by okiehsch** [comment] 2018-04-11 07:38
Which italian filter lists are you using?

**Comment by xlollomanx** [comment] 2018-04-11 07:49
@okiehsch this is my active filter list atm
![adblock list](https://user-images.githubusercontent.com/6764804/38603342-a4d01dd8-3d6d-11e8-9480-3496bd6f04b2.png)

**Comment by okiehsch** [comment] 2018-04-11 07:54
OK, the `ITA: ABP X Files` causes your issue, I do not think that it is enabled by default.

Does it work, if you add
`hdblog.it##script:inject(setInterval-defuser.js, AdBlock)`
to your filter list?

**Comment by gabri25ele** [comment] 2018-04-11 07:54
if ABP X Files is enabled, NOT work
if disabled work

**Comment by xlollomanx** [comment] 2018-04-11 07:56
@okiehsch with that string it works perfect, should I disable ITA: ABP X File ? it really worth?

**Comment by okiehsch** [comment] 2018-04-11 08:01
It is not useless, but if you have it enabled, you have to keep
`hdblog.it##script:inject(setInterval-defuser.js, AdBlock)` in your filter list, because it will not be added to
`uBO-filters` as only issues with  a default setup will be fixed in that list.

**Comment by xlollomanx** [comment] 2018-04-11 08:10
@okiehsch ok thank you :)

**Comment by jspenguin2017** [comment] 2018-04-11 12:26
@okiehsch That is a regional filter though, it will be automatically enabled if the browser has italian locale.

**Comment by xlollomanx** [comment] 2018-04-11 15:04
@jspenguin2017 The filter `ITA: ABP X Files ` is currently not enabled by default. Only `ITA: EasyList Italy` is active by default. My pc is italian localized and I usally enable `ITA: ABP X Files` every time I do a clean installation of w10.

**Comment by gabri25ele** [comment] 2018-04-11 15:19
@xlollomanx use this https://filters.adtidy.org/extension/chromium/filters/2.txt instead of EasyList
I have that and xfiles activated

**Comment by jspenguin2017** [comment] 2018-04-11 16:03
Eh, I thought all regional filters have language flag, I guess I need to read the manifest again.

**Comment by okiehsch** [comment] 2018-04-12 21:57
@jspenguin2017 I asked and it is no mistake, looking through that list you can see why.
Filters like `http://www.888.it/$popup` are really not what you would like to have in alist that is enabled by default.

**Comment by jspenguin2017** [comment] 2018-04-12 22:26
Ah, alright.

**Comment by gabri25ele** [comment] 2018-04-13 07:29
today, hdblog.it no work anymore

**Comment by mapx-** [comment] 2018-04-13 10:14
use easylist italy + last ubo filters

**Comment by mapx-** [comment] 2018-04-13 10:40
I said you to use only ublock filters + easylist italy. Update now ublock filters.

**Comment by gabri25ele** [comment] 2018-04-13 10:43
I told you I use ublock filters + easylist italy!
I told in this thread that the tweak hdblog.it##script:inject(setInterval-defuser.js, AdBlock) not work anymore

**Comment by mapx-** [comment] 2018-04-13 10:47
No, you said nothing.

However, what filters do you see in your logger ?

**Comment by gabri25ele** [comment] 2018-04-13 10:57
No, you don't understand.
read all the messages in this this thread so you can understand.
👎

**Comment by LukePoke** [comment] 2018-04-13 11:13
I confirm there is still the block.

**Comment by gabri25ele** [comment] 2018-04-13 11:34
Yes, we know the problem is Xfile filter!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2 days ago

>  okiehsch commented 2 days ago
>  OK, the ITA: ABP X Files causes your issue, I do not think that it is enabled by default.
>  Does it work, if you add
>  hdblog.it##script:inject(setInterval-defuser.js, AdBlock)
[...]

>  with hdblog.it##script:inject(setInterval-defuser.js, AdBlock) (and xfile activated) seems to be ok

today the filter "hdblog.it##script:inject(setInterval-defuser.js, AdBlock)" not work

**Comment by LukePoke** [comment] 2018-04-13 11:36
Non usare ABPX e bona!

**Comment by gabri25ele** [comment] 2018-04-13 11:47
bona notte
I want to use xfile, I prefer to disable cosmetic filter.

**Comment by LukePoke** [comment] 2018-04-13 11:53
Allora apri qui una richiesta:
https://xfiles.noads.it/

**Comment by mapx-** [comment] 2018-04-13 11:54
for abx add also
```
hdblog.it#@#.ads_block
hdblog.it#@#[id^="banner"]
```

**Comment by xlollomanx** [comment] 2018-04-14 13:11
Seems like ABP X files gives more problems than it solves. I've disabled it for now.

**Comment by xlollomanx** [comment] 2018-04-19 10:01
@jspenguin2017 seems this site not working anymore: https://prnt.sc/j7ac5m

Console: https://prnt.sc/j7ae85

Site is accessible if I disable cosmetic filter or if I disable inline-script but with inline-script filter it remove  a lot of things (I'm too noob to deeply understand what I have to filter)

**Comment by jspenguin2017** [comment] 2018-04-19 14:38
Eh, they are probably watching us.

**Comment by okiehsch** [comment] 2018-04-20 00:04
https://github.com/uBlockOrigin/uAssets/commit/c351cf0df5453dad249924274b41ea7801761eff

**Comment by jspenguin2017** [comment] 2018-04-20 00:11
Should we move to the private issues tracker? 
Issues should be only visible to the reporter and contributors, I see little to no benefit in allowing everyone to see the average issue. 
I know people can still check the commit log but that is a lot harder than subscribing to the issue and get notified as soon as a patch is pushed.

**Comment by okiehsch** [comment] 2018-04-20 00:25
We already have a `uAssets-team` issue about `hdblog.it`, so it really your call.

**Comment by okiehsch** [comment] 2018-04-20 00:40
I can see your point and in the future I can notify you privately about any commit pertaining this issue.

You would have to tell me how though :)

**Comment by jspenguin2017** [comment] 2018-04-20 01:53
> I can notify you privately about any commit

That wouldn't really work, as opening and closing the issue still generate notifications. I don't want to make things hard for contributors, so allowing core contributors to easily know which commit goes where is still important. 

I'm thinking of using the GitLab issues tracker and mark everything as confidential.

**Comment by xlollomanx** [comment] 2018-04-20 10:59
I' ve updated to latest version of Nano Adblocker and now site working correclty. I don't know if you have fixed something but now it works :) 
Btw I agree with you to do something about this otherwise a lot of time will be wasted

**Closed** 2018-04-24 00:04 UTC
Labels: Fixed

**Comment by jspenguin2017** [comment] 2018-04-24 00:10
For further issue with this website, please open a confidential issue here: 
https://gitlab.com/xuhaiyang1234/NanoAdblockerSecretIssues/issues
