### ISSUE TITLE
filecrypt.cc

### ISSUE THREAD

**Issue by EmersonTR** [jspenguin2017/uBlockProtector#766] opened 2017-12-19 00:04 UTC
### Browser: Vivaldi Snapshot 1.14.1042.3 (64 bits)

**Comment by jspenguin2017** [comment] 2017-12-19 00:32
It's a mining wall.

**Comment by jspenguin2017** [comment] 2017-12-19 00:33
Actually, I'll mark this as duplicate of https://github.com/jspenguin2017/uBlockProtector/issues/624

**Comment by jspenguin2017** [comment] 2017-12-19 00:33
Duplicate of #624

**Closed by jspenguin2017** 2017-12-19 00:32 UTC

**Comment by jspenguin2017** [comment] 2017-12-19 00:45
Actually, the mining doesn't start automatically, so I'll put an exception.
