### ISSUE TITLE
genbird.com

### ISSUE THREAD

**Issue by Sheeraudacity** [jspenguin2017/uBlockProtector#316] opened 2017-06-23 12:48 UTC
http://genbird.com/
I realize by now that I need to learn basic css to learn how to deal with these issues but for now I'll be relying on your help I hope you'll bear with me for a while till then, anyway this one gets me back to those intrusive adbock detectors
![pr 2](https://user-images.githubusercontent.com/28789170/27482758-5d52cb40-582b-11e7-8c2c-182721e6d39e.png)

**Comment by uBlock-user** [comment] 2017-06-23 13:15
Can't reproduce. This is AntiBlock v2 script and already patched by the generic solution in the Script. But somehow the it's not being applied on your end. Are you running any other Scripts like AAK or AAK Cont?

**Comment by uBlock-user** [comment] 2017-06-23 13:21
FYI, this is how you're supposed to post - https://github.com/jspenguin2017/uBlockProtector/issues/301#issue-236629031

**Comment by Sheeraudacity** [comment] 2017-06-23 13:24
ads bypasser didn't interfere with protector before I'll try it without it, nope still detects it I don't have any other scripts running, could it be a 3rd party filter and ooh thanks for showing me an example but it seems redundant to post all 3 when they all show either way but I'll try to follow the better and post in the general format anyway

**Comment by uBlock-user** [comment] 2017-06-23 13:36
Clear the cache and then refresh the page. 

Also that format is here for a reason and it's very simple, you just copy it and swap the links with yours, How hard could that be ?

**Comment by Sheeraudacity** [comment] 2017-06-23 13:46
will try that, also I get the reason why the format exists it's just redundant to post 3 links when 1 link is enough like writing 3+3+3 rather than 3x3, but I'll post in that "right " format next time anyway

**Comment by jspenguin2017** [comment] 2017-06-23 13:56
@Sheeraudacity You can post it the way you want, but you risk to be banned if I cannot reproduce it easily.

**Comment by uBlock-user** [comment] 2017-06-23 13:57
It's NOT redundant. First is the direct link, so the contributors like me don't have to **search** for it and waste my time there. Second is the picture proof that proves that you're not opening an invalid issue and making it up which has happened many times before here, so you wouldn't know that. Finally the third is to check whether the script is running on **YOUR** end or not and whether any existing solution is being applied or not on your end. 

It's all to make a contributor's life easy when dealing with issues like yours and others everyday and where the contributor puts his own time as this is volunteer activity and not a job. The more details you provide the faster the solution is dispatched. If you think this is too much, try opening a new issue at the Chromium bug tracker.

**Comment by jspenguin2017** [comment] 2017-06-23 13:59
Weird site, behaves differently as I refresh...

**Comment by uBlock-user** [comment] 2017-06-23 14:20
Not "triggered", but rather justifying your claim that it's redundant so you would understand why I insist you do that. I'm sure if you and me were to switch places, you would feel the same about those three requirements. Also I dislike having to tell every now and then to post in the proper format, every one else is already doing it, so just go with the flow man.

**Comment by jspenguin2017** [comment] 2017-06-23 15:51
Generic solutions will generate a log if it is triggered. This one seems to be a custom function.

**Comment by jspenguin2017** [comment] 2017-06-23 15:56
OK, pushing 9.5 to the store... I should work on automation...

**Comment by jspenguin2017** [comment] 2017-06-27 13:31
Still works. Closing.

**Closed by jspenguin2017** 2017-06-27 13:31 UTC
Labels: Fixed
