### ISSUE TITLE
wenxuecity.com

### ISSUE THREAD

**Issue by vic958420** [jspenguin2017/uBlockProtector#1117] opened 2020-06-03 15:56 UTC
### Test link (required):
https://www.wenxuecity.com/news/2020/06/03/9528733.html

### Screenshot of the web page (including address bar and extension icons) (required):
https://i.imgur.com/lBc0nqA.jpg

### Screenshot of the console (press `F12` to bring up the console) (required):
https://i.imgur.com/2xSAy32.jpg

### Explain what was not right (optional if obvious):
Website asks you to support them by disabling the adblock extensions (its a Chinese news website)

### Reproduction steps (optional if trivial):
1. Go to www.wenxuecity.com
2. Click on any of the articles

### Environment (Required):

- Operating System and Version: Windows 10 version 1909
- Browser and Version: Google Chrome version 83.0.4103.61
- Adblocker and Version: Ublock Origin version 1.27.10

#### Your filter lists (Required):
 Ublock filters (default, badware risks, privacy, resource abuse, unbreak)
Adguard base, adguard mobile ads, easylist
adguard tracking protection, easyprivacy, fanboy's enhanced tracking list
malware domain list, malware domains, spam404
adguard annoyances, adguard social media, anti-facebook, easylist cookie, fanboy's annoyance, fanboy's social, ublock filters - annoyances
mvps hosts, peter lowe's ad and tracking server list
chn: cjx easylist lite, easylist china
adblock warning removal list, malvertising filter list by disconnect, nano defender integration, nano filters

#### Your custom filters (Required if you have any):
old.reddit.com##.listingsignupbar.infobar
old.reddit.com##.commentsignupbar.infobar
www.forbes.com##.right-rail

#### Your other extensions (Required if you have any):
See screenshot: https://i.imgur.com/lBc0nqA.jpg

**Comment by jspenguin2017** [comment] 2020-06-04 00:03
Duplicate of https://github.com/NanoMeow/QuickReports/issues/4008

**Closed by jspenguin2017** 2020-06-04 00:03 UTC
