### ISSUE TITLE
play.tv3.lt

### ISSUE THREAD

**Issue by Vartotojas1234** [jspenguin2017/uBlockProtector#267] opened 2017-06-07 10:09 UTC
http://play.tv3.lt/programos/detektyve-klara/847664?autostart=true

![image](https://user-images.githubusercontent.com/7283682/26888590-b108be86-4b68-11e7-988b-025b1de1e80b.png)

**Comment by uBlock-user** [comment] 2017-06-07 11:44
FF is not part of supported setups.

**Comment by ale5000-git** [comment] 2017-06-07 12:50
It does happen also on Chrome, but I'm not sure that the problem can be resolved since it say "Atsisiųskite mūsų nemokamą programėle, kad galėtumėte peržiūrėti šį video".

Translation: "Download our free app to view this video".

**Comment by uBlock-user** [comment] 2017-06-07 13:24
It flat out says "Download our free app to view this video" so I haven't bothered to look any further.

**Comment by jspenguin2017** [comment] 2017-06-07 13:38
@uBlock-user It doesn't say that when uBO is off.

**Comment by jspenguin2017** [comment] 2017-06-07 13:39
Your setup is broken in every possible way, but it happens to be reproducible on the standard setup, so I assume you know what you are doing, but this is still a warning.

**Comment by uBlock-user** [comment] 2017-06-07 13:56
This is the only script that has signs of Anti adblock code - http://cdn.playstatic.mtgx.tv/static/js/main-w-avod-player/main-w-avod-player.js?v=3.52

So it's the embedded player

**Comment by jspenguin2017** [comment] 2017-06-07 13:59
@uBlock-user I don't neither, but I do when I need to test something. 
![image](https://user-images.githubusercontent.com/7283682/26882276-28db1b64-4b57-11e7-85c6-3d7e9d65160b.png)

**Comment by uBlock-user** [comment] 2017-06-07 14:01
Well If I ever turn uBO off, my browser will be raped and I have experienced it first hand. Also websites behave very differently without the presence of any kind of network/content blocker, so I always keep it on.

**Comment by jspenguin2017** [comment] 2017-06-07 15:01
@uBlock-user Yea, it can happen. Depending on the site. I know the way my browser work and I can distinguish baits from real prompt, so I can get out of malvertizing sites.

**Comment by jspenguin2017** [comment] 2017-06-07 15:35
I think I know how it works now: 
It loads `http://playapi.mtgx.tv/v3/videos/stream/847664`, which contains the media file link: `https://tv3-vod.data.lt/tv3vod/video/video/smil:/SMIL_ACQ/2017/2017_05/20364103/20364103.smil/playlist.m3u8`. 
Then it tries to load `https://playapi.mtgx.tv/v3/adinfo?video=847664&adPlatform=FreeWheel&platform=html5&referer=&clientPlatform=pc`, which contains the line `"ab_allowed":false,`, I bet if I flip it to true it would work... Except that I don't really have a way to change it.

**Comment by jspenguin2017** [comment] 2017-06-07 16:07
Eh... I just found out that we failed pretty hard on this domain... 
![image](https://user-images.githubusercontent.com/7283682/26888699-10d196da-4b69-11e7-99d5-07991061a0c6.png)

**Comment by jspenguin2017** [comment] 2017-06-07 16:36
I don't think I can fix this one... I can find the source, just can't quite play that file.

**Comment by uBlock-user** [comment] 2017-06-07 17:04
> failed pretty hard 

How did we ? Did we miss something ?

**Comment by jspenguin2017** [comment] 2017-06-07 17:06
https://github.com/jspenguin2017/uBlockProtector/issues/110#issuecomment-292396290
https://github.com/brave/browser-laptop/issues/8999
Looks like Brave browser didn't fix it yet...

**Comment by jspenguin2017** [comment] 2017-06-07 17:13
@uBlock-user currently, we are fighting anti-adblock code with more code, Violentproxy is an experiment where I will remove anti-adblock code directly instead of fighting them. 
Project page: https://github.com/Violentproxy/Violentproxy

**Comment by uBlock-user** [comment] 2017-06-07 17:13
Easylist has some whitelisted filters for viafree if you want to try that - https://forums.lanik.us/viewtopic.php?f=62&t=32175&p=107099&hilit=viafree.se#p107099

**Comment by uBlock-user** [comment] 2017-06-07 17:15
Yeah I saw that repo, but how are you using it via uBlockProtector Script ?

**Comment by jspenguin2017** [comment] 2017-06-07 17:16
@uBlock-user I'll have a "Serverscript" that uses Violentengine API to patch requests and responses. I'll be a standalone solution system.

**Comment by jspenguin2017** [comment] 2017-06-07 17:18
@uBlock-user Doesn't seem to work. 
![image](https://user-images.githubusercontent.com/7283682/26891637-fdb22a56-4b72-11e7-8c27-7f187188c126.png)

**Comment by uBlock-user** [comment] 2017-06-07 17:32
Yeah consider them outdated, they were posted back in Nov 2016.

**Comment by uBlock-user** [comment] 2017-06-07 17:33
So we will have to install VP separately as another script ?

**Comment by uBlock-user** [comment] 2017-06-07 17:43
@jspenguin2017 I'm okay, I like to keep an open mind to such new things.

**Comment by ghajini** [comment] 2017-06-09 15:40
We can take help of @okiehsch or @gorhill to resolve these issues
`https://github.com/jspenguin2017/uBlockProtector/blob/master/Notes/No%20Solution.MD`
If you don't mind@jspenguin2017

**Comment by okiehsch** [comment] 2017-06-09 19:11
Looks like the site uses `brightcove` and `stream-stitching`. I don't think there is a way, to circumvent the
pre-roll ads.
To watch the video the bare minimum exceptions are 
````
@@||playapi.mtgx.tv/v3/adinfo$xmlhttprequest,domain=play.tv3.lt
@@||mssl.fwmrm.net/p/MTG_Brightcove_HTML5/AdManager.js$script,domain=play.tv3.lt
@@||fwmrm.net/ad$script,domain=play.tv3.lt
````
as far as I can see.

**Comment by jspenguin2017** [comment] 2017-06-09 19:22
@okiehsch OK, thanks, I won't add anything that would allow ads in, if an user is desperate enough, he can use your workaround. 
I don't think the ads are baked into the stream on the server side, because you can't control the progress bar when ads are playing. If done right, I think it would be possible to patch this with some complex Userscript. But so far, I have no luck, I can grab the m3u8 playlist, but that's it, I couldn't find a way to use the playlist...

**Comment by uBlock-user** [comment] 2017-06-10 04:51
@jspenguin2017 Why not replace the entire player then ?

**Comment by ale5000-git** [comment] 2017-06-10 09:59
If the format is supported, maybe using the HTML5 Video tag.

**Comment by jspenguin2017** [comment] 2017-06-10 13:46
@uBlock-user That's what I'm doing, but I can't parse the media file. 

@ale5000-git I obviously already tried that...

**Comment by jspenguin2017** [comment] 2017-06-11 01:14
Hi guys, I received help privately, and I have a fix for it now 😄 
![image](https://user-images.githubusercontent.com/7283682/27007439-00df730a-4e11-11e7-90ab-580a79e1824d.png)

**Comment by ghajini** [comment] 2017-06-11 01:21
Will it work on all listed `no solution` sites....That will be great

**Comment by jspenguin2017** [comment] 2017-06-11 01:25
@ghajini Keep in mind that GeoLock will not be bypassed, only the anti-adblock.

**Comment by jspenguin2017** [comment] 2017-06-11 01:25
These domains should be fixed: `["viafree.no", "viafree.dk", "viafree.se", "tvplay.skaties.lv", "play.tv3.lt", "tv3play.tv3.ee"]`

**Comment by ghajini** [comment] 2017-06-11 01:27
That's good....I can pass geolock with vpn....fix others also
`https://github.com/jspenguin2017/uBlockProtector/blob/master/Notes/No%20Solution.MD`

**Comment by jspenguin2017** [comment] 2017-06-11 01:33
@ghajini The discussion is in one confidential issue in my GitLab repository, the code is still out there, it's still public. I think I can fix one more, but the last one is probably not going to work with the new technique.

**Comment by jspenguin2017** [comment] 2017-06-17 16:15
Still works, closing.

**Closed by jspenguin2017** 2017-06-17 16:15 UTC
Labels: Fixed
