### ISSUE TITLE
history.com

### ISSUE THREAD

**Issue by ml3000** [jspenguin2017/uBlockProtector#329] opened 2017-06-26 19:55 UTC
http://www.history.com/shows/alone/season-4/episode-0

![image](https://user-images.githubusercontent.com/27796607/27557518-bef15b92-5a6e-11e7-9be5-500c666cdb6f.png)

![image](https://user-images.githubusercontent.com/27796607/27557494-acd377e2-5a6e-11e7-969e-e5ad28968774.png)

**Comment by uBlock-user** [comment] 2017-06-26 21:22
Can't reproduce. But the video doesn't play either for me. Remains stuck as a picture.

**Comment by uBlock-user** [comment] 2017-06-26 21:24
Same as https://github.com/jspenguin2017/uBlockProtector/issues/304

Requires Flash too.

**Comment by jspenguin2017** [comment] 2017-06-26 21:25
US Geo Lock, I don't think this one requires Flash, but yes, the same fix works.

**Comment by uBlock-user** [comment] 2017-06-26 21:28
It does require Flash because the video player never initializes as Flash is not built-in in Chromium builds. Metadata is pulled so I can only witness the picture and it remains stuck there. I also ran the logger, nothing is being blocked to have this happen.

**Comment by uBlock-user** [comment] 2017-06-26 21:45
Okay, I can reproduce it now, but on another link. It doesn't require flash, but the reproduction is by chance, I could reproduce it once and not again without uBP.

link - http://www.history.com/shows/alone/season-4/episode-1

**Comment by jspenguin2017** [comment] 2017-06-26 21:48
@uBlock-user That's because EasyList is whitelisting `doubleclick.net`.

**Comment by uBlock-user** [comment] 2017-06-26 21:55
I have `||doubleclick.net^$important` on my personal filterlist and all ad-servers are blocked, so easylist whitelists never affect me. That's not the reason anyway.

**Comment by jspenguin2017** [comment] 2017-06-30 19:03
Still works, closing.

**Closed by jspenguin2017** 2017-06-30 19:03 UTC
Labels: Fixed, Geo Lock
