### ISSUE TITLE
NSFW! kisshentai.net, kissasian.com

### ISSUE THREAD

**Issue by gavbn** [jspenguin2017/uBlockProtector#256] opened 2017-06-01 16:16 UTC
Before opening an issue, you MUST read the contribution guideline. Failure to do so may result in a ban. 

Test link: http://kisshentai.net/Hentai/Oni-Chichi-Refresh/Episode-004?id=2427

Screenshot: 
![capture](https://cloud.githubusercontent.com/assets/23123477/26689451/50fb9774-4713-11e7-89bc-ed9f8171393c.PNG)

I have ublock protector list and it's .js
![capture](https://cloud.githubusercontent.com/assets/23123477/26689508/811c836e-4713-11e7-8294-5448ba93ef77.PNG)

![capture](https://cloud.githubusercontent.com/assets/23123477/26689543/9791e562-4713-11e7-817a-cd5af064c543.PNG)

Add everything else that you believe to be useful below: 
I am using chrome and it is still blocks the ublock origin

**Comment by jspenguin2017** [comment] 2017-06-01 16:52
Huh, I still can't reproduce it, how long does it take for it to show up? 

I killed the popup with 8.13, the BetterJsPop defuser is now part of generic solution.

**Comment by gavbn** [comment] 2017-06-01 17:10
It usually occurs in 6-7 seconds after I click on the episode link

**Comment by jspenguin2017** [comment] 2017-06-01 17:30
Still can't reproduce, waited 15 min on your test link and another random link.

**Comment by jspenguin2017** [comment] 2017-06-01 17:31
Try to configure your setup *exactly* like this: https://github.com/jspenguin2017/uBlockProtector/blob/master/Notes/Standard%20Configuration.MD

**Comment by uBlock-user** [comment] 2017-06-01 19:14
Can't reproduce.

For popups, I use `kisshentai.net##script:inject(abort-on-property-read.js, BetterJsPop)`

**Comment by jspenguin2017** [comment] 2017-06-01 20:27
@uBlock-user I have 2 generic solutions ready, they are currently commented out. I applied `readOnly` on `BetterJsPop` and it disables it.

**Comment by uBlock-user** [comment] 2017-06-01 20:36
Yes thanks for making it generic. It's now being used on many sites for triggering popups.

**Comment by jspenguin2017** [comment] 2017-06-01 20:47
@uBlock-user 
The generic solution is not activated as I think it's kind of heavy. Not that many sites uses it anyway. The solution implements a neutralized version of BetterJsPop. 
Until now, locking the variable `BetterJsPop` to an empty function works, but it can happen that a website will break if the variable is locked, as it will throw error since the "quick solution" doesn't have any of the API. 
I'm not sure what to do for it yet.

**Comment by gavbn** [comment] 2017-06-02 07:28
It still showing the same thing

**Comment by LaxusiC** [comment] 2017-06-02 09:24
it working for me tho

**Comment by tydrol** [comment] 2017-06-03 08:11
I was going to post a new issue, but since I think the website I'm having trouble with is part of the same "family" as the site in this issue, I guess I should comment in here first.

http://kissasian.com/

Attemping to watch any movie/tv show results in the video being replaced with an anti-adblock image after 10-20 or so seconds. 

Here's a test link: http://kissasian.com/Drama/1911/Movie?id=24448

![kissasian](https://cloud.githubusercontent.com/assets/29158832/26751920/4fa6dc8a-47f9-11e7-93c0-5cf0d39c974a.jpg)

**Comment by jspenguin2017** [comment] 2017-06-03 14:07
OK, I can reproduce now.

**Comment by uBlock-user** [comment] 2017-06-03 15:46
Videos from Google server are all broken on the website, so cannot test it atm.

**Comment by uBlock-user** [comment] 2017-06-03 15:48
For Kissasian Anti Adblock - add `||kissasian.com/*.aspx`

**Comment by jspenguin2017** [comment] 2017-06-03 16:07
@uBlock-user Oh, seems to work. 👍

**Comment by uBlock-user** [comment] 2017-06-03 16:35
It works perfectly. All `aspx` urls are for pulling ads and checking whether ads are loaded or not. Same on the  rest of Kiss sites.

**Comment by jspenguin2017** [comment] 2017-06-07 16:53
Looks like it's still working. Closing.

**Closed by jspenguin2017** 2017-06-07 16:53 UTC
Labels: Fixed

**Comment by markuznw** [comment] 2017-06-25 09:10
Hello @jspenguin2017, on kissasian it still doesn't work, I got no idea if they changed their detection script but using the @tydrol test link it gives the same image. I'm on latest extension v9.10

Thanks in advance for awesome work on extension!

![image](https://user-images.githubusercontent.com/779743/27514880-d735eab6-5996-11e7-92c1-ace7538952ad.png)

**Comment by jspenguin2017** [comment] 2017-06-25 13:42
@markuznw Can't reproduce: 

![image](https://user-images.githubusercontent.com/7283682/27516577-de721574-5979-11e7-9337-1978060c3b1c.png)

**Comment by markuznw** [comment] 2017-06-25 13:48
Oh, I've double checked ublock now and uBlock Protector List was disabled for some reason (it was enabled until i used the script o.o) With it enabled it works fine.

Thanks for the fast response and sorry for the false positive :)

**Comment by uBlock-user** [comment] 2017-10-02 16:42
I can reproduce the anti adblock today

http://kisshentai.net/Content/js/adframe.js

`kisshentai.net##script:inject(abort-on-property-read.js, adblock)`

If you can't reproduce it still then it's whitelisted by some Easylist group filter, running the logger would give the idea about the specific one.

**Comment by jspenguin2017** [comment] 2017-10-03 00:18
It's me or the edit button is gone?

**Comment by uBlock-user** [comment] 2017-10-03 10:37
By edit button, you mean edit comment ? I can see it and it works too as expected.

**Comment by ghajini** [comment] 2018-06-04 17:48
@jspenguin2017,

https://github.com/uBlockOrigin/uAssets/issues/2465

**Comment by jspenguin2017** [comment] 2018-06-04 23:47
One ping is enough.
