### ISSUE TITLE
wstream.video

### ISSUE THREAD

**Issue by antiadblockreporter** [jspenguin2017/uBlockProtector#1118] opened 2020-06-06 11:39 UTC
`https://wstream.video/video6zvimpy52/gw5qkz0hdjgu`

<img width="422" alt="Przechwytywanie" src="https://user-images.githubusercontent.com/66200964/83943003-e261a700-a7f8-11ea-823a-db445dfbe6c7.PNG">
<img width="960" alt="Przechwytywanie1" src="https://user-images.githubusercontent.com/66200964/83943010-eab9e200-a7f8-11ea-9065-45c2b21af17b.PNG">
<img width="960" alt="Przechwytywanie2" src="https://user-images.githubusercontent.com/66200964/83943013-f0172c80-a7f8-11ea-9b3c-91ba7538df5e.PNG">

Unfortunately filters for this website in uAssets last for max 1-2 days.
Could you please find a solution with Nano Defender?

**Comment by jspenguin2017** [comment] 2020-06-06 15:22
Duplicate of https://github.com/NanoMeow/QuickReports/issues/3971

**Closed by jspenguin2017** 2020-06-06 15:22 UTC
Labels: Duplicate
