### ISSUE TITLE
"This extension may have been corrupted" error

### ISSUE THREAD

**Issue by martilucena** [jspenguin2017/uBlockProtector#454] opened 2017-08-06 18:57 UTC
### Screenshot of the web page: 

![screenshot1](https://user-images.githubusercontent.com/30754371/29006024-4ad75794-7ae8-11e7-9882-880994b05e16.png)

![screenshot2](https://user-images.githubusercontent.com/30754371/29006026-537b57c4-7ae8-11e7-9bcf-731584db0e95.png)

When I allow the extension to work in incognito mode, it stops working and this message appears: "This extension may be damaged." (Sorry for my bad English)

**Comment by jspenguin2017** [comment] 2017-08-06 19:06
Can't reproduce. Try reinstall? 
![image](https://user-images.githubusercontent.com/7283682/29006182-1993bff0-7aa8-11e7-8ce2-3f649f6d53bb.png)

**Comment by jspenguin2017** [comment] 2017-08-06 19:49
Huh, if I uncheck allow in incognito and recheck it, I can reproduce... 
This should be a bug in Chromium.

**Comment by jspenguin2017** [comment] 2017-08-06 19:55
https://bugs.chromium.org/p/chromium/issues/detail?id=643814

**Comment by jspenguin2017** [comment] 2017-08-06 20:07
That Chromium bug is marked as fixed, hum... 
Is any other extension experiencing this problem?

**Comment by martilucena** [comment] 2017-08-06 20:20
No, none of the extensions I have installed have this problem

**Comment by uBlock-user** [comment] 2017-08-06 20:22
https://github.com/gorhill/uBlock/issues/2720

Chromium 59 bug

**Comment by uBlock-user** [comment] 2017-08-06 20:24
Shouldn't happen inn Chrome 60 if you have updated to the latest stable version.

**Comment by jspenguin2017** [comment] 2017-08-06 20:25
Eh... Don't tell me this is the problem...
![image](https://user-images.githubusercontent.com/7283682/29006745-254fd6f2-7ab3-11e7-8160-0c80325c88ac.png)

**Comment by jspenguin2017** [comment] 2017-08-06 20:26
I am on Chrome 60, still occurs.

**Comment by martilucena** [comment] 2017-08-06 20:27
I am on Chrome 60 too

**Comment by jspenguin2017** [comment] 2017-08-06 20:27
I'll add a logic to work around this. Probably to CI

**Comment by jspenguin2017** [comment] 2017-08-06 20:34
I'll add a logic to automatically scan for file with "bad" sizes and add white spaces automatically. Meanwhile, I manually padded the file.

**Comment by martilucena** [comment] 2017-08-06 20:38
The extension works fine again!

**Comment by jspenguin2017** [comment] 2017-08-06 20:39
Don't close yet, I want to workaround this Chromium bug for good.

**Comment by jspenguin2017** [comment] 2017-08-06 21:30
This should be fixed for good now.

**Comment by uBlock-user** [comment] 2017-08-07 09:09
can't reproduce it on Chrome 61 or 62.

**Comment by jspenguin2017** [comment] 2017-08-07 14:25
That's good news, but I have to support 59 and 60 until at least 62 hit stable. That means half a year.

**Comment by uBlock-user** [comment] 2017-08-09 12:32
> can't reproduce it on Chrome 61 or 62.

FYI, by that, I meant, I could never reproduce it on 61 and forward and not because of the fix you landed. I could never reproduce it on those versions from the beginning and only happened to me on v59.

**Comment by jspenguin2017** [comment] 2017-08-09 13:59
Yes, that's how I read it. I will need to wait until 62 or 63 to hit stable before removing the check from pipeline. 
The pipeline script looks like to be working properly now, closing.

**Closed by jspenguin2017** 2017-08-09 13:59 UTC
Labels: Fixed

**Comment by jspenguin2017** [comment] 2017-08-10 20:21
It's confirmed that it is not fixed in Chrome 60, will be fixed in 61: 
https://bugs.chromium.org/p/chromium/issues/detail?id=754282#c2

**Comment by adreporter** [comment] 2017-08-18 09:56
@jspenguin2017 Sorry for the off-topic. 
I'm using a 42'' TV as a monitor (so it's a high DPI device)
<img width="945" alt="przechwytywanie1" src="https://user-images.githubusercontent.com/18214146/29453885-84e8bfbe-840b-11e7-8abf-16d7dd8f8306.PNG">
Do you know when it will be fixed? Can you give me the link so I can follow the progress?

Last question
<img width="515" alt="przechwytywanie" src="https://user-images.githubusercontent.com/18214146/29453995-e52efc3a-840b-11e7-9a04-a7c0075bf276.PNG">
Is it possible to do something about it or Google decided the URL of Your Extension?

**Comment by jspenguin2017** [comment] 2017-08-18 13:39
It is confirmed to be a Chromium bug, you can track its progress here: https://bugs.chromium.org/p/chromium/issues/detail?id=747700

Google decides the URL.
