### ISSUE TITLE
aetv.com

### ISSUE THREAD

**Issue by jjosephcuc** [jspenguin2017/uBlockProtector#382] opened 2017-07-11 21:25 UTC

**Comment by jjosephcuc** [comment] 2017-07-11 21:26
Test Link: http://www.aetv.com/shows/live-pd/season-1/episode-50

Web page Screenshot: http://imgur.com/a/igNYM

Console: http://imgur.com/a/DlK3w

This worked approximately a week or so ago.  Since then they've changed something on their end to block uBlock.

Thanks!

**Comment by jspenguin2017** [comment] 2017-07-12 23:51
The link you provided requires an account. So I used another video that does not require that for the test. And it works for me. 
![image](https://user-images.githubusercontent.com/7283682/28144712-6bece1be-672a-11e7-8e60-bee214f5bf2e.png)

Try changing your configuration exactly like this, then turn on your other extensions one by one to see what is causing the problem. 
https://github.com/jspenguin2017/uBlockProtector/blob/master/Notes/Standard%20Configuration.MD

**Comment by uBlock-user** [comment] 2017-07-13 06:37
Duplicate of https://github.com/jspenguin2017/uBlockProtector/issues/304

**Comment by jspenguin2017** [comment] 2017-07-16 20:43
Closing due to lack of response.

**Closed by jspenguin2017** 2017-07-16 20:43 UTC
Labels: Cannot Reproduce
