### ISSUE TITLE
crockolinks.com, 1ink.cc, met.bz

### ISSUE THREAD

**Issue by version365** [jspenguin2017/uBlockProtector#844] opened 2018-02-06 21:07 UTC
### Test link (required): 

1.  `http://crockolinks.com/YrMT6r`
2.  `http://1ink.cc/o0DTB`
3.  `https://met.bz/VfKivut1gt`

### Explain what was not right (optional if obvious): 

I was hoping if these sites could be bypassed altogether (since these don't require captcha solving); like adf.ly and linkshrink.net

**Note:**  I posted this request on uAssets but it got closed. My mistake though.. I forgot that only timer boosting logic was ported to uAssets; the bypassing of ouo.io, linkshrink.net, shorte.st, adf.ly etc. is still being handled by NanoDefender.

**Comment by jspenguin2017** [comment] 2018-02-06 23:49
Sometimes reCAPTCHA can be hidden though. I'll have a look tomorrow.

**Comment by jspenguin2017** [comment] 2018-02-07 01:09
Well, you are right that they don't use reCAPTCHA, but it's just one click, so I'll say won't fix. 
The problem is that the fix achieve close to nothing and if they change something and the fix breaks and possibly break the site with it. 

I can add a script snippet that clicks on elements, but it's a bit more complicated than it sounds, as there isn't a clean way to know when is the right time to click.

**Closed** 2018-02-07 01:09 UTC
Labels: Won't Fix
