### ISSUE TITLE
rtl.be

### ISSUE THREAD

**Issue by ghajini** [jspenguin2017/uBlockProtector#421] opened 2017-07-23 18:56 UTC
### Test link (required): 
http://www.rtl.be/info/regions/flandre/les-militaires-s-arretent-au-drive-in-d-un-fast-food-apres-le-defile-du-21-juillet-une-commande-assez-particuliere-video--938315.aspx

### Screenshot of the web page (required): 
<details><summary>Screenshot:</summary>

http://prntscr.com/fzatiz
</details>

***Screenshot of the console (press `F12` to bring up the console) (required)***
<details><summary>Screenshot:</summary>

http://prntscr.com/fzau2t
http://prntscr.com/fzauaa
http://prntscr.com/fzaugy
http://prntscr.com/fzauqb
http://prntscr.com/fzauwg
</details>

***Add everything else that you believe to be useful below (optional)***

if its due to antiadblock or not,following stream under videos section is also hidden
ss=

<details><summary>Screenshot:</summary>

http://prntscr.com/fzawe6
</details>

**Comment by uBlock-user** [comment] 2017-07-23 19:58
Can't reproduce.

**Comment by uBlock-user** [comment] 2017-07-23 19:59
!()[https://i.gyazo.com/d90dd2b22c7f9cc84bf3a75f71992e6b.png]

**Comment by ghajini** [comment] 2017-07-23 20:11
did you have `videoplaza.tv` exception in your filters

possible code of antiadblock
http://www.rtl.be/videos/player/vp_embed.js

**Comment by jspenguin2017** [comment] 2017-07-23 20:31
Workaround: 
`@@||damoh.*^$media,domain=rtl.be`
You will see some ads.

**Comment by jspenguin2017** [comment] 2017-07-23 20:47
Seems to be `Ooyala AAB Plugin`, I guess just replace it with a neutralized version.

**Comment by jspenguin2017** [comment] 2017-07-23 21:19
I guess I'll just replace the configuration XHR.

**Comment by ghajini** [comment] 2017-07-23 21:41
I just noticed this problem posted by a user on chrome store in "user review section" about ublock protector extension
![img_20170724_030210](https://user-images.githubusercontent.com/20338483/28503096-9549eb64-701d-11e7-9456-e34be42de56f.JPG)

Thus I reported here,I want ublock protector perfect against adblock killers😎👮

**Comment by uBlock-user** [comment] 2017-07-24 02:37
If you're going to whitelist then whitelist  `@@||ooul.tv^$script,domain=rtl.be` you won't see any ads or anything and the video plays.

**Comment by jspenguin2017** [comment] 2017-12-09 23:56
broke

**Comment by jspenguin2017** [comment] 2017-12-16 03:11
Fixed in https://github.com/uBlockOrigin/uAssets/commit/24c76ed9db2c953e5a506a64ad037b02d6d3fae8

**Closed** 2017-12-16 03:12 UTC
Labels: Fixed
