### ISSUE TITLE
haaretz.co.il

### ISSUE THREAD

**Issue by timmyrs** [jspenguin2017/uBlockProtector#1067] opened 2019-06-10 22:14 UTC
https://www.haaretz.co.il/science/.premium-1.7340086

detects uBlock Origin and redirects to

https://www.haaretz.co.il/hblocked?returnTo=https%3A%2F%2Fwww.haaretz.co.il%2Fscience%2F.premium-1.7340086

**Comment by jspenguin2017** [comment] 2019-06-11 01:29
Works fine with the Hebrew regional filters enabled.

**Comment by llacb47** [comment] 2019-06-11 01:30
Couldn't reproduce until I disabled [Easylist Hebrew.](https://github.com/easylist/EasyListHebrew) Try these rules from there:
```haaretz.co.il##+js(addEventListener-defuser.js, scroll)
haaretz.co.il##+js(set-constant.js, showAds, true)
```
I suppose that's where those filters belong, and not in the main nano filters though.

**Comment by jspenguin2017** [comment] 2019-06-11 01:33
Yes, if it's fixed in regional filters, it won't be fixed again in Nano filters.

**Closed by jspenguin2017** 2019-06-11 01:33 UTC
Labels: Cannot Reproduce
