### ISSUE TITLE
Deactivate logs

### ISSUE THREAD

**Issue by paveltrufi** [jspenguin2017/uBlockProtector#892] opened 2018-03-23 11:00 UTC
```
[Nano] Nano Defender Activated :: 127.0.0.1
3-content-rules-1-common.js:56 [Nano] Excluded :: All Generically Applied Solutions
```
It's pretty annoying to have your console.logs flying around mine. Could you, either suppress them or provide an option in the extensions so we can deactivate them?

Thank you in advance.

**Comment by jspenguin2017** [comment] 2018-03-23 12:34
Duplicate of https://github.com/jspenguin2017/uBlockProtector/issues/735

**Closed by jspenguin2017** 2018-03-23 12:34 UTC
Labels: Duplicate
