### ISSUE TITLE
film.wp.pl

### ISSUE THREAD

**Issue by HateAds** [jspenguin2017/uBlockProtector#334] opened 2017-06-28 15:17 UTC
Test link: https://film.wp.pl/charlie-sheen-bliski-bankructwa-gwiazdor-wyprzedaje-pamiatki-aby-splacic-pozwy-sadowe-6138451472139905a

Screenshot of the web page: 
![ads](https://user-images.githubusercontent.com/29756590/27644528-1723b6f0-5c24-11e7-9f01-bb98518ab7c0.png)

Screenshot of the console:
![console](https://user-images.githubusercontent.com/29756590/27645040-704b88ce-5c25-11e7-9a46-111bcc91d025.png)

**Comment by uBlock-user** [comment] 2017-06-28 15:48
Same as https://github.com/jspenguin2017/uBlockProtector/issues/333

All .pl domains as such are using the same anti adblock script apparently.

**Comment by HateAds** [comment] 2017-06-28 18:44
Thanks for the fast fix, but now I have another problem. I can't start the video. 
Do you have the same problem as me?

**Comment by jspenguin2017** [comment] 2017-06-28 19:15
Works for me... 
![image](https://user-images.githubusercontent.com/7283682/27655813-e2c05096-5c03-11e7-87d8-cff0d25abeac.png)

**Comment by xxcriticxx** [comment] 2017-06-28 19:54
@HateAds press ctrl+F5 few times it will work

**Comment by jspenguin2017** [comment] 2017-06-28 19:57
The extension does not have race condition, it works consistently for me.

**Comment by xxcriticxx** [comment] 2017-06-28 20:05
o ye i forgot this extension now not script sorry

**Comment by adreporter** [comment] 2017-06-29 00:48
@HateAds @jspenguin2017 I have the same problem: I can't start the video.

**Comment by jspenguin2017** [comment] 2017-06-29 00:50
@adreporter The solution does not apply across the whole `wp.pl` network, you need to provide links to videos that does not work.

**Comment by xxcriticxx** [comment] 2017-06-29 01:18
i make something happen

**Comment by xxcriticxx** [comment] 2017-06-29 01:24
this to start but there is more 

wiadomosci.wp.pl
sportowefakty.wp.pl
money.pl
kobieta.wp.pl
gwiazdy.wp.pl
portal.abczdrowie.pl
parenting.pl
moto.wp.pl
tech.wp.pl
gry.wp.pl
opinie.wp.pl
turystyka.wp.pl

**Comment by jspenguin2017** [comment] 2017-06-29 01:31
I'm sure most of them are already patched. If you have a domain that does actually not work on the supported setup, post a link to a *test article*.

**Comment by xxcriticxx** [comment] 2017-06-29 01:34
here are some more 

pudelek.tv
pudelek.tv
pudelekx.pl

**Comment by uBlock-user** [comment] 2017-06-29 06:18
If the video doesn't start then it's a filter list issue something is being blocked on your end.

**Comment by xxcriticxx** [comment] 2017-06-29 11:12
@uBlock-user wp.pl is a bitch its big and shit changes daily

**Comment by uBlock-user** [comment] 2017-06-29 11:23
Regardless of how big it is which is irrelevant to the video being not able to play at your end, it works fine for me. Also a cosmetic filter can't cause such a thing.

**Comment by xxcriticxx** [comment] 2017-06-29 13:43
bad cookies will cause such thing

**Comment by jspenguin2017** [comment] 2017-07-01 02:45
I cleaned up the domain list of non-ideal solutions, let me know if something is not right.

**Comment by xxcriticxx** [comment] 2017-07-01 10:12
please add wp.tv

http://wp.tv/i,prognoza-pogody-na-17-lutego,mid,1997971,cid,2303759,klip.html?ticaid=6196d4

![capture](https://user-images.githubusercontent.com/15007183/27761135-4cfc981c-5e24-11e7-9d5c-ef8232cf8e54.PNG)

**Comment by jspenguin2017** [comment] 2017-07-01 13:52
@xxcriticxx Can't reproduce: 
![image](https://user-images.githubusercontent.com/7283682/27762581-3e8bd0a0-5e32-11e7-9437-2ba0478d9c88.png)

**Comment by xxcriticxx** [comment] 2017-07-01 14:05
just add the domain 

i got it to works here now i clear cookies cache browsing history and everything else 

thx as always

**Comment by jspenguin2017** [comment] 2017-07-01 14:08
No.

**Comment by xxcriticxx** [comment] 2017-07-01 14:32
no problem thx for your great work

**Comment by jspenguin2017** [comment] 2017-07-03 17:04
They changed something again...

**Comment by xxcriticxx** [comment] 2017-07-03 17:11
they always keep changing stuff

**Comment by jspenguin2017** [comment] 2017-07-04 00:09
Still works. Closing.

**Closed by jspenguin2017** 2017-07-04 00:09 UTC
Labels: Fixed, Test In Progress
