### ISSUE TITLE
yiv.com

### ISSUE THREAD

**Issue by adreporter** [jspenguin2017/uBlockProtector#350] opened 2017-07-07 13:49 UTC
Test link: https://www.yiv.com/Stickman-Archer-Online

Screenshot of the web page:
<img width="864" alt="cattura" src="https://user-images.githubusercontent.com/18214146/27960428-8f8ed01c-632b-11e7-990d-71f315eaf5ab.PNG">

Screenshot of the console:
<img width="584" alt="cattura2" src="https://user-images.githubusercontent.com/18214146/27960441-987e4176-632b-11e7-8d76-8b0c453924b7.PNG">

If I refresh the page, the anti-adblock message disappears, but the game doesn't load.

**Comment by uBlock-user** [comment] 2017-07-07 13:57
`yiv.com##script:inject(abort-on-property-read.js, onload)`

**Comment by jspenguin2017** [comment] 2017-07-07 14:13
Eh, this is going to be a tough one... 
`@@||googleapis.com/js/sdkloader/ima3.js$script,domain=www.yiv.com`

**Comment by uBlock-user** [comment] 2017-07-07 14:16
Which part ?

**Comment by jspenguin2017** [comment] 2017-07-07 14:17
Got to whitelist Google API or the game won't load.

**Comment by uBlock-user** [comment] 2017-07-07 14:18
It's cookie based. Better yet just set the cookie `AdBlockMessage` to `yes` instead of whitelisting.

**Comment by jspenguin2017** [comment] 2017-07-07 14:20
I'm not talking about the block screen, I mean the game itself, does it load?

**Comment by uBlock-user** [comment] 2017-07-07 14:22
I see. Even after whitelisting, the game doesn't load.

**Comment by uBlock-user** [comment] 2017-07-07 14:24
Does this appear - https://www.yiv.com/games/Penalty-Mania/index.html ?

**Comment by uBlock-user** [comment] 2017-07-07 14:27
Nevermind you will have to whitelist `imasdk.googleapis.com` as it's part of the HTML5 games.

**Comment by uBlock-user** [comment] 2017-07-07 14:31
For Anti adblock use  - `yiv.com##script:inject(setTimeout-defuser.js, ad)`

**Comment by uBlock-user** [comment] 2017-07-07 14:33
![](https://i.gyazo.com/77c1cfb9a2b1834bb0b529359e46b9b5.png)

**Comment by uBlock-user** [comment] 2017-07-07 14:36
Add these two also

```
yiv.com###LeftAdDiv
yiv.com###RightAdDiv
```

**Comment by jspenguin2017** [comment] 2017-07-07 14:39
I'm not going to directly whitelist IMA SDK, I'll loopback it, there are a ton of whitelist for that SDK inherited from AAK, it's a good time to clean them up. (FYI, IMA = Interactive Media Ads)

**Comment by uBlock-user** [comment] 2017-07-07 14:43
Yes I'm aware what it is, but not whitelisting it doesn't initialize, so if you can patch it without the requirement of white-listing that domain that would be great.

**Comment by jspenguin2017** [comment] 2017-07-07 14:50
Huh, there aren't that many actually... Only 2 or 3...

**Comment by ghajini** [comment] 2017-07-07 14:54
What is loopback, is it same to whitelist?

**Comment by jspenguin2017** [comment] 2017-07-07 14:56
No, it's like a custom redirect. The payload can be generated on the fly or pre-calculated.

**Comment by jspenguin2017** [comment] 2017-07-07 15:07
```
PS C:\Users\Alpha\Desktop\Temp Files> node temp
google_js_reporting_queue
gteh
Goog_AdSense_Lidar_sendVastEvent
Goog_AdSense_Lidar_getViewability
Goog_AdSense_Lidar_getUrlSignalsArray
Goog_AdSense_Lidar_getUrlSignalsList
ima
onYouTubeIframeAPIReady
google
```

Why I feel defining `google` is enough...

**Comment by jspenguin2017** [comment] 2017-07-07 16:12
Actually, there are quite a bit of whitelists of IMA SDK in EasyList...

**Comment by jspenguin2017** [comment] 2017-07-07 17:05
![image](https://user-images.githubusercontent.com/7283682/27968414-20a782f6-6304-11e7-96e7-03c577541f3a.png)
![image](https://user-images.githubusercontent.com/7283682/27968440-3b3037bc-6304-11e7-8b81-17f9e9aea6b8.png)
Life is hard

**Comment by jspenguin2017** [comment] 2017-07-07 17:20
I will have the SDK to always dispatch AD_ERROR, since with whitelisting, the SDK will always error out.

**Comment by jspenguin2017** [comment] 2017-07-07 17:39
The empty ads divs are to be handled by EasyList.

**Comment by jspenguin2017** [comment] 2017-07-07 17:40
Commits: 
https://github.com/jspenguin2017/uBlockProtector/commit/fef13402e7096a34bbac117892abd4e9ec0cc7f2
https://github.com/jspenguin2017/uBlockProtector/commit/7a6b71cc79cc98cff5e03ea99c06fdeb336b57b1
https://github.com/jspenguin2017/uBlockProtector/commit/91d3a1235b8ca99a42eb7b493811b20cd8d61a50

**Comment by jspenguin2017** [comment] 2017-07-07 17:41
The new loopback logic will apply to **ALL** IMA SDK requests, Let's test!
`baltimoresun.com|boston.com|calgaryherald.com|capitalgazette.com|carrollcountytimes.com|chicagotribune.com|chroniclelive.co.uk|citypaper.com|cnet.com|courant.com|dailypress.com|deathandtaxesmag.com|edmontonjournal.com|edmunds.com|everquest.allakhazam.com|financialpost.com|gofugyourself.com|hearthhead.com|ibtimes.com|infinitiev.com|latimes.com|leaderpost.com|lifewire.com|lolking.net|mcall.com|metacritic.com|montrealgazette.com|msn.com|nasdaq.com|nationalpost.com|orlandosentinel.com|ottawacitizen.com|pcmag.com|ranker.com|sandiegouniontribune.com|saveur.com|sherdog.com|spin.com|sporcle.com|stereogum.com|sun-sentinel.com|thebalance.com|theprovince.com|thespruce.com|thestarphoenix.com|thoughtco.com|timeanddate.com|tmn.today|torontosun.com|tvguide.com|twincities.com|vagazette.com|vancouversun.com|vibe.com|windsorstar.com|wowhead.com|www.ign.com|zam.com`
`allcatvideos.com|audiomack.com|bloomberg.com|cbc.ca|cbsnews.com|cbssports.com|cnet.com|complex.com|gamejolt.com|news.sky.com|play.ludigames.com|player.performgroup.com|rumble.com|snopes.com|theverge.com|video.foxbusiness.com|video.foxnews.com|vidyomani.com`

**Comment by jspenguin2017** [comment] 2017-07-07 18:07
Seems to work correctly for me. Let me know if it breaks. 
Some website dump the error log, kind of annoying as the error message is like 50 lines... Well, better than getting filled by blocked subrequests.

**Comment by uBlock-user** [comment] 2017-07-07 18:19
Do you receive any redirect failed warnings from Chrome when testing ?

**Comment by jspenguin2017** [comment] 2017-07-07 18:20
Nope.

**Comment by uBlock-user** [comment] 2017-07-07 18:24
Well did you test it on this case itself ? The game doesn't initialize and remains broken

**Comment by uBlock-user** [comment] 2017-07-07 18:26
![](https://i.gyazo.com/ab2e26989275f921e26ac4b6bc7d4a30.png)

**Comment by jspenguin2017** [comment] 2017-07-07 18:27
Did you update integration filters?

**Comment by uBlock-user** [comment] 2017-07-07 18:32
I updated the extension, anything else ?

**Comment by jspenguin2017** [comment] 2017-07-07 18:33
https://github.com/jspenguin2017/uBlockProtector/blob/master/List%20Compiler/List/Rules%20Part%201.txt#L4

**Comment by uBlock-user** [comment] 2017-07-07 18:49
Got it working finally!

**Comment by uBlock-user** [comment] 2017-07-07 18:50
You know you could just kill the `setTimeout` call instead of setting the cookie rather.

**Comment by uBlock-user** [comment] 2017-07-07 18:55
As for those 50 whitelists, some of them are redundant and not even needed as `imasdk.googleapis.com` doesn't even make any connections there.

**Comment by adreporter** [comment] 2017-07-07 19:20
@jspenguin2017 @uBlock-user 
> Seems to work correctly for me. Let me know if it breaks.
> Some websites dump the error event, kind of annoying as the error message is like 50 lines... Well, better than getting filled by blocked subrequests.

> Got it working finally!

Yes, it works. Thank you.

**Comment by jspenguin2017** [comment] 2017-07-07 19:23
This solution is generic, need to test on other websites too.

**Comment by adreporter** [comment] 2017-07-07 19:25
@jspenguin2017 On these, right?
<details>baltimoresun.com|boston.com|calgaryherald.com|capitalgazette.com|carrollcountytimes.com|chicagotribune.com|chroniclelive.co.uk|citypaper.com|cnet.com|courant.com|dailypress.com|deathandtaxesmag.com|edmontonjournal.com|edmunds.com|everquest.allakhazam.com|financialpost.com|gofugyourself.com|hearthhead.com|ibtimes.com|infinitiev.com|latimes.com|leaderpost.com|lifewire.com|lolking.net|mcall.com|metacritic.com|montrealgazette.com|msn.com|nasdaq.com|nationalpost.com|orlandosentinel.com|ottawacitizen.com|pcmag.com|ranker.com|sandiegouniontribune.com|saveur.com|sherdog.com|spin.com|sporcle.com|stereogum.com|sun-sentinel.com|thebalance.com|theprovince.com|thespruce.com|thestarphoenix.com|thoughtco.com|timeanddate.com|tmn.today|torontosun.com|tvguide.com|twincities.com|vagazette.com|vancouversun.com|vibe.com|windsorstar.com|wowhead.com|www.ign.com|zam.com
allcatvideos.com|audiomack.com|bloomberg.com|cbc.ca|cbsnews.com|cbssports.com|cnet.com|complex.com|gamejolt.com|news.sky.com|play.ludigames.com|player.performgroup.com|rumble.com|snopes.com|theverge.com|video.foxbusiness.com|video.foxnews.com|vidyomani.com

**Comment by jspenguin2017** [comment] 2017-07-07 19:30
These and any website that use IMA SDK. Need to test a substantial sample.

**Comment by adreporter** [comment] 2017-07-07 19:54
@jspenguin2017 Oh, I see. I would like to help you. I remember I wrote you in a comment I'm not an expert, well I'm a noob actually. All can I do is to see if there are some anti-adblock messages in those 73 websites you posted above. Do I have to check also the proper functionality of those websites?

**Comment by jspenguin2017** [comment] 2017-07-07 20:00
Yea, the key is proper functionality, the domain list I posted is not good. I'll use an automation script to filter them. Most of them doesn't even load the SDK.

**Comment by adreporter** [comment] 2017-07-07 20:14
If I understood right, I have to wait for a new domain list you'll post here and then check if anti-adblock messages appear on those websites in the list + proper functionality of those websites, right?

**Comment by uBlock-user** [comment] 2017-07-07 20:29
There you go - https://publicwww.com/websites/%22imasdk.googleapis.com%2Fjs%2Fsdkloader%2Fima3.js%22/

**Comment by adreporter** [comment] 2017-07-07 20:30
Oh look, only 6146 websites. Easy-peasy!

**Comment by jspenguin2017** [comment] 2017-07-07 20:31
![image](https://user-images.githubusercontent.com/7283682/27968440-3b3037bc-6304-11e7-8b81-17f9e9aea6b8.png)
6146 results...

I did a quick scrape of EasyList domains, none seems to be using it... Am I doing it wrong?

**Comment by jspenguin2017** [comment] 2017-07-07 20:33
OK, it is crashing on the second entry :'D

**Comment by adreporter** [comment] 2017-07-07 20:33
@jspenguin2017 @uBlock-user What's the plan now?

**Comment by jspenguin2017** [comment] 2017-07-07 20:34
I'll do it. It's a bit complex.

**Comment by uBlock-user** [comment] 2017-07-07 21:00
@jspenguin2017 Don't bother going beyond 1000, that should cover all the famous and most used one with the higher ranking in accordance to Alexa.

**Comment by jspenguin2017** [comment] 2017-07-07 21:01
I'll only check like 50

**Comment by uBlock-user** [comment] 2017-07-07 21:01
@adreporter He will have to do the heavy lifting from here on I guess.

**Comment by jspenguin2017** [comment] 2017-07-07 21:04
OK, fixed two bugs.

**Comment by jspenguin2017** [comment] 2017-07-07 21:08
OK, just found some extra work... #352

**Comment by jspenguin2017** [comment] 2017-07-07 21:32
Fixed 3 bugs. Checked 60 websites, seems to be working properly.

**Comment by adreporter** [comment] 2017-07-07 21:32
Good job.

**Comment by adreporter** [comment] 2017-07-07 21:44
@jspenguin2017 Can I close the issue?

**Comment by jspenguin2017** [comment] 2017-07-07 21:45
Yep, let's close it.

**Closed by jspenguin2017** 2017-07-07 21:45 UTC
Labels: Fixed

**Comment by adreporter** [comment] 2017-07-09 10:39
@jspenguin2017 

> Yea, the key is proper functionality

Unfortunately I found a website in the list you posted above that doesn't work properly with the uBlock Protector Extension enabled:
http://www.cbsnews.com/news/voter-fraud-case-tied-to-iowan-woman-voting-for-trump-twice/
Scroll down and click play on this video:
<img width="288" alt="video" src="https://user-images.githubusercontent.com/18214146/27993102-c10644e0-64a2-11e7-9ec9-cd8bc7554eb3.PNG">
After a few seconds you'll see the video doesn't load:
<img width="751" alt="cattura11" src="https://user-images.githubusercontent.com/18214146/27993116-3c5f5f3c-64a3-11e7-9357-3de527ae0765.PNG">
I'm getting a lot of errors and warnings in the console (the count doesn't stop):
<img width="535" alt="cattura3333" src="https://user-images.githubusercontent.com/18214146/27993131-975a8358-64a3-11e7-8a58-d084fcac9b8f.PNG">
Could you please have a look?

**Comment by jspenguin2017** [comment] 2017-07-09 14:47
Yep, I'll fix it. Whitelisted while I work on it.

**Comment by jspenguin2017** [comment] 2017-07-09 18:34
I think their website is broken, as it requests non-existing files. The request is somehow canceled by the original SDK... Let me know if you found other website with similar issue.

**Comment by adreporter** [comment] 2017-08-31 13:36
@jspenguin2017 
https://www.yiv.com/Stickman-Archer-Online
The game doesn't load anymore.

**Comment by adreporter** [comment] 2017-08-31 13:39
@jspenguin2017 
https://www.yiv.com/Stickman-Archer-Online
The game doesn't load anymore.
Can you fix it?

**Comment by adreporter** [comment] 2017-09-02 08:38
@jspenguin2017 
https://www.yiv.com/Stickman-Archer-Online
Please scroll down and play the video, after 10 seconds of playback you'll notice this:
<img width="621" alt="przechwytywanie" src="https://user-images.githubusercontent.com/18214146/29994229-d9cd5b46-8fca-11e7-84f3-7696859d5b89.PNG">
Can you fix it?

**Comment by jspenguin2017** [comment] 2017-09-02 13:00
Can't reproduce first one: 
![image](https://user-images.githubusercontent.com/7283682/29995680-573ca4ac-8fac-11e7-86aa-ead6fdc5db15.png)

**Comment by adreporter** [comment] 2017-09-02 13:34
@jspenguin2017 After clicking on the yellow button, don't do anything for 10-15 seconds, the anti-adblock message will come out.

**Comment by jspenguin2017** [comment] 2017-09-02 13:50
Nope, still can't reproduce. 
![image](https://user-images.githubusercontent.com/7283682/29995993-5a2d975a-8fb3-11e7-8ade-d09daa214414.png)

**Comment by jspenguin2017** [comment] 2018-11-18 23:42
https://github.com/NanoMeow/QuickReports/issues/340

**Comment by jspenguin2017** [comment] 2018-11-18 23:42
Please stop digging up old threads. Open new issues in NanoFilters repository or use the Quick Issue Reporter.
