### ISSUE TITLE
animeforce.org

### ISSUE THREAD

**Issue by xlollomanx** [jspenguin2017/uBlockProtector#455] opened 2017-08-06 21:08 UTC
Test link (required) :http://www.animeforce.org/ds16.php?file=www.wagnaria.org/DDL/ANIME/WitchCraftWorks/WitchCraftWorks_Ep_11_SUB_ITA.mp4

Screenshot of the web page (required): https://prnt.sc/g55l5t

Screenshot of the console (press F12 to bring up the console) (required): https://prnt.sc/g55nc3

Add everything else that you believe to be useful below (optional): This is a streaming site of anime. I'm using it for years but now it give this error. Thanks!

edit: edited console screenshoot. Not catched all the console errors.

**Comment by jspenguin2017** [comment] 2017-08-06 21:22
Can't reproduce.

**Comment by jspenguin2017** [comment] 2017-08-06 21:24
![image](https://user-images.githubusercontent.com/7283682/29007203-4d2aa97e-7abb-11e7-9b83-d88d507ac98d.png)

**Comment by uBlock-user** [comment] 2017-08-06 21:35
Can't reproduce.

**Comment by uBlock-user** [comment] 2017-08-06 21:36
You probably didn''t install the extension, I can't see any generic notice about Antiblock.org v2 in the console in the picture.

**Comment by uBlock-user** [comment] 2017-08-06 21:36
Still right click doesn't work and needs to be patched.

**Comment by jspenguin2017** [comment] 2017-08-06 21:41
This fixed popup and right click.

**Comment by xlollomanx** [comment] 2017-08-07 07:47
@uBlock-user The extension was installed, but maybe happened something wrong, because today I rebooted pc and it worked fine. Sorry this waste of time.

**Comment by uBlock-user** [comment] 2017-08-07 09:10
Something on your side, perhaps. Otherwise antiblock v2 gets caught in generic buster.

**Comment by xlollomanx** [comment] 2017-08-07 09:21
@uBlock-user Yes, sure on my side. Now it's working perfectly.

**Comment by jspenguin2017** [comment] 2017-08-07 13:54
It could be your browser pulled the bad version that choked on the broken hash algorithm. 
I have a CI script to prevent that from happening again. Closing.

**Closed by jspenguin2017** 2017-08-07 13:54 UTC
Labels: Cannot Reproduce
