### ISSUE TITLE
di.fm

### ISSUE THREAD

**Issue by mooop12** [jspenguin2017/uBlockProtector#510] opened 2017-08-23 18:06 UTC
### Test link (required): 
https://www.di.fm/ (any station, probably needs to be logged in to hear the ads)

### Screenshot of the web page (required): 

http://i.imgur.com/Fr8ATOP.png

### Screenshot of the console (press `F12` to bring up the console) (required): 

http://i.imgur.com/TO78Sq2.png
http://i.imgur.com/Gb0QpH3.png

### Add everything else that you believe to be useful below (optional): 
You can see in the logs the name of the anti-adblock addon they are using: https://github.com/sitexw/FuckAdBlock

**Comment by jspenguin2017** [comment] 2017-08-23 18:19
How do you reproduce it? Do you have to listen for a while?

**Comment by uBlock-user** [comment] 2017-08-23 18:22
Can't reproduce.

If it's happening on a specific link, post that link here!

**Comment by mooop12** [comment] 2017-08-23 18:23
Sorry, forgot to mention that. Yes, though I don't know the exact interval. You should hear the ads in the first 30 minutes of listening when logged in. There seems to be a kind of trial when you're not logged in, I'm not sure if they play the ads then.

**Comment by uBlock-user** [comment] 2017-08-23 18:27
![](https://i.gyazo.com/5358eb8bf6c887eeec97bd982b45bada.png)

FuckAdblock is patched already.

**Comment by mooop12** [comment] 2017-08-23 18:33
I think you need to listen a little longer than 5 minutes. Maybe they also use something other than FuckAdblock. In the logs I sent (second screenshot) you can see at timestamp 19:56:34.730 they detect the adblock and are redirecting to an adblock wall.

**Comment by uBlock-user** [comment] 2017-08-23 18:34
https://www.di.fm/search/channels?q=Progressive&page=1

Is the second one the Progressive one ?

**Comment by mooop12** [comment] 2017-08-23 18:34
Yes.

**Comment by uBlock-user** [comment] 2017-08-23 18:38
https://www.di.fm/assets/application-007986938e0ac35a55d99243e2d2c444.js

https://www.di.fm/assets/application-007986938e0ac35a55d99243e2d2c444.js

XHR - https://www.di.fm/_papi/v1/di/adrulesets/webplayer?country_code=IN

Those are the traces of midroll ads I have found.

**Comment by Zhangsun321** [comment] 2017-08-23 18:57
hey moop
ill show you how to get di.fm comerical free!
https://friezy.ru/en/rt

you have a few choices... they have an apk you candownload to your mobile device..
OR for pc's they have.... you can plug their ripped stream url
OR
just download a new playlist everyweek with the 'free 7 day trial'

**Comment by jspenguin2017** [comment] 2017-08-23 19:05
So what's the problem exactly? The audio tracks have ads or it shows the anti-adblock screen?

**Comment by uBlock-user** [comment] 2017-08-23 19:07
I guess he's facing both. I can't reproduce any so far.

**Comment by mooop12** [comment] 2017-08-23 19:08
Previously with an adblock there was just a 5 second announcement of ads, with no actual ads playing. Recently they changed something, and now when it is time to play the ads the stream just stops and an anti-adblock screen is shown.

@Zhangsun321 I guess that's one way out of it, though you loose the track progress, easy station changing etc. Thanks nonetheless.

**Comment by jspenguin2017** [comment] 2017-08-23 19:10
I think nooping the ads track should work.

**Comment by Zhangsun321** [comment] 2017-08-23 19:12
hey @mooop12 try this
https://hqradio.ru/di/

**Comment by jspenguin2017** [comment] 2017-08-24 16:59
This one is really hard to reproduce, we need someone who regularly use this website to debug it.

**Comment by mooop12** [comment] 2017-08-24 17:58
I can do that - just tell me what do you need.

**Comment by jspenguin2017** [comment] 2017-08-24 18:44
Can you try to find out which URL serves the audio ads and noop it? 
Also, is there a flag in `localStorage` that is linked to the block screen?

**Comment by mooop12** [comment] 2017-08-24 18:49
I'm not sure what nooping means? You mean to just block it in the adblock? Wouldn't that just trigger the anti-adblock wall like it does now?

**Comment by jspenguin2017** [comment] 2017-08-24 19:14
So first find the ads server from logger, then `$redirect` it to `noopmp3-0.1s`.

**Comment by mooop12** [comment] 2017-08-28 15:28
These are the rules that work for me: 

```
||gvt1.com/*/gfp_video_ads/*/file.webm*$media,redirect=noopmp3-0.1s,domain=di.fm
@@||pubads.g.doubleclick.net/gampad/ads^$xmlhttprequest,domain=di.fm
@@||di.deliveryengine.adswizz.com^$xmlhttprequest,domain=di.fm
```

I'm not a big fan of adding these ad domains to allowed exceptions, but I know of no other way to modify an Angular module on the fly, which is what they are using when serving the ads and detecting the adblock.

**Comment by jspenguin2017** [comment] 2017-08-28 15:33
XHR can be modifies with `a.replace`. Although I would need a dump to create the rule. Marking as workaround.

**Comment by jspenguin2017** [comment] 2017-08-28 15:42
I don't really see the requests in logger, I guess it is only reproducible with an account. Can you provide a test account? 
You can send it to me privately by opening a confidential issue in GitLab or sending it to https://jspenguin.com/PrivateMessage/ with reference Issue 510.

**Comment by adreporter** [comment] 2017-08-28 16:27
> You can send it to me privately by opening a confidential issue in GitLab or sending it to https://jspenguin.com/PrivateMessage/ with reference Issue 510.

Sent.

**Comment by mooop12** [comment] 2017-08-28 16:32
Here's a uBlock log for a single ad "loop" if that will help:

```
18:13:49	@@||di.deliveryengine.adswizz.com^$xmlhttprequest,domain=di.fm	++	xhr	https://di.deliveryengine.adswizz.com/www/delivery/swfIndex.php?zone_alias=%5B%7Bza%3ADImidroll%2Cn%3A8%7D%5D&companion_zones_alias=Display&duration=245000&listenerId=&protocolVersion=2.0-compliant&reqType=AdsSetup&aw_0_azn.pgenre=Electronic&cb=1800269430
18:13:49	@@||pubads.g.doubleclick.net/gampad/ads^$xmlhttprequest,domain=di.fm	++	xhr	https://pubads.g.doubleclick.net/gampad/ads?sz=300x250&ciu_szs=300x250&iu=/1009675/radio_di_progressive&url=https%3A%2F%2Fwww.di.fm%2F&correlator=1503936829692&description_url=%5Bdescription_url%5D&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1
18:13:49	@@||di.deliveryengine.adswizz.com^$xmlhttprequest,domain=di.fm	++	xhr	https://di.deliveryengine.adswizz.com/www/delivery/swfIndex.php?zone_alias=%5B%7Bza%3ADImidroll%2Cn%3A8%7D%5D&companion_zones_alias=Display&duration=245000&listenerId=&protocolVersion=2.0-compliant&reqType=AdsSetup&aw_0_azn.pgenre=Electronic&cb=469573735
18:13:49	@@||pubads.g.doubleclick.net/gampad/ads^$xmlhttprequest,domain=di.fm	++	xhr	https://pubads.g.doubleclick.net/gampad/ads?sz=300x250&ciu_szs=300x250&iu=/1009675/radio_di_progressive&url=https%3A%2F%2Fwww.di.fm%2F&correlator=1503936829353&description_url=%5Bdescription_url%5D&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1
18:13:49	noopmp3-0.1s	<<	media	https://redirector.gvt1.com/videoplayback/id/0e5ce236caf6b42f/itag/43/source/gfp_video_ads/requiressl/yes/acao/yes/mime/video%2Fwebm/ip/0.0.0.0/ipbits/0/expire/1503958429/sparams/ip,ipbits,expire,id,itag,source,requiressl,acao,mime/signature/06008EE71D9AB1245FBF3BEE0A5026EF248FE6BA.2BC74F9C2B1B954E6D51977DEFC58E0E529BDADF/key/ck2/file/file.webm
18:13:49	_video_ads/	--	media	https://redirector.gvt1.com/videoplayback/id/0e5ce236caf6b42f/itag/43/source/gfp_video_ads/requiressl/yes/acao/yes/mime/video%2Fwebm/ip/0.0.0.0/ipbits/0/expire/1503958429/sparams/ip,ipbits,expire,id,itag,source,requiressl,acao,mime/signature/06008EE71D9AB1245FBF3BEE0A5026EF248FE6BA.2BC74F9C2B1B954E6D51977DEFC58E0E529BDADF/key/ck2/file/file.webm
18:13:48	@@||pubads.g.doubleclick.net/gampad/ads^$xmlhttprequest,domain=di.fm	++	xhr	https://pubads.g.doubleclick.net/gampad/ads?sz=300x250&ciu_szs=300x250&iu=/1009675/radio_di_progressive&url=https%3A%2F%2Fwww.di.fm%2F&correlator=1503936828984&description_url=%5Bdescription_url%5D&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1
```

**Comment by jspenguin2017** [comment] 2017-08-28 17:20
Dump: https://pastebin.com/PjVJcgif

**Comment by jspenguin2017** [comment] 2017-08-28 17:29
I'm testing my solution. 
```JavaScript
    if (a.domCmp(["di.fm"])) {
        a.loopback((ignored, url) => {
            //=====Debug Only=====
            window.console.log(url);
            //=====Debug Only=====
            if (url.startsWith("https://pubads.g.doubleclick.net/")) {
                return `
<?xml version="1.0" encoding="UTF-8"?>
<VAST xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vast.xsd" version="3.0">
</VAST>
`;
            } else if (url.startsWith("https://di.deliveryengine.adswizz.com/")) {
                return `
<?xml version="1.0" encoding="UTF-8"?>
<VAST version="2.0"/>
`;
            } else {
                return null;
            }
        });
    }
```

It is available in debug mode of Extension.

**Comment by jspenguin2017** [comment] 2017-08-28 17:42
Yep, it does work. 
Can you update Extension to 11.166 and test it out to make sure? Those white lists can be removed.

**Comment by mooop12** [comment] 2017-08-28 18:49
It works, although it's throwing errors about not being able to parse the string your returning. Is it supposed to be doing that?

![screenshot_20170828_204752](https://user-images.githubusercontent.com/20934112/29788293-58116200-8c32-11e7-8ce3-7483b0438820.png)

**Comment by jspenguin2017** [comment] 2017-08-28 18:57
Not really, I didn't look into it since it worked, there might be something wrong about the payload I gave to it.

**Comment by jspenguin2017** [comment] 2017-08-28 18:58
This is the current payload: 
```XML

<?xml version="1.0" encoding="UTF-8"?>
<VAST xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vast.xsd" version="3.0">
</VAST>

```

**Closed** 2017-08-29 13:08 UTC
Labels: Account Required, Fixed
