### ISSUE TITLE
przegladsportowy.pl

### ISSUE THREAD

**Issue by Tasiorsa** [jspenguin2017/uBlockProtector#785] opened 2018-01-04 17:11 UTC
### Test link (required): 
http://www.przegladsportowy.pl/

### Screenshot of the web page (including address bar and extension icons) (required): 

http://i64.tinypic.com/2q37oqp.jpg

### Screenshot of the console (press `F12` to bring up the console) (required): 

http://i63.tinypic.com/hrad7d.png

### Environment (Required): 

- Operating System and Version:  Win 7 Pro
- Browser and Version: Firefox 57.0.3 x64
- Adblocker and Version:  Nano Adblocker 1.0.23

### Explain what was not right (optional if obvious): 
Adblock Detected - Please Disable and reload site

**Comment by jspenguin2017** [comment] 2018-01-04 17:48
Reproduced if polish filters activated.

**Comment by jspenguin2017** [comment] 2018-01-04 17:50
@okiehsch

**Comment by Tasiorsa** [comment] 2018-01-04 18:04
All polish filters are activated:
http://i68.tinypic.com/2ywbbeu.png

**Comment by okiehsch** [comment] 2018-01-04 19:42
Hm, I can only reproduce with Chrome, site works fine with Firefox on my end, I have the polish filter lists enabled, anyway
`przegladsportowy.pl##script:inject(abort-current-inline-script.js, $onet, adblock-detect)`
fixes the issue with Chrome, I would need to know if it also works with Firefox.

**Comment by jspenguin2017** [comment] 2018-01-04 19:54
Confirmed works. 

<details>

![image](https://user-images.githubusercontent.com/7283682/34581593-4658691a-f14e-11e7-8f69-c8929744c140.png)
![image](https://user-images.githubusercontent.com/7283682/34581612-545a80ca-f14e-11e7-8fd3-f042b26ab62f.png)

</details>

**Comment by jspenguin2017** [comment] 2018-01-04 20:00
Inline script execution cancelling only works in Chromium (and Edge), I added a rule to Nano Defender as a backup because `textContent` is sometimes bugged for long scripts.

**Comment by Tasiorsa** [comment] 2018-01-04 20:10
Works for me :) Thanks!

**Comment by jspenguin2017** [comment] 2018-01-04 20:31
Landed in uAssets, closing.

**Closed by jspenguin2017** 2018-01-04 20:31 UTC
Labels: Work In Progress

**Comment by okiehsch** [comment] 2018-01-04 20:32
> How about `przegladsportowy.pl##^script#adsinit`?
Should work with Firefox, but I think filters that work with both Chrome and Firefox should have priority.

**Comment by jspenguin2017** [comment] 2018-01-04 20:42
`abort-current-inline-script.js` doesn't always work on Chrome due to a weird bug (over-optimization) when you have DevTools closed. 
It's more reliable to remove the script by ID.

**Comment by okiehsch** [comment] 2018-01-04 20:48
> It's more reliable to remove the script by ID.

I totally agree with you and as soon as Chrome supports uBO's  HTML filters, I will use them and replace
old `abort-current-inline-script.js` filters if possible.

**Comment by jspenguin2017** [comment] 2018-01-04 20:53
It looks like gorhill won't implement it unless Chrome gets an official API for it, although I would like to use an undocumented behavior to our advantage. (Mutation observer can cancel script execution)

**Comment by Tasiorsa** [comment] 2018-01-04 21:47
Again same problem on Firefox :(

**Comment by jspenguin2017** [comment] 2018-01-04 23:18
It's not that reliable, I'll roll out a fix in Nano Defender.

**Comment by jspenguin2017** [comment] 2018-01-04 23:27
Fixed in 13.17, it can take a few minutes to get pass review.

**Comment by Tasiorsa** [comment] 2018-01-05 05:11
With 13.17 everything looks OK :) Thanks again!
