### ISSUE TITLE
vipracing.tv

### ISSUE THREAD

**Issue by xlollomanx** [jspenguin2017/uBlockProtector#958] opened 2018-06-29 15:26 UTC
### Test link (required):
http://vipracing.tv/channel/canal-6

### Screenshot of the web page (including address bar and extension icons) (required): 
 https://prnt.sc/k0und9

### Screenshot of the console (press `F12` to bring up the console) (required):

I've already posted console in previous screenshot, but console doesn't show nothing. otherwise If I test with firefox the console show this: https://prnt.sc/k0upko

### Explain what was not right (optional if obvious):
There is a very annoying warning every time I open the site. I tried playing with chrome site permission, but I didn't solved anything. I don't know if this can be fixed by nano adblocker/defender, btw I just want say thank you.

### Reproduction steps (optional if trivial):
 Just open the page link

### Environment (Required):

- Operating System and Version: Windows 10 1803 build17134.137
- Browser and Version: Chrome 67.0.3396.99
- Adblocker and Version: Nano Adblocker 1.0.0.54/Nano Defender15.0.0.2

#### Your filter lists (Required): 
https://prnt.sc/kmzgcn

#### Your custom filters (Required if you have any):
```
! 7/04/2018, 14:08:15 http://vipracing.info/
vlive.pw/ad.html
vipracing.tv###addTop
vipracing.tv##.text-left.col-xs-12.col-sm-3
! 8/5/2018, 20:43:47 http://maxdeportv.net/
maxdeportv.net###adsdiv
maxdeportv.net###iframe1
maxdeportv.net##body > table:nth-of-type(1) > tbody
! 12/5/2018, 16:09:33 http://pasiondeportiva.me/
pasiondeportiva.me###addy_overlayer_content
pasiondeportiva.me###addy_overlayer
||ibrodsports.club/adsset/click.php$subdocument
```

### Add everything else that you believe to be useful below (optional):
My main browser is Chrome. I just posted firefox console because the chrome one is empty. Basically they share the same setup.

**Comment by mapx-** [comment] 2018-06-29 16:35
add
```
||storage.googleapis.com/wafscr/mp.min.js$script,domain=vipracing.tv
vipracing.tv##[href="http://www.tvbarata.club/"]
||tvbarata.club/ads/$subdocument
vipracing.tv##.rj-publi
```

**Comment by xlollomanx** [comment] 2018-06-29 17:15
@mapx- oh thank you! these filters seems work fine

**Comment by jspenguin2017** [comment] 2018-06-30 00:29
Did the rules land in uAssets?

**Comment by jspenguin2017** [comment] 2018-06-30 01:09
@okiehsch

**Comment by okiehsch** [comment] 2018-06-30 01:21
They did not,  mapx- probably thinks that this issue can be fixed without any extended syntax, which is correct.

**Comment by okiehsch** [comment] 2018-06-30 01:39
I actually get blocked by Google Safebrowsing on some subsites, for example 

![image](https://user-images.githubusercontent.com/16838044/42120164-f5b00294-7c16-11e8-975c-f5218a96f3db.png)

I will add a fix that blocks the potentially malicious requests and include mapx- filters.

**Comment by okiehsch** [comment] 2018-06-30 01:49
Fixed.

**Comment by xlollomanx** [comment] 2018-08-26 09:07
@jspenguin2017 @okiehsch  Sorry for re-open this but they added some invisible overlays over the videoplayer. That block you to access the player settings like audio. Test link: http://vipracing.tv/channel/canal-0

**Comment by jspenguin2017** [comment] 2018-08-26 15:54
Can't reproduce.

**Comment by xlollomanx** [comment] 2018-08-26 16:50
@jspenguin2017 I tried with other browser and pc: me too cannot reproduce this issue until I force filters update. I can remove this overlay only if I delete the code inside the red line: 
![ads2](https://user-images.githubusercontent.com/6764804/44630622-dfb5fa80-a960-11e8-8a04-582c05f04621.png)

**Comment by jspenguin2017** [comment] 2018-08-26 17:21
If you click the X button, it goes away. I'm not sure if this can be fixed in uBO. @okiehsch

**Comment by xlollomanx** [comment] 2018-08-26 17:22
@jspenguin2017 what X button? I can't see anything

**Comment by jspenguin2017** [comment] 2018-08-26 17:24
![image](https://user-images.githubusercontent.com/7283682/44630961-9fd02280-a922-11e8-9954-9b607a92bc90.png)

**Comment by okiehsch** [comment] 2018-08-26 17:26
No, best that can be done is disabling the popup that occurs if you click the "x", that has been fixed for `telerium-streams`, see https://github.com/uBlockOrigin/uAssets/commit/3e4c5a8de6d268355fb5f3da9ffc3fc96f2a9b44

**Closed** 2018-08-26 17:49 UTC
Labels: Fixed

**Comment by xlollomanx** [comment] 2018-08-26 18:42
umh...nothing on my side. maybe some of my filters hide it.

**Comment by xlollomanx** [comment] 2018-08-26 18:48
@jspenguin2017  @okiehsch thank you very much for your support. Works fine!

**Comment by xlollomanx** [comment] 2018-11-29 15:49
@jspenguin2017 @okiehsch @mapx- sorry for re-open this but seems something changed and now the adblocker is a bit too aggressive and with it enabled the video player isn't showing. With adblocker disabled I can see the streaming btw.

Test link: http://vipracing.tv/channel/canal-6

Console screenshot: https://prnt.sc/lokxf9

Filters enabled: https://prnt.sc/lokzm6

Custom filters:
 ||storage.googleapis.com/wafscr/mp.min.js$script,domain=vipracing.tv

**Comment by mapx-** [comment] 2018-11-29 17:02
fixed
