### ISSUE TITLE
eurogamer.net

### ISSUE THREAD

**Issue by Zhangsun321** [jspenguin2017/uBlockProtector#245] opened 2017-05-30 13:58 UTC
http://www.eurogamer.net/
just started anti ad block last night
chrome violent monkey ublock origin

**Comment by uBlock-user** [comment] 2017-05-30 14:03
`a.noAccess("stop");`

**Comment by uBlock-user** [comment] 2017-05-30 14:06
same as https://github.com/jspenguin2017/uBlockProtector/issues/85

**Comment by Zhangsun321** [comment] 2017-05-30 14:13
ok now.. i remember doing comicbook.com manually...
so i would put..
||eurogamer.net^$inline-script
||$third-party,domain=eurogamer.net
into my ublock whitelist...
yep.. seems to work as a temp fix.
till jspenguin does the update..

**Comment by uBlock-user** [comment] 2017-05-30 14:16
> so i would put..
||eurogamer.net^$inline-script

Using that filter might kill other website functionality, so it's advisable to only use it as a weapon of last resort.

**Comment by Zhangsun321** [comment] 2017-05-30 14:19
well your fix...   where do i put that into my ublock? or do i add it somewhere to my violent monkey?
im still learning... :)

**Comment by uBlock-user** [comment] 2017-05-30 14:20
Just wait for @jspenguin2017 to patch it in the Script or the List. We already have the solution.

**Comment by Zhangsun321** [comment] 2017-05-30 14:21
ok thank you two very much

**Comment by jspenguin2017** [comment] 2017-05-30 14:27
Thanks, I'll patch this.

**Comment by jspenguin2017** [comment] 2017-05-30 15:26
Looks like it is "pinging" `p.d.nn0e.com`, which is currently not blocked, but I'll roll out the patch anyway, since that domain looks pretty sketchy.

**Comment by uBlock-user** [comment] 2017-05-30 18:33
Just add - `||p.d.*.com/v$third-party,script` that will take care of any such new domains being added.

**Comment by jspenguin2017** [comment] 2017-05-30 18:35
@uBlock-user Yea... we probably should do this...

**Comment by jspenguin2017** [comment] 2017-05-30 18:44
@uBlock-user Are you sure `/v` is needed? 
![image](https://cloud.githubusercontent.com/assets/7283682/26599399/ba04c2e8-4535-11e7-86d0-6fcd85111cab.png)
This does not needs to be blocked? 
![image](https://cloud.githubusercontent.com/assets/7283682/26599411/c7d008ce-4535-11e7-9271-22b6a357ce2b.png)

**Comment by jspenguin2017** [comment] 2017-05-30 18:47
What? 
![image](https://cloud.githubusercontent.com/assets/7283682/26599561/3335d4ea-4536-11e7-8e3c-d534b5e4515a.png)

**Comment by jspenguin2017** [comment] 2017-05-30 18:51
OK, looks like Google is behind this. It has a valid HTTPS certificate and the domain is pointing to Google's IP. 
![image](https://cloud.githubusercontent.com/assets/7283682/26599678/abb92b10-4536-11e7-89cc-e81a88b61290.png)

**Comment by uBlock-user** [comment] 2017-05-30 19:39
Yes, all these domains are owned by Google for whatever purposes.

Secondly, the filter I posted is from uBlock Filters+ repo. I already have that so I suggested, you can remove /v or don't add at all and just add the domain, it will still do the job.

**Comment by jspenguin2017** [comment] 2017-05-30 21:32
I'm testing `||p.d.*.com^$third-party,script`, I'm feel it is a bit too aggressive... And what is telling us that Google won't change `d` to `c` or something...

**Comment by jspenguin2017** [comment] 2017-05-30 21:38
The certificate matches these domains: 

```
DNS Name=*.d.0emm.com
DNS Name=*.d.0emn.com
DNS Name=*.d.0enm.com
DNS Name=*.d.0fmm.com
DNS Name=*.d.0mme.com
DNS Name=*.d.1emn.com
DNS Name=*.d.1enm.com
DNS Name=*.d.2enm.com
DNS Name=*.d.3enm.com
DNS Name=*.d.4666.ch
DNS Name=*.d.8d1f.com
DNS Name=*.d.9emn.com
DNS Name=*.d.e0mn.com
DNS Name=*.d.em0n.com
DNS Name=*.d.emn0.com
DNS Name=*.d.m80fg.com
DNS Name=*.d.mdf91.com
DNS Name=*.d.mn0e.com
DNS Name=*.d.mpk01.com
DNS Name=*.d.ndf81.com
DNS Name=*.d.nfd81.com
DNS Name=*.d.nn0e.com
DNS Name=*.d.rpts.org
DNS Name=*.w.0emm.com
DNS Name=*.w.0emn.com
DNS Name=*.w.0enm.com
DNS Name=*.w.0fmm.com
DNS Name=*.w.0mme.com
DNS Name=*.w.1emn.com
DNS Name=*.w.1enm.com
DNS Name=*.w.2enm.com
DNS Name=*.w.3enm.com
DNS Name=*.w.4666.ch
DNS Name=*.w.8d1f.com
DNS Name=*.w.9emn.com
DNS Name=*.w.e0mn.com
DNS Name=*.w.em0n.com
DNS Name=*.w.emn0.com
DNS Name=*.w.m80fg.com
DNS Name=*.w.mdf91.com
DNS Name=*.w.mn0e.com
DNS Name=*.w.mpk01.com
DNS Name=*.w.ndf81.com
DNS Name=*.w.nfd81.com
DNS Name=*.w.nn0e.com
DNS Name=*.w.rpts.org
```

I guess that rule isn't good... Maybe we just go grab the certificate from time to time and just list the domains as black list?

**Comment by jspenguin2017** [comment] 2017-05-30 21:54
```
||d.0emm.com^$third-party,script
||d.0emn.com^$third-party,script
||d.0enm.com^$third-party,script
||d.0fmm.com^$third-party,script
||d.0mme.com^$third-party,script
||d.1emn.com^$third-party,script
||d.1enm.com^$third-party,script
||d.2enm.com^$third-party,script
||d.3enm.com^$third-party,script
||d.4666.ch^$third-party,script
||d.8d1f.com^$third-party,script
||d.9emn.com^$third-party,script
||d.e0mn.com^$third-party,script
||d.em0n.com^$third-party,script
||d.emn0.com^$third-party,script
||d.m80fg.com^$third-party,script
||d.mdf91.com^$third-party,script
||d.mn0e.com^$third-party,script
||d.mpk01.com^$third-party,script
||d.ndf81.com^$third-party,script
||d.nfd81.com^$third-party,script
||d.nn0e.com^$third-party,script
||d.rpts.org^$third-party,script
||w.0emm.com^$third-party,script
||w.0emn.com^$third-party,script
||w.0enm.com^$third-party,script
||w.0fmm.com^$third-party,script
||w.0mme.com^$third-party,script
||w.1emn.com^$third-party,script
||w.1enm.com^$third-party,script
||w.2enm.com^$third-party,script
||w.3enm.com^$third-party,script
||w.4666.ch^$third-party,script
||w.8d1f.com^$third-party,script
||w.9emn.com^$third-party,script
||w.e0mn.com^$third-party,script
||w.em0n.com^$third-party,script
||w.emn0.com^$third-party,script
||w.m80fg.com^$third-party,script
||w.mdf91.com^$third-party,script
||w.mn0e.com^$third-party,script
||w.mpk01.com^$third-party,script
||w.ndf81.com^$third-party,script
||w.nfd81.com^$third-party,script
||w.nn0e.com^$third-party,script
||w.rpts.org^$third-party,script
```

**Comment by uBlock-user** [comment] 2017-05-31 10:09
Or we could just let Easylist and Fanboy add them as they come across and allocate one less responsibility on our shoulders

**Comment by jspenguin2017** [comment] 2017-05-31 14:08
Hum, EasyList does have a few of them in there... I don't think they will block all of them since it does break some sites, and there is no easy way for AdBlock / ABP to fix that.

**Comment by ryanbr** [comment] 2017-06-01 12:32
We blocked them initially, then it caused a few issues with page rendering.

**Comment by uBlock-user** [comment] 2017-06-01 13:11
I have them blocked always, I don't see any issue with page rendering on any domains I visit. Also these domains are used for serving Anti Adblock noticesfyi

**Comment by jspenguin2017** [comment] 2017-06-01 14:07
@ryanbr It cause problem with page rendering because there is a script that ping those domains and destroy the page if the ping fails, but with uBlock Origin, we can crash the detection script. I think it is appropriate for EasyList to not block them, because it is aimed at Adblock Plus.

**Comment by jspenguin2017** [comment] 2017-06-03 14:15
Closing as it still works.

**Closed by jspenguin2017** 2017-06-03 14:15 UTC
Labels: Fixed

**Comment by spodermenpls** [comment] 2017-09-12 23:59
@jspenguin2017 The quoted emn0.com-scripts are causing problems on the German real estate site immobilienscout24.de, when you open an exposé (example: https://www.immobilienscout24.de/expose/98473676?referrer=RESULT_LIST_LISTING&navigationServiceUrl=%2FSuche%2Fcontroller%2FexposeNavigation%2Fnavigate.go%3FsearchUrl%3D%2FSuche%2FS-T%2FWohnung-Miete%2FHamburg%2FHamburg%26exposeId%3D98473676&navigationHasPrev=false&navigationHasNext=true&navigationBarType=RESULT_LIST&searchId=ee38e9a0-a170-3a3e-93e3-44bc0b49d62d#/), one of the scripts whitescreens the whole page, even though uBlock Origin + the AAK-Cont list, which copied the emn0.com-rules from uBlockProtector, are detecting all of them. Is there something that can be done, so I don't have to whitelist the scripts anymore to view the exposés?

**Comment by jspenguin2017** [comment] 2017-09-13 00:30
@spodermenpls The problem with `immobilienscout24.de` should be fixed in the latest release, if you have found any other sites using this Funding Choice or whatever, just let me know, it's a trivial fix but I can't apply it to all websites.

**Comment by spodermenpls** [comment] 2017-09-13 00:45
@jspenguin2017 I deleted my original comment, because the problem is most likely caused by AAK-Cont, not uBProtector. They copied your rules for emn0.com into their .txt-list, but not in the userscript (which I analyzed only after commenting here). By adding the rules to the userscript, the emn0.com-scripts should be effectively disabled, otherwise I will let you know.

**Comment by jspenguin2017** [comment] 2017-09-13 00:58
I am aware that AAK-Cont is out of sync by quite a bit, but I don't have time to update it, and other maintainers are super busy too. I might exclude those rules from AAK-Cont. Thanks for bringing this up.
