### ISSUE TITLE
upon.egybest.xyz

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#1086] opened 2019-10-04 07:47 UTC
### Test link (required):
https://upon.egybest.xyz/

### Screenshot of the web page (including address bar and extension icons) (required):
![2019-10-04_094536](https://user-images.githubusercontent.com/2828165/66190259-ec407280-e68b-11e9-8961-137f1401f719.png)

### Screenshot of the console (press `F12` to bring up the console) (required):
![2019-10-04_094557](https://user-images.githubusercontent.com/2828165/66190277-f6627100-e68b-11e9-972b-230ef279be88.png)

**Environment (Required):**
Operating System and Version: WIN 7 64BIT
Browser and Version: Chrome Version 77.0.3865.90 (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.127+Nano Defender 15.0.0.168

**Your filter lists (Required):**
Built-in (10/11)
Nano Defender Integration​​​​​
Nano filters​​​​​
Nano filters – Annoyance
Nano filters – Whitelist​​​​​
uBlock filters​​​​​
uBlock filters – Annoyances​​​​​
uBlock filters – Badware risks​​​​​
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak

**Ads (2/4)**
Adblock Warning Removal List​​​​​
EasyList​​​​​

**Privacy (1/3)**
EasyPrivacy​​​​​

**Malware domains (2/4)**
Malware Domain List​​​​​
Malware domains​​​​​

**Annoyances (3/5)**
Adguard’s Annoyance List​​​​​
Fanboy’s Annoyance List​​​​​
Fanboy’s Anti-Thirdparty Social (see warning inside list)​​​​​​​​​
Fanboy’s Cookiemonster List​​​​​​​​​
Fanboy’s Social Blocking List​​​​​

Multipurpose (2/5)
NoCoin Filter List
Peter Lowe’s Ad and tracking server list

**Regions, languages (3/36)**
ARA: Liste AR
IRN: Adblock-Iran
RUS: RU AdList

**Comment by mapx-** [comment] 2019-10-04 08:09
you should test adguard extension

**Comment by titosalah** [comment] 2019-10-04 08:18
@mapx-    adguard extension  Not working

![2019-10-04_101744](https://user-images.githubusercontent.com/2828165/66192238-50653580-e690-11e9-83b1-ea6fab815a9d.png)

**Comment by mapx-** [comment] 2019-10-04 08:27
Did you disable other blocking extensions ? (nano, uBo etc)

**Comment by jspenguin2017** [comment] 2019-10-04 15:32
Duplicate of https://github.com/NanoAdblocker/NanoFilters/issues/376

**Closed by jspenguin2017** 2019-10-04 15:32 UTC

**Comment by titosalah** [comment] 2019-10-09 17:37
@jspenguin2017  @mapx-   now i fix it with adguard  

i put this code in adguard  user filter 

![2019-10-09_192930](https://user-images.githubusercontent.com/2828165/66505323-6c6f3980-eacb-11e9-9ff0-7866c2982c93.png)

**can u use this code in nano adblocker or ublock origin**

good.egybest.site###NotificationsAskMsg

good.egybest.site###main > div.msg_box.error:first-child

@@||vidstream.to/cv.php$important,match-case


**website working very good and stream site working but must disable nano or ublock origin**

![2019-10-09_193022](https://user-images.githubusercontent.com/2828165/66505397-96c0f700-eacb-11e9-91ab-09fb0ce73e4a.png)

![2019-10-09_193010](https://user-images.githubusercontent.com/2828165/66505410-a17b8c00-eacb-11e9-8597-e7b115cbeec4.png)

**Comment by jspenguin2017** [comment] 2019-10-09 21:29
I don't believe `$match-case` is supported. Also, `$important` can't be used with exception filters.

**Comment by jspenguin2017** [comment] 2019-10-09 21:30
Either way, continue discussion in the primary issue ( https://github.com/NanoAdblocker/NanoFilters/issues/376 ).
