### ISSUE TITLE
katfile.com

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#385] opened 2017-07-11 22:53 UTC
katfile.com

### Test link (required): 
http://katfile.com/5b46kit7h0tz/Amr.Diab.ArabSeed.CoM.mp3.html
After enter Captcha to begin download
### Screenshot of the web page (required): 
http://i.imgur.com/UP7hYrJ.png
-->
### Screenshot of the console
http://i.imgur.com/oWlJyGf.png
<!--

**Comment by jspenguin2017** [comment] 2017-07-11 23:16
I can't seem to reproduce it... I removed the timer and popup. 
![image](https://user-images.githubusercontent.com/7283682/28094895-aedc92f4-665c-11e7-86d5-6154881be312.png)

**Comment by uBlock-user** [comment] 2017-07-12 01:24
Can't reproduce either!

**Comment by titosalah** [comment] 2017-07-12 05:55
jspenguin2017 thank you    >>> same problem   but timer removed
why every thing work for you only ?
i installed
uBlock Origin
uBlock Protector Extension
+
Pop up blocker for Chrome™ - Poper Blocker
Privacy Badger
Tampermonkey
any problem from last 3 extensions

**Comment by uBlock-user** [comment] 2017-07-12 06:16
Rmove Pop up blocker and Privacy badger, you don't need those and disable TM and then test again.

**Comment by jspenguin2017** [comment] 2017-07-12 14:47
I'm on standard setup, but most people are not, I'm not getting into solving compatibility issues with other extensions, so if it works only for me, then you got to figure out what you installed caused the problem.

**Comment by jspenguin2017** [comment] 2017-07-16 20:43
Still works. Closing.

**Closed by jspenguin2017** 2017-07-16 20:43 UTC
Labels: Fixed
