### ISSUE TITLE
NSFW! rule34hentai.net

### ISSUE THREAD

**Issue by catshitz** [jspenguin2017/uBlockProtector#177] opened 2017-05-03 20:06 UTC
Much appreciated!

**Comment by jspenguin2017** [comment] 2017-05-03 20:19
Hum, the code is pretty early in the page... And they pasted it twice 😂 
Try this: 
`||rule34hentai.net^$script-inject(bab-defuser.js)`

**Comment by catshitz** [comment] 2017-05-03 23:44
Chromium 57.0.2987.133, left only AdBlockProtector script and list, doesn't work.

**Comment by Zhangsun321** [comment] 2017-05-04 01:54
||rule34hentai.net^$script-inject(bab-defuser.js)
doesnt work for me either...

**Comment by jspenguin2017** [comment] 2017-05-04 02:01
Ops... Apparently I don't know the script inject syntax... Sorry about that, List is updated. 
`rule34hentai.net##script:inject(bab-defuser.js)`

**Comment by jspenguin2017** [comment] 2017-05-04 02:05
Hum... That was embarrassing, the syntax is wrong... I think the updated rule should work, but let me properly test it.

**Comment by Zhangsun321** [comment] 2017-05-04 02:05
works... we still love you.. ty... now will that 'line' work for all blockadblock users... just vhanhing the url at the front of it?

**Comment by jspenguin2017** [comment] 2017-05-04 02:09
OK, looks like `eval` is not used elsewhere, we'll just remove it. 
```
rule34hentai.net##script:inject(noeval.js)
rule34hentai.net###babasbmsgx
```

**Comment by catshitz** [comment] 2017-05-04 02:57
Working now, thanks a lot!

**Comment by jspenguin2017** [comment] 2017-05-04 03:44
Awesome!

**Comment by uBlock-user** [comment] 2017-05-04 11:11
> now will that 'line' work for all blockadblock users... just changing the url at the front of it?

Yes.

**Comment by uBlock-user** [comment] 2017-05-04 11:16
@jspenguin2017 You can use those filters or just add the one with `bab-defuser.js` which also defuses the `babmsgx` along with the anti adblock script.

**Comment by Quickneasy** [comment] 2017-05-10 06:23
Apologies if I'm missing something here but is this definitely working? I have both the script and the list installed properly (to my knowledge at least) and this website is still giving me the red screen of adblocker death. I'm not quite sure what to do :(

**Comment by jspenguin2017** [comment] 2017-05-10 14:17
@Quickneasy Then it might be caused by cache. Clear your browser cache and try again. It works for me.

**Comment by jspenguin2017** [comment] 2017-05-10 14:21
@Quickneasy 
It still works for me. Can you configure your setup exactly like this and try again? 
https://github.com/jspenguin2017/AdBlockProtector/blob/master/Notes/Standard%20Setup.MD

**Comment by Quickneasy** [comment] 2017-05-12 02:41
Aha yeah that seems to be it, I weirdly have two 'Adblock Protector List' settings and I only had one enabled so I enabled them both, and I was also missing 'Adblock Warning Removal List' and 
'CHN: EasyList China (中文)'

Apologies for the fact that I missed that step that's my bad! Thank you for the help my dude!

**Comment by catshitz** [comment] 2017-07-18 11:38
@jspenguin2017 Weird thing, with the new Protector Extension all features on, I kept getting pop-up ads like this "stencef.com/MDNNRG9RUSAw" on this site (rule34hentai.net), but the old discontinued script works just fine without it, is there might be a chance that the old rules was forgotten to be added to the new extension?

**Comment by jspenguin2017** [comment] 2017-07-18 13:59
Did we have a script rule for this domain?

**Comment by jspenguin2017** [comment] 2017-07-18 14:04
This should fix it...

**Comment by catshitz** [comment] 2017-07-19 06:40
Thx, but it doesn't help. Now I'm getting massive "stencef.com/***" sort of click-popup ads on various sites (not just rule34hentai.net), it seems to start after I switched the discontinued Ublock Protector Script with the new Protector Extension. There must be something wrong, I'll dig it myself.

**Comment by jspenguin2017** [comment] 2017-07-19 14:00
It needs to be fixed on case by case basis, it is not generic. 
Can you tell me exactly what is broken? I couldn't find anything that broke.

**Comment by jspenguin2017** [comment] 2017-07-19 14:03
Are you absolutely sure that the old Userscript is able to prevent the popup? And not the website changed something? Because I don't recall to have removed anything.

**Comment by uBlock-user** [comment] 2017-07-19 14:55
The Extension has nothing to do with it. The webmaster added new popup script which needs to be patched, simple.

**Comment by uBlock-user** [comment] 2017-07-19 14:58
I can reproduce the popup even after disabling the extension.

**Comment by jspenguin2017** [comment] 2017-07-19 15:03
I think we can just block inline script, doesn't seem to break anything.

**Comment by uBlock-user** [comment] 2017-07-19 15:15
Sure or kill the `open`.

**Comment by jspenguin2017** [comment] 2017-07-19 15:17
Does it go through `open`?

**Comment by uBlock-user** [comment] 2017-07-19 15:19
Actually this is the kind of website where you can just make it permanent and kill it with CSP. The amount of 3rd party script trying to load popups, nasty adware and all that shit is just excruciating to watch.

**Comment by uBlock-user** [comment] 2017-07-19 15:20
Block cookies and site data and then kill the open. Refresh the page and you won't get any popup.

**Comment by jspenguin2017** [comment] 2017-07-19 15:21
That would break login, wouldn't it?

**Comment by uBlock-user** [comment] 2017-07-19 15:23
haven't tested the login as I don't have any account.

**Comment by catshitz** [comment] 2017-07-19 20:14
@jspenguin2017 @uBlock-user Thank you both for your help!
This new rule (uBlock Protector List ||rule34hentai.net^$inline-script) has already helped to prevent click-popup ads like this "stencef.com/***" from being triggered, but it also caused some malfunction like this:
![image](https://user-images.githubusercontent.com/18102209/28387350-473e5a0a-6d01-11e7-9460-81cf8b425fdf.png)
which used to be like this,
![image](https://user-images.githubusercontent.com/18102209/28387361-58bffe82-6d01-11e7-973a-69675bf4921e.png)
and this affects all the column items.
Sorry to bother, but could you please modify or delete this "||rule34hentai.net^$inline-script" in order to make them work again?
Appreciated for your help! I've already post a comment to the webmaster for the click-popup ads problem. Thx again!

**Comment by jspenguin2017** [comment] 2017-07-19 20:53
I'm pretty sure he isn't going to remove the popup. Unless the website is hacked, it won't popup for no reason. 
I fixed it another way, I won't remove inline script blocking, you can override it if you want.

**Comment by jspenguin2017** [comment] 2017-07-19 21:08
I can blacklist the domain but that won't stop the popup, just stop the popup from loading. I don't know how to fix the popup on all domains, if you found a way let me know.

**Comment by jspenguin2017** [comment] 2017-07-19 21:23
For `http://cloudyfiles.org/bcobqn6btt0i`, block CloudFront works, but I can't block it everywhere as it is CDN that only sometimes serve bad stuff.

**Comment by uBlock-user** [comment] 2017-07-20 06:39
Does killing `open` break anything ? Otherwise just use that.

**Comment by jspenguin2017** [comment] 2017-07-20 14:21
New popup scripts no longer use `open`, they use a real mouse click event and forward it to a generated anchor element. Or something similar.

**Comment by uBlock-user** [comment] 2017-07-20 15:09
I cannot reproduce the popup if I kill `open`, so this one is still using the open one way or the other.

**Comment by uBlock-user** [comment] 2017-07-20 15:12
Also we now have addEventListener defuser in ![resources arsenal](https://github.com/uBlockOrigin/uAssets/blob/master/filters/resources.txt#L1816) so you can kill the specific mouse event associated with that popup.

**Comment by jspenguin2017** [comment] 2017-07-20 15:13
I guess they will try to use `open` first, and crash... I guess filter won't work, need no access. 

Filtering `addEventListener` won't work, as every button on the website uses the same mouse click event.

**Comment by uBlock-user** [comment] 2017-07-20 16:04
Blocking the `inline-script` does the job just fine without breaking anything.

**Comment by jspenguin2017** [comment] 2017-07-20 16:10
Whatever works, it can't be generic either way.

**Comment by uBlock-user** [comment] 2017-07-20 16:23
No need to make it generic in the first place, just patch it case by case.

**Comment by jspenguin2017** [comment] 2017-07-21 14:34
Still works. Closing.

**Closed by jspenguin2017** 2017-07-21 14:34 UTC
Labels: Fixed
