### ISSUE TITLE
exame.abril.com.br

### ISSUE THREAD

**Issue by ialexsilva** [jspenguin2017/uBlockProtector#233] opened 2017-05-24 14:23 UTC
Before opening an issue, you MUST read the contribution guideline. Failure to do so may result in a ban. 

### About this website

Test link: http://exame.abril.com.br/

Screenshot:
![capturar](https://cloud.githubusercontent.com/assets/6363160/26408056/2a964dfa-4073-11e7-92d7-7776fcbe265a.PNG) 

### Setup

Browser: Google Chrome Version 58.0.3029.110 (64-bit)

AdBlocker: uBlock Origin

Script Host: 

### Others

Add this custom filter **||*.tinypass.com** fix this issue

**Comment by jspenguin2017** [comment] 2017-05-24 16:18
Can't reproduce. Marking as bad installation as you have not specified the script host that you are using. 
![image](https://cloud.githubusercontent.com/assets/7283682/26413778/47b602b2-406a-11e7-982f-6483813609a0.png)

**Comment by uBlock-user** [comment] 2017-05-24 17:33
Can't reproduce.

**Comment by jspenguin2017** [comment] 2017-05-27 14:13
Looks like it is still working, your issue is most likely due to misconfiguration on your end. Closing.

**Closed by jspenguin2017** 2017-05-27 14:13 UTC
Labels: Bad Installation, Cannot Reproduce
