### ISSUE TITLE
link.tl, vivads.net, bits.yt

### ISSUE THREAD

**Issue by version365** [jspenguin2017/uBlockProtector#835] opened 2018-02-01 11:43 UTC
### Test link (required): 
`http://link.tl/1kGKj`
`http://vivads.net/v4yvi`
`http://bits.yt/RxB28o`

**Comment by jspenguin2017** [comment] 2018-02-01 21:47
Can you explain the problem?

**Comment by jspenguin2017** [comment] 2018-02-01 21:49
@okiehsch An overlay in the first one (`http://link.tl/1kGKj`)
```
link.tl##.mobsplOverlay
link.tl##.mobsplBox
```

I don't see anything wrong with the last two.

**Comment by version365** [comment] 2018-02-02 10:11
Sorry, my bad for not explaining..

Here are some different links..

**Link >>** `http://vivads.net/1ir9E`
**Screenhot >>** https://i.imgur.com/bSmwGOu.png ; https://i.imgur.com/9IAezx7.png

**Link >>** `https://bits.yt/a3u1RA5UK`
**Screenshot >>** https://i.imgur.com/K0Cg9yP.png

Also, I was hoping if you could skip the timers..

**Comment by jspenguin2017** [comment] 2018-02-02 13:52
Weird, the link before redirected me directly. I can reproduce now...

**Comment by jspenguin2017** [comment] 2018-02-03 05:39
@okiehsch I just realized gorhill copied my timer boosting logic, so are you going to fix timers as well?

**Comment by okiehsch** [comment] 2018-02-03 06:10
Well, he has added it, so we should use it.
I do think that boosting every 5 second countdown is a little overkill, so I would limit it's usage, just my two cents.

**Comment by version365** [comment] 2018-02-03 14:11
>I do think that boosting every 5 second countdown is a little overkill

Well, it may be overkill for 1 site; but when you are getting 8-10 of these websites in a row, it's really helpful. And all of the leech sites have them..

**Comment by gorhill** [comment] 2018-02-03 18:46
I don't see any good reason to not boost -- the wait time is meant to force users to see the ads, so there should be no wait time at all since we block the ads.

**Comment by okiehsch** [comment] 2018-02-03 18:57
@jspenguin2017 can I simply copy your `NanoTimer.txt-filters`, or does the booster work differently with `NanoAdblocker`?

**Comment by jspenguin2017** [comment] 2018-02-03 19:01
As long as gorhill didn't change my code. 
Are you merging the full timer file into `uBlock filters`? Or you'll add a specific timer filter?

**Comment by jspenguin2017** [comment] 2018-02-03 19:03
Note that unlike `setTimeout-defuser`, the delay matcher defaults to `1000` and not `match all`. As I'm worried that people will misuse it. 

The version in NanoDefender gives the option to match all though.

**Comment by okiehsch** [comment] 2018-02-03 19:07
Looking at it , he just [imported](https://github.com/uBlockOrigin/uAssets/blob/master/filters/resources.txt#L2085-L2169) your code.
I was thinking about merging it, at the end it's only 3 filters and I will link to th original.

**Comment by jspenguin2017** [comment] 2018-02-03 19:08
It's 3 lines but 140 filters.

**Comment by jspenguin2017** [comment] 2018-02-03 19:10
I don't want to have duplicate filters everywhere, if you guys are taking over timer boosting then I'll leave them to you.

**Comment by okiehsch** [comment] 2018-02-03 19:19
Of course, I meant 3 lines, my bad.
OK, I will add them.

**Comment by okiehsch** [comment] 2018-02-03 19:48
Done.

**Comment by jspenguin2017** [comment] 2018-02-03 20:04
Can you link onto a commit? I won't keep the filters if they are merged into uBlock filters. 
https://github.com/NanoAdblocker/NanoFilters/blob/a57366bd7b42a31d25af47eefc031218826bcae0/NanoFiltersSource/NanoTimer.txt

**Comment by okiehsch** [comment] 2018-02-03 20:41
Sure, no problem.

**Comment by okiehsch** [comment] 2018-02-03 20:42
https://github.com/uBlockOrigin/uAssets/commit/839e67a08791c2967e44b53e4673c4af7224dcd4

**Comment by version365** [comment] 2018-02-06 05:07
@jspenguin2017 
So, now that timer boosting lists are in uAssets, where do request new sites, here or uAssets?

**Comment by jspenguin2017** [comment] 2018-02-06 15:35
uAssets I guess. 
I'll test `link.tl` later.

**Comment by jspenguin2017** [comment] 2018-02-07 01:12
It's working except the "found your file" overlay. I guess that should be removed as well.

**Closed** 2018-02-07 22:28 UTC
Labels: Fixed
