### ISSUE TITLE
ncaa.com

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#344] opened 2017-07-02 15:24 UTC
### Test link (required): 
http://www.ncaa.com/march-madness-live/watch

### Screenshot of the web page (required): 
![ncaa_march_madness_live_-_google_chrome_2017-07-02_17-19-27](https://user-images.githubusercontent.com/27441315/27771242-286b16ae-5f4b-11e7-92f4-641fb24daf91.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![ncaa_march_madness_live_-_google_chrome_2017-07-02_17-21-26](https://user-images.githubusercontent.com/27441315/27771245-306d916a-5f4b-11e7-9ff1-c689af2dcaa9.png)
![ncaa_march_madness_live_-_google_chrome_2017-07-02_17-22-05](https://user-images.githubusercontent.com/27441315/27771247-358bdf58-5f4b-11e7-9610-52c44cb06865.png)

**Comment by jspenguin2017** [comment] 2017-07-02 15:32
Might need a fake API for the two crashes...

**Comment by uBlock-user** [comment] 2017-07-02 16:01
https://github.com/reek/anti-adblock-killer/issues/2965#issuecomment-287168823

Does that still work ?

**Comment by jspenguin2017** [comment] 2017-07-02 16:02
It only helps hiding the message...

**Comment by uBlock-user** [comment] 2017-07-02 16:16
The video doesn't play ?

**Comment by jspenguin2017** [comment] 2017-07-02 16:16
Does it play for you?

**Comment by uBlock-user** [comment] 2017-07-02 16:16
No, that's why I asked.

**Comment by uBlock-user** [comment] 2017-07-02 16:19
Probably a bad filter from Easylist and co. Need to investigate what's broken.

**Comment by jspenguin2017** [comment] 2017-07-02 20:25
Looks like they put ads loading inside their player... 
![image](https://user-images.githubusercontent.com/7283682/27773215-434f3e82-5f32-11e7-9cee-38817a9b156c.png)

**Comment by jspenguin2017** [comment] 2017-07-02 20:41
This works: 
```
@@||ncaa.com^$generichide
! =====
@@||fwmrm.net^$script,domain=ncaa.com
@@||moatads.com^$script,domain=ncaa.com
```
Real ads are still blocked, good enough fro a workaround.

**Comment by jspenguin2017** [comment] 2017-07-02 20:46
`a.xhrSpoof` from AAK-Cont can be handy in this case... It takes uBO filter as input, we might want to implement that differently for our case. 
```JavaScript
        /**
         * Modifies the response text of an XHR request.
         * @method xhrSpoof
         * @param urlFilter {String} Matches the request URL based on the adblock/uBlock filter syntax.
         * @param replacement {String} The replacement for the response text.
         */
        xhrSpoof(urlFilter, replacement) {
            this.xhrSpoof.rules.push(this.urlFilterToRegex(urlFilter));
            this.xhrSpoof.replacements.push(replacement);
            if (!this.xhrSpoof.injected) {
                
                let getReplacementIndex = (url) => {
                    let index = -1;
                    for (let i=0; i<this.xhrSpoof.rules.length; i++) {
                        if (this.xhrSpoof.rules[i].test(url)) {
                            index = i;
                            this.xhrSpoof.rules[i].lastIndex = 0;
                            break;
                        }
                    }
                    return index;
                };
                let getReplacementIndexName = this.exportFunction(getReplacementIndex);
                
                let getReplacementValue = (index) => {
                    return this.xhrSpoof.replacements[index];
                };
                let getReplacementValueName = this.exportFunction(getReplacementValue);
                
                this.addScript(`
                    (function(proxied) {
                        var getReplacementIndex = window.${getReplacementIndexName};
                        delete window.${getReplacementIndexName};    
                        var getReplacementValue = window.${getReplacementValueName};
                        delete window.${getReplacementValueName};

                        window.XMLHttpRequest = function() {
                            var wrapped = new(Function.prototype.bind.apply(proxied, arguments));

                            var open = wrapped.open;
                            wrapped.open = function(method, url, async) {
                                    
                                // Determine absolute path
                                var link = document.createElement("a");
                                link.href = url;

                                let replacementIndex = getReplacementIndex(link.protocol+"//"+link.host+link.pathname+link.search+link.hash);
                                if (replacementIndex > -1) {
                                        Object.defineProperty(this, "responseText", {
                                                writable: true,
                                                value: getReplacementValue(replacementIndex)
                                        });
                                }

                                return open.call(wrapped, method, url, async);
                            };

                            return wrapped;
                        };
                    })(XMLHttpRequest);
                `, this.scriptInjectMode.eval);
            }
        }
```

**Comment by jspenguin2017** [comment] 2017-07-03 04:01
Eh... They use JSONP to load the file... I think just whitelist it is fine, too much work to properly loopback it.

**Comment by jspenguin2017** [comment] 2017-07-03 04:03
Even if we are going to loopback it, it needs to be done in the background page, we still need to whitelist it so uBlock Origin won't interfere with our loopback logic.

**Comment by uBlock-user** [comment] 2017-07-03 07:39
It fetches the streaming API from the ad-server that's why it will remain broken unless whitelisted. The only way to patch this is to replace the player. They purpose fully did that so they can insert their shitty ads anytime they want as long as the domains are whitelisted so this is a compromise, not a solution.

**Comment by jspenguin2017** [comment] 2017-07-03 13:39
Don't have to replace the player, loopback the request is enough, just pretty complex, I might do that.

**Comment by jspenguin2017** [comment] 2017-07-03 17:09
I am able to stop the player from complaining, but the video still doesn't play... 
![image](https://user-images.githubusercontent.com/7283682/27802292-0cdfb742-5fe0-11e7-9dfc-6d92e848ce5b.png)

**Comment by jspenguin2017** [comment] 2017-07-03 17:24
I feel I'm pretty close, I think just the player extension event pump is not right.

**Comment by jspenguin2017** [comment] 2017-07-03 18:11
I just realized video stream is in the ads request JSON...

**Comment by jspenguin2017** [comment] 2017-07-03 18:46
I'm going to update background page so the extension is nooped, that's the best I can do, I don't think there is a way to get around sending request to `fwmrm.net`.

**Comment by jspenguin2017** [comment] 2017-07-03 19:17
I nooped the SDK, alright, good enough.

**Comment by uBlock-user** [comment] 2017-07-03 19:18
Do we need to whitelist those domains anymore ?

**Comment by jspenguin2017** [comment] 2017-07-03 19:19
Yes, otherwise loopback will be canceled. 
```JavaScript
a.staticServer(
    [
        "https://*.moatads.com/*/MoatFreeWheelJSPEM.js",
    ],
    [
        "script",
    ],
    "data:text/javascript;base64,KCgpID0+IHsNCiAgICAidXNlIHN0cmljdCI7DQogICAgd2luZG93LmNvbnNvbGUuZXJyb3IoIlVuY2F1Z2h0IEVycm" +
    "9yOiBGcmVlV2hlZWwgU0RLIGlzIG5vdCBhbGxvd2VkIG9uIHRoaXMgZGV2aWNlISIpOw0KICAgIHdpbmRvdy5Nb2F0RnJlZVdoZWVsSlNQRU0gPSBjbGFz" +
    "cyB7DQogICAgICAgIGluaXQoKSB7IH0NCiAgICAgICAgZGlzcG9zZSgpIHsgfQ0KICAgIH07DQp9KSgpOw==",
);
```
There is no way around sending request to `fwmrm.net` though.

**Comment by jspenguin2017** [comment] 2017-07-03 19:19
Update the second whitelist to `@@|https://*.moatads.com/*/MoatFreeWheelJSPEM.js|$script` so it will not miss the loopback server.

**Comment by jspenguin2017** [comment] 2017-07-03 19:21
You should see a log if loopback is triggered: 
![image](https://user-images.githubusercontent.com/7283682/27805529-71417aba-5ff2-11e7-9090-82dc14cf069c.png)

**Comment by jspenguin2017** [comment] 2017-07-03 19:25
Wait, that's not right, the media file isn't in the JSONP...

**Comment by jspenguin2017** [comment] 2017-07-03 19:56
YES! I got it to work!

**Comment by jspenguin2017** [comment] 2017-07-03 20:16
It should work properly now, remove the old whitelists and add these 3 lines: 
```
|https://jspenguin.com/API/uBlockProtector/Solutions/Blocked.php$important
@@|https://*.moatads.com/*/MoatFreeWheelJSPEM.js$script
@@|http://mmod.v.fwmrm.net/ad/g/*$script,domain=ncaa.com
```
The request to these ads servers are loopbacked internally and the content served is under my control. `https://jspenguin.com/API/uBlockProtector/Solutions/Blocked.php` does not actually exist.

**Comment by jspenguin2017** [comment] 2017-07-03 20:19
You should see this in the console if it worked properly: 
![image](https://user-images.githubusercontent.com/7283682/27806886-8abf34d4-5ffa-11e7-88bb-319d83cd5e14.png)

**Comment by lain566** [comment] 2017-07-03 20:51
@jspenguin2017 Looks great, thanks for your hard work 👍

**Comment by jspenguin2017** [comment] 2017-07-03 23:01
OK, I think the engine is good this time... I couldn't think of another loopback bypass.

**Comment by jspenguin2017** [comment] 2017-07-03 23:05
@uBlock-user If you just don't want to white list them, then you can set them to redirect, but make sure to install uBlock Protector **after** uBlock Origin. 
```
|https://jspenguin.com/API/uBlockProtector/Solutions/Blocked.php$important
|https://*.moatads.com/*/MoatFreeWheelJSPEM.js|$script,redirect=noopjs
|http://mmod.v.fwmrm.net/ad/g/*$script,domain=ncaa.com,redirect=noopjs
```

**Comment by jspenguin2017** [comment] 2017-07-04 01:43
Another generic static server, loopbacking `https://ads.korri.fr/index.js` this time. 
```JavaScript
    //---jQuery plugin---
    //Payload generator
    /*
    console.log(a.mkPayload(() => {
        "use strict";
        window.console.error("Uncaught Error: jQuery uBlock Origin detector plugin is not allowed on this device!");
        try {
            window.$.adblock = false;
        } catch (err) { }
        try {
            window.jQuery.adblock = false;
        } catch (err) { }
    }));
    */
    a.staticServer(
        [
            "https://ads.korri.fr/index.js",
        ],
        [
            "script",
        ],
        "data:text/javascript;base64,KCgpID0+IHsNCiAgICAgICAgInVzZSBzdHJpY3QiOw0KICAgICAgICB3aW5kb3cuY29uc29sZS5lcnJvcigiV" +
        "W5jYXVnaHQgRXJyb3I6IGpRdWVyeSB1QmxvY2sgT3JpZ2luIGRldGVjdG9yIHBsdWdpbiBpcyBub3QgYWxsb3dlZCBvbiB0aGlzIGRldmljZSEiKT" +
        "sNCiAgICAgICAgdHJ5IHsNCiAgICAgICAgICAgIHdpbmRvdy4kLmFkYmxvY2sgPSBmYWxzZTsNCiAgICAgICAgfSBjYXRjaCAoZXJyKSB7IH0NCiA" +
        "gICAgICAgdHJ5IHsNCiAgICAgICAgICAgIHdpbmRvdy5qUXVlcnkuYWRibG9jayA9IGZhbHNlOw0KICAgICAgICB9IGNhdGNoIChlcnIpIHsgfQ0K" +
        "ICAgIH0pKCk7",
    );
```

**Comment by uBlock-user** [comment] 2017-07-04 06:13
Redirect filters are not getting applied, guess whitelist will have to do.

**Comment by uBlock-user** [comment] 2017-07-04 06:14
Forget it, given my strict setup, it will never work. You can call it "Fixed" if that works for you.

**Comment by jspenguin2017** [comment] 2017-07-04 13:50
I just realized my redirects are not good...
```
|https://jspenguin.com/API/uBlockProtector/Solutions/Blocked.php$important
||moatads.com/*/MoatFreeWheelJSPEM.js$script,redirect=noopjs
||mmod.v.fwmrm.net/ad/g/*$script,domain=ncaa.com,redirect=noopjs
```

Also, the whitelists are tuned to guarantee a hit in the loopback server, so the request never actually gets send.

**Comment by jspenguin2017** [comment] 2017-07-04 13:56
I tested it this time, the rules above does work, but generates an warning for uBO: 
![image](https://user-images.githubusercontent.com/7283682/27832964-ed3ee530-608d-11e7-9df6-753230f39742.png)
I'm not sure if it will show if you are not in developer mode. 

It's up to you, this is fixed for me, since I trust my extension to never let whitelisted requests to actually get through.

**Comment by uBlock-user** [comment] 2017-07-04 16:18
Wow, now that you're redirecting it too, you have given birth to a race condition for redirection with uBlock Origin and that warning won't go away until you reboot chrome and you can't disable it from appearing it either.

**Comment by uBlock-user** [comment] 2017-07-04 16:20
It will show up every-time you redirect something and uBO does it too, and it's annoying to look.

**Comment by jspenguin2017** [comment] 2017-07-04 16:20
No, it's not race condition, the order is well documented. Just don't open extension page and you won't see it.

**Comment by uBlock-user** [comment] 2017-07-04 16:23
The only way to avoid that warning from arising is not to use a functionality shared by two or more extensions. In this case, either don't redirect via your extension and redirect via uBO or redirect via your extensions and use a whiteliting filter for uBO.

**Comment by uBlock-user** [comment] 2017-07-04 16:25
It is a race condition, your extension and uBO both try to redirect and Chrome by design picks one that happens to be executed first in a typical  and whichever comes close second will get the warning. I have seen thse kinda warning numerous times when dealing with CSP and I hate it with my heart, because it creates a notification with orange colour so you can't stop yourself until you see it and disable the notification.

**Comment by uBlock-user** [comment] 2017-07-04 16:28
The CSP one that I mentioned - https://github.com/gorhill/uBlock/issues/1941

**Comment by jspenguin2017** [comment] 2017-07-04 16:29
From Chrome docs: 

> If more than one extension attempts to modify the request, the **most recently installed extension wins** and all others are ignored. An extension is not notified if its instruction to modify or redirect has been ignored.

It has a documented behavior, as long as uBlock Protector is installed after, it will reliably win, it is not a "race".

**Comment by uBlock-user** [comment] 2017-07-04 16:31
Yes that is, but the notification part is wrong. It does notify about it's failure. It's not ignored, but rather informed to the user about the failure which only happens in Chrome. If you're okay with the warning then it's fine I'm not, that's why having a same functionality between two extensions always results in this.

**Comment by jspenguin2017** [comment] 2017-07-04 16:33
Then go with whitelist, I'm not going to stop using custom redirect.

**Comment by uBlock-user** [comment] 2017-07-04 16:33
uBlock Protector will win but the warning will also appear when uBlock Origin fails.

**Comment by uBlock-user** [comment] 2017-07-04 16:34
Sure, but if you use it consistently, you will be receiving a lot such warnings on other websites from time to time, so if you're okay with that then it's fine.

**Comment by jspenguin2017** [comment] 2017-07-04 16:52
I go with whitelist. I have them whitelisted in List. I don't think there is a way to bypass the loopback engine, let me know if you found one.

**Comment by uBlock-user** [comment] 2017-07-04 16:56
Can you post the fine-grained whitelisted rules like you did with the redirect filters as I prefer not to whitelist every script from those ad-servers and only keep that're required for the operation to succeed ?

**Comment by jspenguin2017** [comment] 2017-07-04 16:59
Yes, the whitelist in my filter list is the exact same matcher used in my extension, all integration whitelists will be like that. There are a lot of whitelists inherited from AAK, those are hard to replace.

**Comment by ghajini** [comment] 2017-07-06 12:49
Yes too many exceptions(like those of `googlesyndication`)......why not auditing in steps....I know its time consuming...but they r not needed for smart ublock origin.....

**Comment by jspenguin2017** [comment] 2017-07-06 13:15
Like are you going to help cleaning them up? Because I don't have time for that. There are 700+ rules to go over.

**Comment by jspenguin2017** [comment] 2017-07-06 13:23
And I don't have test links for those filters, it's too hard to replace them.

**Comment by ghajini** [comment] 2017-07-06 16:05
Sorry iam not a software developer 😕,if I was ,I may have definitely helped you😀

**Comment by uBlock-user** [comment] 2017-07-06 16:47
Working as expected, there's nothing further to do. You may close it.

**Comment by jspenguin2017** [comment] 2017-07-06 16:54
Cleaning up that 700 whitelists is no easy task, and I have no plan in doing that. 
This website is fixed with an ideal solution, closing.

**Closed by jspenguin2017** 2017-07-06 16:54 UTC
Labels: Fixed
