### ISSUE TITLE
channel4.com

### ISSUE THREAD

**Issue by ghajini** [jspenguin2017/uBlockProtector#450] opened 2017-08-06 08:49 UTC
### Test link (required): 
http://www.channel4.com/programmes/britain-at-low-tide/on-demand/64335-001
### Screenshot of the web page (required): 
http://prntscr.com/g4yt3i

### Screenshot of the console (press `F12` to bring up the console) (required): 
http://prntscr.com/g4yt7e

### Add everything else that you believe to be useful below (optional): 
REquires ***Flash***
REquires ***LOgin*** that you can grab at 
http://bugmenot.com/view/channel4.com  , the 1st account works

also may require ***UK IP(geolock)***

**Comment by jspenguin2017** [comment] 2017-08-06 15:06
Can't reproduce.

**Comment by ghajini** [comment] 2017-08-06 15:24
try uk vpn,its reproducible

**Comment by jspenguin2017** [comment] 2017-08-06 15:32
OK, can reproduce with UK proxy. The detection is built into the player. Since it is Flash, it is low priority.

**Comment by ghajini** [comment] 2017-08-10 15:30
how its `caanot reproduce`

**Comment by jspenguin2017** [comment] 2017-08-10 15:32
You closed it so I assume the issue is gone?

**Comment by ghajini** [comment] 2017-08-10 15:34
nope i just closed because i thought its ~low priority a/c to you, so you will solve that just like ~currently no solution threads,when you have time.................

**Comment by uBlock-user** [comment] 2017-08-13 19:18
`Low Priority` because it's requires flash, that's all.

**Comment by ghajini** [comment] 2017-08-23 14:46
when fix will be available though its low priority

**Comment by jspenguin2017** [comment] 2017-08-23 15:00
I don't know.

**Closed** 2017-08-23 15:07 UTC
Labels: Geo Lock, Low Priority

**Comment by ghajini** [comment] 2017-08-23 15:33
@@/crossdomain.xml$domain=channel4.com
@@||ak.http.anno.channel4.com^$domain=channel4.com
@@||cf.http.anno.channel4.com^$domain=channel4.com
working from easylist,checkout

**Comment by lain566** [comment] 2017-11-19 12:08
It's broken.
<details>

![britain_at_low_tide_-_on_demand_-_all_4_-_google_c_2017-11-19_13-05-52](https://user-images.githubusercontent.com/27441315/32990493-6dc99354-cd2a-11e7-89cf-f01931625589.png)
</details>

**Comment by jspenguin2017** [comment] 2017-11-20 01:25
Confirmed broken, I'll open another issue for it.
