### ISSUE TITLE
gry.wp.pl, wiadomosci.wp.pl

### ISSUE THREAD

**Issue by HateAds** [jspenguin2017/uBlockProtector#384] opened 2017-07-11 21:49 UTC
Test link (required):
https://gry.wp.pl/graja-w-gry-i-zbieraja-pieniadze-dla-potrzebujacych-duzo-pieniedzy-6141622738806401a

Screenshot of the web page (required):

![wp gry](https://user-images.githubusercontent.com/29756590/28092347-4d065f24-6693-11e7-9419-71cbf2d2474e.png)

Screenshot of the console (press F12 to bring up the console) (required):

![wp konsola](https://user-images.githubusercontent.com/29756590/28092360-59a0f794-6693-11e7-90f5-28ab15660e47.png)

**Comment by jspenguin2017** [comment] 2017-07-11 21:50
I'm wondering if I can find a generic solution for Funding Choices.

**Comment by jspenguin2017** [comment] 2017-07-11 21:51
Wait this is not Funding Choices...

**Comment by uBlock-user** [comment] 2017-07-12 01:29
same as https://github.com/jspenguin2017/uBlockProtector/issues/346

**Comment by uBlock-user** [comment] 2017-07-12 01:32
Killing `adonis` or `eval` should do it.

**Comment by HateAds** [comment] 2017-07-13 11:02
The player has stopped playing videos, everything was fine yesterday.

**Comment by jspenguin2017** [comment] 2017-07-13 14:15
I just nooped `atob`, `eval` would work too. It is really early in the page, I guess uBO won't be able to handle it.

**Comment by adreporter** [comment] 2017-07-13 18:53
@jspenguin2017 
https://gry.wp.pl/graja-w-gry-i-zbieraja-pieniadze-dla-potrzebujacych-duzo-pieniedzy-6141622738806401a
Scroll down to this video
<img width="483" alt="asasaas" src="https://user-images.githubusercontent.com/18214146/28182686-3536be9a-680d-11e7-817d-8703e58c9395.PNG">
and please tell me if you can play it. I'm asking it because it doesn't work for me.

**Comment by jspenguin2017** [comment] 2017-07-13 19:01
Nope, but now it does.

**Comment by lain566** [comment] 2017-07-13 19:25
@jspenguin2017 Video player disappears while page is loading

https://wiadomosci.wp.pl/tvp-info-przekracza-kolejne-granice-zobaczcie-jak-nazwali-kontrmanifestantow-6142973419370113a

![tvp_info_przekracza_kolejne_granice _zobaczcie _ja_2017-07-13_21-15-57](https://user-images.githubusercontent.com/27441315/28183733-da1f8510-6810-11e7-8410-9da37fb9b2f0.png)

It should look like this

![tvp_info_przekracza_kolejne_granice _zobaczcie _ja_2017-07-13_21-12-56](https://user-images.githubusercontent.com/27441315/28183716-cb768806-6810-11e7-8582-b5b2f7320699.png)

**Comment by jspenguin2017** [comment] 2017-07-13 19:29
Yea... It's not caused by uBlock Protector though.

**Comment by jspenguin2017** [comment] 2017-07-13 20:14
Need to pin down root cause. Someone help?

**Comment by xxcriticxx** [comment] 2017-07-13 21:31
maybe @szymon1118 can help ?

**Comment by lain566** [comment] 2017-07-13 21:44
@jspenguin2017 Do you want the whitelist?

**Comment by jspenguin2017** [comment] 2017-07-13 21:59
@lain566 As long as it doesn't show ads.

**Comment by jspenguin2017** [comment] 2017-07-13 22:01
Yea, why not. Finding white list is the first step towards fixing an issue.

**Comment by lain566** [comment] 2017-07-13 22:02
```
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=wiadomosci.wp.pl
@@||wp.hit.gemius.pl/gplayer.js$script,domain=wiadomosci.wp.pl
@@||wp.hit.gemius.pl/gdejs/xgde.js$script,domain=wiadomosci.wp.pl
@@||static.criteo.net/js/ld/publishertag.js$script,domain=wiadomosci.wp.pl
```

**Comment by jspenguin2017** [comment] 2017-07-13 22:09
Eh... This will be a pain to loopback... Somehow the old solution isn't able to grab the deleted player, maybe have a DOM watcher and prevent the player from being deleted?

**Comment by lain566** [comment] 2017-07-13 22:49
@jspenguin2017 Does this work for you? 
```
||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,redirect=noopjs,domain=wiadomosci.wp.pl
||static.criteo.net/js/ld/publishertag.js$script,redirect=noopjs,domain=wiadomosci.wp.pl

@@||wp.hit.gemius.pl/gplayer.js$script,domain=wiadomosci.wp.pl
@@||wp.hit.gemius.pl/gdejs/xgde.js$script,domain=wiadomosci.wp.pl
```

**Comment by jspenguin2017** [comment] 2017-07-13 23:49
Yep, that does work.

**Comment by HateAds** [comment] 2017-07-14 10:08
Another site with a broken video player (video doesn't play)
https://www.o2.pl/hot/archeolodzy-w-szoku-120-pestek-w-szkielecie-6143864558925953a

![o2](https://user-images.githubusercontent.com/29756590/28208178-c49f1116-688c-11e7-98cc-a102b306d8d4.png)

**Comment by uBlock-user** [comment] 2017-07-14 11:46
Nooping `atob` or `btoa` can break the websites in general, that's why I suggested, killing `adonis` or `eval`.

**Comment by jspenguin2017** [comment] 2017-07-14 15:46
`atob` is only called for that 3 times, I'll change it if it actually break something.

**Comment by jspenguin2017** [comment] 2017-07-14 15:53
Closing, `wiadomosci.wp.pl` is extracted to another issue.

**Closed by jspenguin2017** 2017-07-14 15:53 UTC
Labels: Fixed

**Comment by MajkiIT** [comment] 2017-07-17 16:11
@jspenguin2017 problem is not solved. IF I add this `@@||www.adiode.com/http$xmlhttprequest,domain=gry.wp.pl` I don't see alert.

**Comment by jspenguin2017** [comment] 2017-07-17 18:24
@MajkiIT What alert? Which page? Why that rule? 
Everything seems to be working as intended for me.

**Comment by MajkiIT** [comment] 2017-07-17 19:05
This https://user-images.githubusercontent.com/29756590/28092347-4d065f24-6693-11e7-9419-71cbf2d2474e.png

on page ==>https://gry.wp.pl/graja-w-gry-i-zbieraja-pieniadze-dla-potrzebujacych-duzo-pieniedzy-6141622738806401a

Rule, because I test that rule block page.

**Comment by jspenguin2017** [comment] 2017-07-17 20:01
It works fine for me with or without that rule. I don't see why should I add that rule.

**Comment by hawkeye116477** [comment] 2017-07-17 20:58
@jspenguin2017 I chcecked and on this page I see two the same movies, something is not right. If i disable uBlock Protector, I see correct, two different movies.

**Comment by jspenguin2017** [comment] 2017-07-17 21:00
Yea, the background worker is pretty fragile... It has to do with the generic worker.

**Comment by jspenguin2017** [comment] 2017-07-17 21:12
Is this better?

**Comment by hawkeye116477** [comment] 2017-07-17 21:14
@jspenguin2017 Yes, thanks.

**Comment by HateAds** [comment] 2017-07-22 12:08
https://gry.wp.pl/ctrl-odc-3-znakomite-gry-o-ktorych-nie-slyszeliscie-6145233467373697a
@jspenguin2017  The player has stopped working
![1](https://user-images.githubusercontent.com/29756590/28490956-b5f6c194-6ee6-11e7-8267-e75769565ebd.png)

**Comment by jspenguin2017** [comment] 2017-07-22 14:00
I think I found the problem. It wasn't replacing just the first player.

**Comment by HateAds** [comment] 2017-07-22 16:16
@jspenguin2017 It's working now, thank you.
