### ISSUE TITLE
hackintosh.zone, hackintosh.computer, and related domains

### ISSUE THREAD

**Issue by Eva850** [jspenguin2017/uBlockProtector#35] opened 2016-11-19 21:53 UTC
Chrome
Tampermonkey + Anti Adblock Killer + Adblock Protector
Ublock Origin standard configuration + AAK list + adblock protector list
Site works for a while, then BlockAdBlock screen appears.
![blockadblock](https://cloud.githubusercontent.com/assets/20646455/20458624/83e9aab0-aeaa-11e6-8316-6145d871776a.png)

**Comment by X01X012013** [comment] 2016-11-19 22:06
Finally someone knows how to properly use BlockAdBlock, site won't load unless BAB runs, I'll have a closer look.

**Comment by X01X012013** [comment] 2016-11-19 22:31
Hi, this is fixed in 3.0.6, however, AAK has some old code that will break the website, so please disable AAK when viewing this website.

**Comment by Eva850** [comment] 2016-11-19 23:41
It works for me, thanks. I will close this issue.

**Comment by uBlock-user** [comment] 2017-04-18 15:31
Not working anymore! Needs to be patched again.

**Comment by jspenguin2017** [comment] 2017-04-18 18:12
Yep, you are right, it's now doing a redirect.

**Comment by uBlock-user** [comment] 2017-04-18 18:21
Can you patch that redirect ?

**Comment by jspenguin2017** [comment] 2017-04-18 18:40
They have added a lot of in-line scripts... Blocking all in-line scripts seems to break the page... 
This is what I got so far: 
```
||hackintosh.*$inline-script
hackintosh.*###loader-wrapper
```

```JavaScript
if (a.domInc(["hackintosh"])) {
    a.on("DOMContentLoaded", function() {
        a.$("#babasbmsgx").remove();
        a.$("loader-wrapper").remove();
        a.doc.body.style.setProperty("visibility", "visible", "important");
    });
}
```

**Comment by uBlock-user** [comment] 2017-04-18 19:03
That's perfect, add it and bag it!

**Comment by uBlock-user** [comment] 2017-04-18 19:06
For hackintosh.computer, you will need to block one or more 1st party scripts too fyi!

**Comment by uBlock-user** [comment] 2017-04-18 19:10
Add this filter too - `||hackintosh.*/doubleclick/` 

That will do the job.

**Comment by jspenguin2017** [comment] 2017-04-18 19:29
That displays the page... but is the page properly rendered? I think it is missing some sections...

**Comment by uBlock-user** [comment] 2017-04-18 19:34
You're right, it's a bit broken. I will post images to differentiate the difference.

unbroken - https://i.gyazo.com/37a2714f330a0722a3630d85a95eff7f.png

broken - https://i.gyazo.com/6088b5c4d16738e106327fbb72f82410.png

**Comment by jspenguin2017** [comment] 2017-04-18 22:55
Let's summarize what we know now: 

* The detection script is one of the in-line ones. 
* BlockAdBlock is still there, so our old solution is still needed. 
* `adblock` flag affects Google Analytics event, but this isn't what is causing redirect, but we should still lock it to `false`. 
* A randomly named function that looks like this is quite suspicious, it does tamper with the back button, but doesn't seem to have any redirect in it: 
```JavaScript
function jiowmecfzy(){
document.write("<!DOCTYPE html><html><head></head><body><div align='cent"
 +"er'><b><img style='max-width:100%;' src='http://f.cl.ly/items/3F0t2c0L"
 +"360t1A1l0A2W/disable-adblock.png'><br><a href='https://www.hackintosh.zone/'>[ Try again ]</a></b"
 +"><br><strong>If it doesn't work disable AD Block completely, Click Try "
 +"Again, Enable ADBlock, Add This website to Exceptional List</strong><b"
 +"r><div align='center' id='3727f6ecab' class='pagefair-acceptable'></di"
 +"v></div></body></html>");
   window.history.pushState("object or string", "Hackintosh Zone", "/adblock/stop_adblock.html");
}
```

* There is nothing in-line that actually do the redirect, but blocking all in-line scripts prevents the redirect, so it must be one of the scripts that are loaded in-line. This is suspicious: `https://www.hackintosh.zone/ips_4/ads/combine.js`

**Comment by jspenguin2017** [comment] 2017-04-18 23:34
I'm still trying to pin down the code that does the redirect... If someone found it, please let me know.

**Comment by uBlock-user** [comment] 2017-04-18 23:53
hackintosh.zone/advjs/bin/jso.php 

Will that help ?

**Comment by jspenguin2017** [comment] 2017-04-19 00:09
Hum... It's an obfuscator, but why do we need it... It doesn't de-obfuscate...

**Comment by F4z** [comment] 2017-04-19 00:45
I do not have idea why, but if I block this - https://www.hackintosh.zone/donate/donate.php - I am not redirected, so maybe it will be helpfull.

`||hackintosh.zone/donate/donate.php^$inline-script`
or 
`||hackintosh.zone/donate/donate.php`

**Comment by uBlock-user** [comment] 2017-04-19 01:28
Yep, that works just fine for the `.zone` domain.

**Comment by jspenguin2017** [comment] 2017-04-19 02:13
@F4z Thanks, added to List.

**Comment by uBlock-user** [comment] 2017-04-19 02:24
`hackintosh.computer` still remains unfixed though

**Comment by uBlock-user** [comment] 2017-04-19 02:28
They're also using CSS bait - 

```javascript
/* Anti Adblock */
<style>
.post .ab {
 display: none!important;
}
html.ab .post .ab {
 display: inline-block! important;
}
</style>
```

**Comment by jspenguin2017** [comment] 2017-04-19 02:48
@uBlock-user 
How is that a CSS bait? Can you explain it a bit? 
I don't see anything wrong with the web page, except that it shows some ad placeholders: 
![image](https://cloud.githubusercontent.com/assets/7283682/25161291/58259314-2478-11e7-8401-f075bcdf70ca.png)

**Comment by uBlock-user** [comment] 2017-04-19 11:45
Eh,,, I see this - https://i.gyazo.com/b379cb1abe35235177d10e4ce6d8bfec.png

**Comment by uBlock-user** [comment] 2017-04-19 12:01
adding `a.readOnly("functionadredirecter", function () { });` kills the redirection, but the CSS is a bit broken.

**Comment by jspenguin2017** [comment] 2017-04-19 13:26
@uBlock-user Are you sure that you have the latest Script and List installed?

**Comment by uBlock-user** [comment] 2017-04-19 13:47
I don't use the list, that's why I asked, which filters do I need to add.

**Comment by jspenguin2017** [comment] 2017-04-19 14:17
The rule that is added to List is `||hackintosh.*/donate/donate.php`.

**Comment by jspenguin2017** [comment] 2017-04-24 19:38
OK, `hackintosh.computer` is now fully fixed, `hackintosh.zone` broke again... 
Test link: https://www.hackintosh.zone/file/46-nireshs-mac-os-x-mountain-lion-for-amd-and-intel-1085/

**Comment by okiehsch** [comment] 2017-04-24 19:57
Hm, if you don't mind me asking, if you use uBO, which I assumed, what is broken on your end?
If you don't use uBO, feel free to ignore this post.

**Comment by jspenguin2017** [comment] 2017-04-24 19:59
@okiehsch After a few seconds, it redirects me to `https://www.hackintosh.zone/adblock/stop_adblock.html`
Blocking `donate.php` seems to no longer work.

**Comment by okiehsch** [comment] 2017-04-24 20:00
This has been fixed in https://github.com/uBlockOrigin/uAssets/commit/8f938c2fd381775a10e99b292a98a3871af88cba and the fix still works on my end.

**Comment by jspenguin2017** [comment] 2017-04-24 20:04
@okiehsch Well, looks like my filters were not updated. Working fine now 👍

**Comment by jspenguin2017** [comment] 2017-04-25 14:25
Looks good, let's close this now.

**Comment by ghajini** [comment] 2017-05-13 07:33
Not working....or is it due to core update of adblock protector

**Comment by jspenguin2017** [comment] 2017-05-13 14:57
@ghajini Core update has not started. I see the problem: They added `/adsense/` in their resource URLs
![image](https://cloud.githubusercontent.com/assets/7283682/26026530/2a37b05e-37ba-11e7-9864-9515ad56574d.png)

**Comment by uBlock-user** [comment] 2017-09-14 08:36
`hackintosh.computer` is screwiing up the CSS upon detection

**Comment by uBlock-user** [comment] 2017-09-14 08:39
```
hackintosh.computer##script:inject(abort-current-inline-script.js, jQuery, ai_adb)
||hackintosh.computer^$csp=style-src 'self' fonts.googleapis.com *.gstatic.com *.hackintosh.computer
```

**Comment by jspenguin2017** [comment] 2017-09-14 21:21
OK I'll have a look.

**Comment by jspenguin2017** [comment] 2017-09-14 21:23
I don't really see the problem: 
![image](https://user-images.githubusercontent.com/7283682/30456386-973b8420-9960-11e7-9ea7-b0cfe0948500.png)

**Comment by jspenguin2017** [comment] 2017-09-15 02:05
Can't reproduce the problem.

**Comment by uBlock-user** [comment] 2017-09-15 04:39
I can reproduce, it shows a white body and if I patch the CSS via style filter, then script checks for two ai_adb cookies and if they're not present then redirects me to https://www.hackintosh.computer/adblock/stop_adblock.html
which I patch via the script filter.

**Comment by jspenguin2017** [comment] 2017-09-15 12:27
When do those cookies get set? I am never redirected to that page.

**Comment by jspenguin2017** [comment] 2017-09-15 12:43
I see the problem. It should be an easy fix though.

**Closed** 2017-09-15 12:49 UTC
Labels: Test In Progress
