### ISSUE TITLE
telegraph.co.uk

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#951] opened 2018-06-10 22:42 UTC
### Test link (required):
https://www.telegraph.co.uk/tennis/2018/06/10/rafael-nadal-vs-dominic-thiem-french-open-2018-mens-final/

### Screenshot of the web page (including address bar and extension icons) (required):
![2018-06-11_003827](https://user-images.githubusercontent.com/2828165/41207110-f8f59c04-6d0f-11e8-8600-b55217af379c.png)

### Screenshot of the console (press `F12` to bring up the console) (required):
![2018-06-11_003902](https://user-images.githubusercontent.com/2828165/41207113-0378cc82-6d10-11e8-9986-7721c940c56c.png)

Environment (Required):
Operating System and Version: WIN 7 SP1 64BIT
Browser and Version: Chrome Version 67.0.3396.79 (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.53+Nano Defender 14.50

Your filter lists (Required):
My filters​​​​​
Nano Defender Integration​​​
Nano filters​
Nano filters – Timer bypassing (sometimes works)​
Nano filters – Whitelist​​​​​
uBlock filters​
uBlock filters – Badware risks
uBlock filters – Privacy​​​​​
uBlock filters – Resource abuse
uBlock filters – Unbreak
Ads (2)
Adblock Warning Removal List​
EasyList
Privacy (1)
EasyPrivacy​
Malware Domain List​​​​​
Malware domains​
Peter Lowe’s Ad and tracking server list
Regions, languages (4)
ARA: Liste AR
IRN: Adblock-Iran​
RUS: Adguard Russian Filter​
RUS: RU AdList​

Your custom filters (Required if you have any):
https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_browser.txt

**Comment by jspenguin2017** [comment] 2018-06-10 22:59
Can't reproduce. 
![image](https://user-images.githubusercontent.com/7283682/41207252-8e403ecc-6ccf-11e8-8324-78716423030f.png)

**Comment by zaphodbeebblebrox** [comment] 2018-06-15 03:30
I can reproduce inconstantly with nano adbocker + defender. Appears to be fixed with `@@||telegraph.co.uk^$generichide`.

**Comment by jspenguin2017** [comment] 2018-06-16 00:32
Fixed.

**Closed by jspenguin2017** 2018-06-16 00:32 UTC
Labels: Fixed
