### ISSUE TITLE
crackle.com

### ISSUE THREAD

**Issue by det427** [jspenguin2017/uBlockProtector#622] opened 2017-09-30 16:30 UTC
`https://www.crackle.com/party-boat`

### Screenshot of the web page (required): 
![image](https://user-images.githubusercontent.com/32418037/31047519-3ad100c6-a5c1-11e7-8a51-4ce08bd61c52.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 

![image](https://user-images.githubusercontent.com/32418037/31047538-98f3d82c-a5c1-11e7-9d84-7b5fbd2772fd.png)

### Add everything else that you believe to be useful below (optional): 

Using Chrome Version 61.0.3163.100 (Official Build) (64-bit)
The only way I can watch a video is if I turn off uBlock Origin but then I get the ads.

**Comment by uBlock-user** [comment] 2017-09-30 18:08
Has `GeoLock`

**Comment by uBlock-user** [comment] 2017-09-30 18:10
That link also gives me a `No media found.` error

**Comment by jspenguin2017** [comment] 2017-09-30 18:14
Try this link? https://www.crackle.com/the-interview/2499136

**Comment by det427** [comment] 2017-09-30 18:21
Just a blank screen

![image](https://user-images.githubusercontent.com/32418037/31048415-79e7db3a-a5d1-11e7-8df0-fd9d204dfea1.png)

**Comment by uBlock-user** [comment] 2017-09-30 18:22
Same but now with a 404 image and the only thing I'm blocking in this instance is adservers.

![](https://i.gyazo.com/0db7af70461534f0731b326f957d130a.png)

**Comment by uBlock-user** [comment] 2017-09-30 18:24
They probably have ads integrated with the player very deep.

**Comment by ghajini** [comment] 2017-10-01 18:12
hii....it has geolock 
can you make your setup like this on order to simplify debugging for you
![setup](https://user-images.githubusercontent.com/20338483/31057521-b0486358-a701-11e7-99f8-a9f422497083.png) to access the site...

***console output***
[console.zip](https://github.com/jspenguin2017/uBlockProtector/files/1347390/console.zip)

yep disabling ublock origin plays video 
![opera_2017-10-01_23-28-08](https://user-images.githubusercontent.com/20338483/31057548-26c4578a-a702-11e7-9d08-4ae841a6f5d8.png)

and inserts ads
![stream ads](https://user-images.githubusercontent.com/20338483/31057551-312a1c1e-a702-11e7-8cc2-d68082944f86.png)

**Comment by jspenguin2017** [comment] 2017-11-24 14:38
This works: 
```
@@||crackle.com/vendor/AdManager.js$script,first-party
@@||secure-dcr.imrworldwide.com/novms/js/$script,domain=crackle.com
```
Not sure if it will allow ads in, I didn't see any but need further testing.

**Comment by lain566** [comment] 2017-11-24 18:58
Yep, that seems to work, I don't see ads either.

**Comment by lain566** [comment] 2017-11-24 22:58
Test this, fast forward to video end, and wait for it to automatically skip to the next video.
`https://www.crackle.com/playlist/2128307/2503629`

Player gets stuck again.

**Comment by jspenguin2017** [comment] 2017-11-24 23:06
Yea, apparently it only works for the first video it plays, and you need to click the video to start it.

**Comment by jspenguin2017** [comment] 2017-11-24 23:49
The solution doesn't fully correct the problem but helps, and doesn't have known side effect, I'll add it for now.

**Comment by lain566** [comment] 2017-11-25 19:24
This filter solves it, videos are played automatically and the player does not get stuck ,but the ads are loaded.
`@@crackle.com/ad/$script`


Could this be the ads manifest?
<details>

`http://fwlive.crackle.com/ad/g/1?prof=151933%3Acrackle_html5_site_live&nw=151933&caid=2503335&vdur=5574&csid=cr.crack.html5.opus_movies&cd=1366%2C768&vclr=js-6.14.0.1-4586cdac-201703071903&resp=json&orig=https%3A%2F%2Fwww.crackle.com&cbfn=tv.freewheel.SDK._instanceQueue%5B%27Context_5%27%5D.requestComplete&flag=%2Bplay-uapl%2Bsltp%2Bemcr%2Bunka%2Bunks%2Bfbad%2Bslcb%2Bnucr%2Baeti%2Brema%2Bvicb;seg=1605207&seg=2423927&_fw_h_x_flash_version=0%2C0%2C0%2C0&_fw_dpr=1.00;slid=ad1600640&ptgt=p&h=640&w=1600&flag=%2Bcmpn%2Bnsit&prct=text%2Fhtml_doc_lit_mobile%2Ctext%2Fhtml_doc_ref;slid=companionSlot&ptgt=p&h=250&w=300&flag=%2Bcmpn&prct=text%2Fhtml_doc_lit_mobile%2Ctext%2Fhtml_doc_ref;slid=ad72890&ptgt=p&h=90&w=728&flag=%2Bcmpn%2Bnsit&prct=text%2Fhtml_doc_lit_mobile%2Ctext%2Fhtml_doc_ref`
</details>

**Comment by jspenguin2017** [comment] 2017-11-25 19:29
Looks familiar, should be patchable with `a.dynamicServer`.

**Comment by ghajini** [comment] 2018-03-22 14:42
As per last comment is it still workable

**Comment by jspenguin2017** [comment] 2018-03-22 15:10
Yea, it's a small problem so I didn't get to it.

**Comment by det427** [comment] 2018-05-11 16:52
Cannot even open the website now!
It states Initialization Failure.
The new website name is sonycrackle.com

**Comment by jspenguin2017** [comment] 2018-05-11 16:57
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/2248

**Comment by jspenguin2017** [comment] 2018-05-11 16:57
Let's handle this upstream. Issue filed.

**Closed by jspenguin2017** 2018-05-11 16:57 UTC
Labels: Duplicate, Geo Lock
