### ISSUE TITLE
igg-games.com

### ISSUE THREAD

**Issue by JourneyOver** [jspenguin2017/uBlockProtector#1087] opened 2019-10-10 04:20 UTC
### Test link (required):

https://igg-games.com/

### Screenshot of the web page (including address bar and extension icons) (required):

![P0dRFdQ](https://user-images.githubusercontent.com/13910285/66537993-2e344300-eae8-11e9-9e56-9b2f9a65c1aa.jpg)

### Screenshot of the console (press `F12` to bring up the console) (required):

![10-09-2019_22-58-54](https://user-images.githubusercontent.com/13910285/66538052-6d629400-eae8-11e9-8fa5-141be2bec82f.png)

### Environment (Required):

- Operating System and Version: Win10 x64 bit 
- Browser and Version: Chrome Version 77.0.3865.90 
- Adblocker and Version: Nano Adblocker 1.0.0.127 & Nano Defender 15.0.0.168

#### Your filter lists (Required):

![10-09-2019_23-12-47](https://user-images.githubusercontent.com/13910285/66538520-5624a600-eaea-11e9-94b9-25f9c55a18a3.png)

#### Your custom filters (Required if you have any):

http://winhelp2002.mvps.org/hosts.txt
https://mirror1.malwaredomains.com/files/immortal_domains.txt
https://raw.githubusercontent.com/FadeMind/hosts.extras/master/StreamingAds/hosts
https://easylist-downloads.adblockplus.org/adwarefilters.txt
https://www.fanboy.co.nz/r/fanboy-ultimate.txt
https://raw.githubusercontent.com/IDKwhattoputhere/uBlock-Filters-Plus/master/uBlock-Filters-Plus.txt

### Add everything else that you believe to be useful below (optional):

**Comment by jspenguin2017** [comment] 2019-10-10 15:26
Duplicate of https://github.com/NanoMeow/QuickReports/issues/1978

**Closed by jspenguin2017** 2019-10-10 15:26 UTC
