### ISSUE TITLE
kissanime.ru

### ISSUE THREAD

**Issue by gavbn** [jspenguin2017/uBlockProtector#961] opened 2018-07-02 13:18 UTC
### Test link (required):

http://kissanime.ru/Anime/Boku-no-Hero-Academia-3rd-Season/Episode-051?id=147357&s=rapidvideo

### Screenshot of the web page (including address bar and extension icons) (required):

![capture](https://user-images.githubusercontent.com/23123477/42166017-5f6de702-7e27-11e8-9694-68771e8ac73c.PNG)

### Screenshot of the console (press `F12` to bring up the console) (required):

![captura](https://user-images.githubusercontent.com/23123477/42166097-94eb5aae-7e27-11e8-8d31-ae2193e2aa9e.PNG)

### Explain what was not right (optional if obvious):The site is blocking the adblock and
the site is blocking the users who uses any kind of adblock.So,can you please help me out?

### Environment (Required):

- Operating System and Version: Windows 7 ultimate X64
- Browser and Version: Chrome,67
- Adblocker and Version: Nano adblock v1.0.0.55
Nano defender 15.0.0.2

#### Your filter lists (Required):

![capturb](https://user-images.githubusercontent.com/23123477/42166311-415bc22e-7e28-11e8-87e7-cfb98877d075.PNG)
![capturh](https://user-images.githubusercontent.com/23123477/42166315-453b982e-7e28-11e8-9c72-cbe428acc2ee.PNG)

**Comment by jspenguin2017** [comment] 2018-07-02 13:45
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/2708

**Closed** 2018-07-02 13:44 UTC
Labels: Duplicate

**Comment by gavbn** [comment] 2018-07-02 13:46
Is it working for you?

**Comment by jspenguin2017** [comment] 2018-07-02 13:54
It's listed on the home page, they change their logic every day.

**Comment by gavbn** [comment] 2018-07-02 13:55
But,they ban users who use any kind of adblock,do you know any solution for this?

**Comment by jspenguin2017** [comment] 2018-07-02 14:13
Again, they change it every day, and we don't have time to deal with it.

**Comment by rogersachan** [comment] 2018-07-02 18:19
kissanime.ru is now full-on banning users with adblockers on.

**Comment by NatoBoram** [comment] 2018-07-31 03:33
@rogersachan They're not technically banning users, they're just removing the video a few seconds after the video is fully displayed and ads are blocked. In fact, if you're quick enough, you could open the `iframe` in another tab with right click and just watch the video from there.

One way to counter this would be to disable ad blocker, load the video, then select the iframe they're deleting after ads are blocked, and create a userscript that duplicates that iframe somewhere else (or just open a new tab with the iframe). They'll delete their own iframe, but not yours.

But it's a hassle to do, and I don't want to see ads anyway, so I'm just using kissanime.ac instead. Shit player compared to kissanime.ru, but hey, at least I'm not paying *and* I'm not seeing ads.
