### ISSUE TITLE
gala.fr

### ISSUE THREAD

**Issue by maxxyme** [jspenguin2017/uBlockProtector#438] opened 2017-07-27 10:44 UTC
### Test link (required): 
http://www.gala.fr/l_actu/news_de_stars/photo_-_angelina_jolie_paralysee_du_visage_l_actrice_se_confie_neuf_mois_apres_son_divorce_400352

### Screenshot of the web page (required): 
http://imgur.com/McVSkbt

### Screenshot of the console (press `F12` to bring up the console) (required): 
http://imgur.com/AVbo86p

### Add everything else that you believe to be useful below (optional): 
The home page gala.fr doesn't redirect at first sight, but if you refresh the page, you'll get redirected to (sorry the link has blanks so it doesn't render properly...)
 http://www.gala.fr/maf/telechargement#title=Stars : toute l'actu des stars - Gala&url=http://www.gala.fr/
the same way you get redirected when trying to access an article (like the one I put the link above).
However all this redirect process doesn't happen when coming from Google News.

**Comment by uBlock-user** [comment] 2017-07-27 11:26
Can't reproduce.

**Comment by uBlock-user** [comment] 2017-07-27 11:26
`||gala.fr/ads.js$xmlhttprequest,redirect=nooptext`

**Comment by jspenguin2017** [comment] 2017-07-27 13:57
Can't reproduce... Refreshed multiple times. Can you test if some of your other extensions is causing problem?

**Comment by uBlock-user** [comment] 2017-07-27 15:15
The only way I can reproduce is if I block the `XHR` from `gala.fr/ads.js`

**Comment by jspenguin2017** [comment] 2017-07-27 16:12
I don't see that file in logger...

**Comment by uBlock-user** [comment] 2017-07-27 17:22
delete cookies and site data and close the current tab, then open the website in new tab along with the logger.

**Comment by jspenguin2017** [comment] 2017-07-27 17:48
Still can't reproduce.

**Comment by maxxyme** [comment] 2017-07-27 23:09
OK, tested with a new Person in Chrome, installed uBlock Origin, forced update of default checked lists, no problem.
Checked FRA (French EasyList), get the problem.

So as long as you already told in another issue that you won't support it, I'll see with them.

**Comment by jspenguin2017** [comment] 2017-07-27 23:16
Alright, closing then.

**Closed by jspenguin2017** 2017-07-27 23:16 UTC
Labels: Cannot Reproduce

**Comment by uBlock-user** [comment] 2017-07-28 06:34
> Still can't reproduce.

That was not for reproduction of anti adblock but rather the effort you need to make to help you see the entry of /ads.js in the logger specifically

**Comment by jspenguin2017** [comment] 2017-07-28 13:56
Yea, I still can't see that file in logger.

**Comment by maxxyme** [comment] 2017-09-07 09:36
That's probably geo-located, as you're in Canada, while it's a French website.

**Comment by jspenguin2017** [comment] 2017-09-07 22:42
If you mean geo locked then no, it's not: 
![image](https://user-images.githubusercontent.com/7283682/30188404-895607ce-93eb-11e7-95f6-996d36aca4d9.png)

**Comment by maxxyme** [comment] 2017-09-08 08:51
I meant the ads... you're Canada = not interesting for them, so no ads.
